//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class AI_Items : XPLiteObject
    {
        Guid fAI_Items_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid AI_Items_ID
        {
            get { return fAI_Items_ID; }
            set { SetPropertyValue<Guid>(nameof(AI_Items_ID), ref fAI_Items_ID, value); }
        }
        AI_Main fAI_Main_ID;
        [Association(@"AI_ItemsReferencesAI_Main")]
        public AI_Main AI_Main_ID
        {
            get { return fAI_Main_ID; }
            set { SetPropertyValue<AI_Main>(nameof(AI_Main_ID), ref fAI_Main_ID, value); }
        }
        string fTransaction_Number;
        [Size(20)]
        public string Transaction_Number
        {
            get { return fTransaction_Number; }
            set { SetPropertyValue<string>(nameof(Transaction_Number), ref fTransaction_Number, value); }
        }
        int fTransaction_Index;
        public int Transaction_Index
        {
            get { return fTransaction_Index; }
            set { SetPropertyValue<int>(nameof(Transaction_Index), ref fTransaction_Index, value); }
        }
        decimal fPaid_Amount;
        public decimal Paid_Amount
        {
            get { return fPaid_Amount; }
            set { SetPropertyValue<decimal>(nameof(Paid_Amount), ref fPaid_Amount, value); }
        }
        string fInvoice_Number;
        [Size(25)]
        public string Invoice_Number
        {
            get { return fInvoice_Number; }
            set { SetPropertyValue<string>(nameof(Invoice_Number), ref fInvoice_Number, value); }
        }
        DateTime fCreated_Date_Time;
        public DateTime Created_Date_Time
        {
            get { return fCreated_Date_Time; }
            set { SetPropertyValue<DateTime>(nameof(Created_Date_Time), ref fCreated_Date_Time, value); }
        }
        pl_Transaction fTransaction_Type;
        [Association(@"AI_ItemsReferencespl_Transaction")]
        public pl_Transaction Transaction_Type
        {
            get { return fTransaction_Type; }
            set { SetPropertyValue<pl_Transaction>(nameof(Transaction_Type), ref fTransaction_Type, value); }
        }
        decimal fOriginal_Amount;
        public decimal Original_Amount
        {
            get { return fOriginal_Amount; }
            set { SetPropertyValue<decimal>(nameof(Original_Amount), ref fOriginal_Amount, value); }
        }
        CM_Main fCM_Main_ID;
        [Association(@"AI_ItemsReferencesCM_Main")]
        public CM_Main CM_Main_ID
        {
            get { return fCM_Main_ID; }
            set { SetPropertyValue<CM_Main>(nameof(CM_Main_ID), ref fCM_Main_ID, value); }
        }
        string fCM_Name;
        public string CM_Name
        {
            get { return fCM_Name; }
            set { SetPropertyValue<string>(nameof(CM_Name), ref fCM_Name, value); }
        }
        string fCM_Account_Number_Text;
        [Size(25)]
        public string CM_Account_Number_Text
        {
            get { return fCM_Account_Number_Text; }
            set { SetPropertyValue<string>(nameof(CM_Account_Number_Text), ref fCM_Account_Number_Text, value); }
        }
        Guid fTransaction_Guid;
        public Guid Transaction_Guid
        {
            get { return fTransaction_Guid; }
            set { SetPropertyValue<Guid>(nameof(Transaction_Guid), ref fTransaction_Guid, value); }
        }
    }

}
