//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class AN_Main : XPLiteObject
    {
        Guid fAN_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid AN_ID
        {
            get { return fAN_ID; }
            set { SetPropertyValue<Guid>(nameof(AN_ID), ref fAN_ID, value); }
        }
        int fFree_Account_Number;
        public int Free_Account_Number
        {
            get { return fFree_Account_Number; }
            set { SetPropertyValue<int>(nameof(Free_Account_Number), ref fFree_Account_Number, value); }
        }
    }

}
