//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class CD_Address : XPLiteObject
    {
        Guid fCD_Address_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid CD_Address_ID
        {
            get { return fCD_Address_ID; }
            set { SetPropertyValue<Guid>(nameof(CD_Address_ID), ref fCD_Address_ID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fAddress;
        [Size(50)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fOverflow;
        [Size(50)]
        public string Overflow
        {
            get { return fOverflow; }
            set { SetPropertyValue<string>(nameof(Overflow), ref fOverflow, value); }
        }
        string fCity;
        [Size(50)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fState;
        [Size(2)]
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>(nameof(State), ref fState, value); }
        }
        pl_Country fCountry;
        [Association(@"CD_AddressReferencespl_Country")]
        public pl_Country Country
        {
            get { return fCountry; }
            set { SetPropertyValue<pl_Country>(nameof(Country), ref fCountry, value); }
        }
    }

}
