//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class CD_Contacts : XPLiteObject
    {
        Guid fCD_Contacts_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid CD_Contacts_ID
        {
            get { return fCD_Contacts_ID; }
            set { SetPropertyValue<Guid>(nameof(CD_Contacts_ID), ref fCD_Contacts_ID, value); }
        }
        CD_Main fCD_Main_ID;
        [Association(@"CD_ContactsReferencesCD_Main")]
        public CD_Main CD_Main_ID
        {
            get { return fCD_Main_ID; }
            set { SetPropertyValue<CD_Main>(nameof(CD_Main_ID), ref fCD_Main_ID, value); }
        }
        string fContact;
        [Size(50)]
        public string Contact
        {
            get { return fContact; }
            set { SetPropertyValue<string>(nameof(Contact), ref fContact, value); }
        }
        bool fUSMail;
        public bool USMail
        {
            get { return fUSMail; }
            set { SetPropertyValue<bool>(nameof(USMail), ref fUSMail, value); }
        }
        bool fEMail;
        public bool EMail
        {
            get { return fEMail; }
            set { SetPropertyValue<bool>(nameof(EMail), ref fEMail, value); }
        }
        string fEmail_Address;
        public string Email_Address
        {
            get { return fEmail_Address; }
            set { SetPropertyValue<string>(nameof(Email_Address), ref fEmail_Address, value); }
        }
        bool fFax;
        public bool Fax
        {
            get { return fFax; }
            set { SetPropertyValue<bool>(nameof(Fax), ref fFax, value); }
        }
        string fFax_Number;
        [Size(25)]
        public string Fax_Number
        {
            get { return fFax_Number; }
            set { SetPropertyValue<string>(nameof(Fax_Number), ref fFax_Number, value); }
        }
        bool fPhone;
        public bool Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<bool>(nameof(Phone), ref fPhone, value); }
        }
        string fPhone_Number;
        [Size(25)]
        public string Phone_Number
        {
            get { return fPhone_Number; }
            set { SetPropertyValue<string>(nameof(Phone_Number), ref fPhone_Number, value); }
        }
        string fPhone_Extension;
        [Size(10)]
        public string Phone_Extension
        {
            get { return fPhone_Extension; }
            set { SetPropertyValue<string>(nameof(Phone_Extension), ref fPhone_Extension, value); }
        }
    }

}
