//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class CG_List : XPLiteObject
    {
        Guid fCG_List_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid CG_List_ID
        {
            get { return fCG_List_ID; }
            set { SetPropertyValue<Guid>(nameof(CG_List_ID), ref fCG_List_ID, value); }
        }
        Guid fParent_ID;
        public Guid Parent_ID
        {
            get { return fParent_ID; }
            set { SetPropertyValue<Guid>(nameof(Parent_ID), ref fParent_ID, value); }
        }
        Guid fChild_ID;
        public Guid Child_ID
        {
            get { return fChild_ID; }
            set { SetPropertyValue<Guid>(nameof(Child_ID), ref fChild_ID, value); }
        }
        string fDescription;
        [Size(60)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
    }

}
