//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class CM_History_Credit : XPLiteObject
    {
        Guid fCM_History_Credit_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid CM_History_Credit_ID
        {
            get { return fCM_History_Credit_ID; }
            set { SetPropertyValue<Guid>(nameof(CM_History_Credit_ID), ref fCM_History_Credit_ID, value); }
        }
        Guid fCM_Main_ID;
        public Guid CM_Main_ID
        {
            get { return fCM_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(CM_Main_ID), ref fCM_Main_ID, value); }
        }
        DateTime fCreated_Date_Time;
        public DateTime Created_Date_Time
        {
            get { return fCreated_Date_Time; }
            set { SetPropertyValue<DateTime>(nameof(Created_Date_Time), ref fCreated_Date_Time, value); }
        }
        int fYear;
        public int Year
        {
            get { return fYear; }
            set { SetPropertyValue<int>(nameof(Year), ref fYear, value); }
        }
        decimal fBalance;
        public decimal Balance
        {
            get { return fBalance; }
            set { SetPropertyValue<decimal>(nameof(Balance), ref fBalance, value); }
        }
        decimal fFinance_Charge_Balance;
        public decimal Finance_Charge_Balance
        {
            get { return fFinance_Charge_Balance; }
            set { SetPropertyValue<decimal>(nameof(Finance_Charge_Balance), ref fFinance_Charge_Balance, value); }
        }
        decimal fUnbilled_Balance;
        public decimal Unbilled_Balance
        {
            get { return fUnbilled_Balance; }
            set { SetPropertyValue<decimal>(nameof(Unbilled_Balance), ref fUnbilled_Balance, value); }
        }
        decimal fUnapplied_Cash;
        public decimal Unapplied_Cash
        {
            get { return fUnapplied_Cash; }
            set { SetPropertyValue<decimal>(nameof(Unapplied_Cash), ref fUnapplied_Cash, value); }
        }
        decimal fFuture_Balance_Due;
        public decimal Future_Balance_Due
        {
            get { return fFuture_Balance_Due; }
            set { SetPropertyValue<decimal>(nameof(Future_Balance_Due), ref fFuture_Balance_Due, value); }
        }
        decimal fPast_Due;
        public decimal Past_Due
        {
            get { return fPast_Due; }
            set { SetPropertyValue<decimal>(nameof(Past_Due), ref fPast_Due, value); }
        }
        decimal fPast_Due_0_30_Days;
        public decimal Past_Due_0_30_Days
        {
            get { return fPast_Due_0_30_Days; }
            set { SetPropertyValue<decimal>(nameof(Past_Due_0_30_Days), ref fPast_Due_0_30_Days, value); }
        }
        decimal fPast_Due_31_60_Days;
        public decimal Past_Due_31_60_Days
        {
            get { return fPast_Due_31_60_Days; }
            set { SetPropertyValue<decimal>(nameof(Past_Due_31_60_Days), ref fPast_Due_31_60_Days, value); }
        }
        decimal fPast_Due_61_90_Days;
        public decimal Past_Due_61_90_Days
        {
            get { return fPast_Due_61_90_Days; }
            set { SetPropertyValue<decimal>(nameof(Past_Due_61_90_Days), ref fPast_Due_61_90_Days, value); }
        }
        decimal fPast_Due_91_120_Days;
        public decimal Past_Due_91_120_Days
        {
            get { return fPast_Due_91_120_Days; }
            set { SetPropertyValue<decimal>(nameof(Past_Due_91_120_Days), ref fPast_Due_91_120_Days, value); }
        }
        decimal fPast_Due_121_UP_Days;
        public decimal Past_Due_121_UP_Days
        {
            get { return fPast_Due_121_UP_Days; }
            set { SetPropertyValue<decimal>(nameof(Past_Due_121_UP_Days), ref fPast_Due_121_UP_Days, value); }
        }
        int fPaid_Past_Due_0_30_Days;
        public int Paid_Past_Due_0_30_Days
        {
            get { return fPaid_Past_Due_0_30_Days; }
            set { SetPropertyValue<int>(nameof(Paid_Past_Due_0_30_Days), ref fPaid_Past_Due_0_30_Days, value); }
        }
        int fPaid_Past_Due_31_60_Days;
        public int Paid_Past_Due_31_60_Days
        {
            get { return fPaid_Past_Due_31_60_Days; }
            set { SetPropertyValue<int>(nameof(Paid_Past_Due_31_60_Days), ref fPaid_Past_Due_31_60_Days, value); }
        }
        int fPaid_Past_Due_61_90_Days;
        public int Paid_Past_Due_61_90_Days
        {
            get { return fPaid_Past_Due_61_90_Days; }
            set { SetPropertyValue<int>(nameof(Paid_Past_Due_61_90_Days), ref fPaid_Past_Due_61_90_Days, value); }
        }
        int fPaid_Past_Due_91_120_Days;
        public int Paid_Past_Due_91_120_Days
        {
            get { return fPaid_Past_Due_91_120_Days; }
            set { SetPropertyValue<int>(nameof(Paid_Past_Due_91_120_Days), ref fPaid_Past_Due_91_120_Days, value); }
        }
        int fPaid_Past_Due_121_UP_Days;
        public int Paid_Past_Due_121_UP_Days
        {
            get { return fPaid_Past_Due_121_UP_Days; }
            set { SetPropertyValue<int>(nameof(Paid_Past_Due_121_UP_Days), ref fPaid_Past_Due_121_UP_Days, value); }
        }
        int fLast_Invoice_Date;
        public int Last_Invoice_Date
        {
            get { return fLast_Invoice_Date; }
            set { SetPropertyValue<int>(nameof(Last_Invoice_Date), ref fLast_Invoice_Date, value); }
        }
        decimal fLast_Invoice_Number;
        public decimal Last_Invoice_Number
        {
            get { return fLast_Invoice_Number; }
            set { SetPropertyValue<decimal>(nameof(Last_Invoice_Number), ref fLast_Invoice_Number, value); }
        }
        decimal fLast_Invoice_Amount;
        public decimal Last_Invoice_Amount
        {
            get { return fLast_Invoice_Amount; }
            set { SetPropertyValue<decimal>(nameof(Last_Invoice_Amount), ref fLast_Invoice_Amount, value); }
        }
        int fLast_Pay_Date;
        public int Last_Pay_Date
        {
            get { return fLast_Pay_Date; }
            set { SetPropertyValue<int>(nameof(Last_Pay_Date), ref fLast_Pay_Date, value); }
        }
        int fLast_Pay_Number;
        public int Last_Pay_Number
        {
            get { return fLast_Pay_Number; }
            set { SetPropertyValue<int>(nameof(Last_Pay_Number), ref fLast_Pay_Number, value); }
        }
        decimal fLast_Pay_Amount;
        public decimal Last_Pay_Amount
        {
            get { return fLast_Pay_Amount; }
            set { SetPropertyValue<decimal>(nameof(Last_Pay_Amount), ref fLast_Pay_Amount, value); }
        }
        Guid fMax_Credit_TM;
        public Guid Max_Credit_TM
        {
            get { return fMax_Credit_TM; }
            set { SetPropertyValue<Guid>(nameof(Max_Credit_TM), ref fMax_Credit_TM, value); }
        }
        Guid fMax_Credit_TY;
        public Guid Max_Credit_TY
        {
            get { return fMax_Credit_TY; }
            set { SetPropertyValue<Guid>(nameof(Max_Credit_TY), ref fMax_Credit_TY, value); }
        }
    }

}
