//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class CM_Options : XPLiteObject
    {
        Guid fCM_Options_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid CM_Options_ID
        {
            get { return fCM_Options_ID; }
            set { SetPropertyValue<Guid>(nameof(CM_Options_ID), ref fCM_Options_ID, value); }
        }
        CM_Main fCM_Main_ID;
        [Association(@"CM_OptionsReferencesCM_Main")]
        public CM_Main CM_Main_ID
        {
            get { return fCM_Main_ID; }
            set { SetPropertyValue<CM_Main>(nameof(CM_Main_ID), ref fCM_Main_ID, value); }
        }
        TD_Main fTD_Main_ID;
        [Association(@"CM_OptionsReferencesTD_Main")]
        public TD_Main TD_Main_ID
        {
            get { return fTD_Main_ID; }
            set { SetPropertyValue<TD_Main>(nameof(TD_Main_ID), ref fTD_Main_ID, value); }
        }
        string fTax_Number;
        [Size(20)]
        public string Tax_Number
        {
            get { return fTax_Number; }
            set { SetPropertyValue<string>(nameof(Tax_Number), ref fTax_Number, value); }
        }
        pl_Tax_Number_Type fTax_Number_Type;
        [Association(@"CM_OptionsReferencespl_Tax_Number_Type")]
        public pl_Tax_Number_Type Tax_Number_Type
        {
            get { return fTax_Number_Type; }
            set { SetPropertyValue<pl_Tax_Number_Type>(nameof(Tax_Number_Type), ref fTax_Number_Type, value); }
        }
        pl_Ship_Via fShip_Via;
        [Association(@"CM_OptionsReferencespl_Ship_Via")]
        public pl_Ship_Via Ship_Via
        {
            get { return fShip_Via; }
            set { SetPropertyValue<pl_Ship_Via>(nameof(Ship_Via), ref fShip_Via, value); }
        }
        int fDiscount;
        public int Discount
        {
            get { return fDiscount; }
            set { SetPropertyValue<int>(nameof(Discount), ref fDiscount, value); }
        }
        pl_Discount_Type fDiscount_Percent;
        [Association(@"CM_OptionsReferencespl_Discount_Type")]
        public pl_Discount_Type Discount_Percent
        {
            get { return fDiscount_Percent; }
            set { SetPropertyValue<pl_Discount_Type>(nameof(Discount_Percent), ref fDiscount_Percent, value); }
        }
        bool fAllow_Dating;
        public bool Allow_Dating
        {
            get { return fAllow_Dating; }
            set { SetPropertyValue<bool>(nameof(Allow_Dating), ref fAllow_Dating, value); }
        }
        bool fOrder_Acknowledgement;
        public bool Order_Acknowledgement
        {
            get { return fOrder_Acknowledgement; }
            set { SetPropertyValue<bool>(nameof(Order_Acknowledgement), ref fOrder_Acknowledgement, value); }
        }
        bool fNo_Partial_Ship;
        public bool No_Partial_Ship
        {
            get { return fNo_Partial_Ship; }
            set { SetPropertyValue<bool>(nameof(No_Partial_Ship), ref fNo_Partial_Ship, value); }
        }
        bool fAccept_Backorders;
        public bool Accept_Backorders
        {
            get { return fAccept_Backorders; }
            set { SetPropertyValue<bool>(nameof(Accept_Backorders), ref fAccept_Backorders, value); }
        }
        bool fMailing_Labels;
        [Indexed(Name = @"CM_Options_Mailing_Labels_Do_Not_Ship")]
        public bool Mailing_Labels
        {
            get { return fMailing_Labels; }
            set { SetPropertyValue<bool>(nameof(Mailing_Labels), ref fMailing_Labels, value); }
        }
        bool fStatements;
        public bool Statements
        {
            get { return fStatements; }
            set { SetPropertyValue<bool>(nameof(Statements), ref fStatements, value); }
        }
        bool fFinance_Charge;
        public bool Finance_Charge
        {
            get { return fFinance_Charge; }
            set { SetPropertyValue<bool>(nameof(Finance_Charge), ref fFinance_Charge, value); }
        }
        bool fAuto_OE_Minimums;
        public bool Auto_OE_Minimums
        {
            get { return fAuto_OE_Minimums; }
            set { SetPropertyValue<bool>(nameof(Auto_OE_Minimums), ref fAuto_OE_Minimums, value); }
        }
        int fUse_Price_Set;
        public int Use_Price_Set
        {
            get { return fUse_Price_Set; }
            set { SetPropertyValue<int>(nameof(Use_Price_Set), ref fUse_Price_Set, value); }
        }
        bool fCall_Before_Shipping;
        public bool Call_Before_Shipping
        {
            get { return fCall_Before_Shipping; }
            set { SetPropertyValue<bool>(nameof(Call_Before_Shipping), ref fCall_Before_Shipping, value); }
        }
        bool fCall_Before_Delivery;
        public bool Call_Before_Delivery
        {
            get { return fCall_Before_Delivery; }
            set { SetPropertyValue<bool>(nameof(Call_Before_Delivery), ref fCall_Before_Delivery, value); }
        }
        bool fCall_Before_Shipping_BOs;
        public bool Call_Before_Shipping_BOs
        {
            get { return fCall_Before_Shipping_BOs; }
            set { SetPropertyValue<bool>(nameof(Call_Before_Shipping_BOs), ref fCall_Before_Shipping_BOs, value); }
        }
        int fNo_Statement_Limit;
        public int No_Statement_Limit
        {
            get { return fNo_Statement_Limit; }
            set { SetPropertyValue<int>(nameof(No_Statement_Limit), ref fNo_Statement_Limit, value); }
        }
        bool fPickup_Orders_Only;
        public bool Pickup_Orders_Only
        {
            get { return fPickup_Orders_Only; }
            set { SetPropertyValue<bool>(nameof(Pickup_Orders_Only), ref fPickup_Orders_Only, value); }
        }
        Guid fHold_Reason;
        public Guid Hold_Reason
        {
            get { return fHold_Reason; }
            set { SetPropertyValue<Guid>(nameof(Hold_Reason), ref fHold_Reason, value); }
        }
        bool fHold_Flag;
        public bool Hold_Flag
        {
            get { return fHold_Flag; }
            set { SetPropertyValue<bool>(nameof(Hold_Flag), ref fHold_Flag, value); }
        }
        pl_Reason_for_Hold fHold_Placed_Reason_ID;
        [Association(@"CM_OptionsReferencespl_Reason_for_Hold")]
        public pl_Reason_for_Hold Hold_Placed_Reason_ID
        {
            get { return fHold_Placed_Reason_ID; }
            set { SetPropertyValue<pl_Reason_for_Hold>(nameof(Hold_Placed_Reason_ID), ref fHold_Placed_Reason_ID, value); }
        }
        UD_Main fHold_Placed_User_ID;
        [Association(@"CM_OptionsReferencesUD_Main3")]
        public UD_Main Hold_Placed_User_ID
        {
            get { return fHold_Placed_User_ID; }
            set { SetPropertyValue<UD_Main>(nameof(Hold_Placed_User_ID), ref fHold_Placed_User_ID, value); }
        }
        DateTime fHold_Placed_DateTime;
        public DateTime Hold_Placed_DateTime
        {
            get { return fHold_Placed_DateTime; }
            set { SetPropertyValue<DateTime>(nameof(Hold_Placed_DateTime), ref fHold_Placed_DateTime, value); }
        }
        pl_Reason_for_Hold fHold_Removed_Reason_ID;
        [Association(@"CM_OptionsReferencespl_Reason_for_Hold1")]
        public pl_Reason_for_Hold Hold_Removed_Reason_ID
        {
            get { return fHold_Removed_Reason_ID; }
            set { SetPropertyValue<pl_Reason_for_Hold>(nameof(Hold_Removed_Reason_ID), ref fHold_Removed_Reason_ID, value); }
        }
        UD_Main fHold_Removed_User_ID;
        [Association(@"CM_OptionsReferencesUD_Main4")]
        public UD_Main Hold_Removed_User_ID
        {
            get { return fHold_Removed_User_ID; }
            set { SetPropertyValue<UD_Main>(nameof(Hold_Removed_User_ID), ref fHold_Removed_User_ID, value); }
        }
        DateTime fHold_Removed_DateTime;
        public DateTime Hold_Removed_DateTime
        {
            get { return fHold_Removed_DateTime; }
            set { SetPropertyValue<DateTime>(nameof(Hold_Removed_DateTime), ref fHold_Removed_DateTime, value); }
        }
        bool fSeasonal_Summer;
        public bool Seasonal_Summer
        {
            get { return fSeasonal_Summer; }
            set { SetPropertyValue<bool>(nameof(Seasonal_Summer), ref fSeasonal_Summer, value); }
        }
        DateTime fSeasonal_Summer_Date;
        public DateTime Seasonal_Summer_Date
        {
            get { return fSeasonal_Summer_Date; }
            set { SetPropertyValue<DateTime>(nameof(Seasonal_Summer_Date), ref fSeasonal_Summer_Date, value); }
        }
        bool fSeasonal_Winter;
        public bool Seasonal_Winter
        {
            get { return fSeasonal_Winter; }
            set { SetPropertyValue<bool>(nameof(Seasonal_Winter), ref fSeasonal_Winter, value); }
        }
        DateTime fSeasonal_Winter_Date;
        public DateTime Seasonal_Winter_Date
        {
            get { return fSeasonal_Winter_Date; }
            set { SetPropertyValue<DateTime>(nameof(Seasonal_Winter_Date), ref fSeasonal_Winter_Date, value); }
        }
        bool fCredit_Pending;
        public bool Credit_Pending
        {
            get { return fCredit_Pending; }
            set { SetPropertyValue<bool>(nameof(Credit_Pending), ref fCredit_Pending, value); }
        }
        bool fBad_Check;
        public bool Bad_Check
        {
            get { return fBad_Check; }
            set { SetPropertyValue<bool>(nameof(Bad_Check), ref fBad_Check, value); }
        }
        bool fSlow_Pay;
        public bool Slow_Pay
        {
            get { return fSlow_Pay; }
            set { SetPropertyValue<bool>(nameof(Slow_Pay), ref fSlow_Pay, value); }
        }
        bool fRefused_Shipment;
        public bool Refused_Shipment
        {
            get { return fRefused_Shipment; }
            set { SetPropertyValue<bool>(nameof(Refused_Shipment), ref fRefused_Shipment, value); }
        }
        bool fDo_Not_Ship;
        public bool Do_Not_Ship
        {
            get { return fDo_Not_Ship; }
            set { SetPropertyValue<bool>(nameof(Do_Not_Ship), ref fDo_Not_Ship, value); }
        }
        UD_Main fUD_Main_ID;
        [Association(@"CM_OptionsReferencesUD_Main")]
        public UD_Main UD_Main_ID
        {
            get { return fUD_Main_ID; }
            set { SetPropertyValue<UD_Main>(nameof(UD_Main_ID), ref fUD_Main_ID, value); }
        }
        bool fCollection;
        public bool Collection
        {
            get { return fCollection; }
            set { SetPropertyValue<bool>(nameof(Collection), ref fCollection, value); }
        }
        bool fCredit_Watch;
        public bool Credit_Watch
        {
            get { return fCredit_Watch; }
            set { SetPropertyValue<bool>(nameof(Credit_Watch), ref fCredit_Watch, value); }
        }
        pl_Credit_Status fCredit_Status_ID;
        [Association(@"CM_OptionsReferencespl_Credit_Status")]
        public pl_Credit_Status Credit_Status_ID
        {
            get { return fCredit_Status_ID; }
            set { SetPropertyValue<pl_Credit_Status>(nameof(Credit_Status_ID), ref fCredit_Status_ID, value); }
        }
        DateTime fBad_Check_Date;
        public DateTime Bad_Check_Date
        {
            get { return fBad_Check_Date; }
            set { SetPropertyValue<DateTime>(nameof(Bad_Check_Date), ref fBad_Check_Date, value); }
        }
        DateTime fRefused_Shipment_Date;
        public DateTime Refused_Shipment_Date
        {
            get { return fRefused_Shipment_Date; }
            set { SetPropertyValue<DateTime>(nameof(Refused_Shipment_Date), ref fRefused_Shipment_Date, value); }
        }
        DateTime fDo_Not_Ship_Date;
        public DateTime Do_Not_Ship_Date
        {
            get { return fDo_Not_Ship_Date; }
            set { SetPropertyValue<DateTime>(nameof(Do_Not_Ship_Date), ref fDo_Not_Ship_Date, value); }
        }
        DateTime fCollection_Date;
        public DateTime Collection_Date
        {
            get { return fCollection_Date; }
            set { SetPropertyValue<DateTime>(nameof(Collection_Date), ref fCollection_Date, value); }
        }
        int fCredit_Limit;
        public int Credit_Limit
        {
            get { return fCredit_Limit; }
            set { SetPropertyValue<int>(nameof(Credit_Limit), ref fCredit_Limit, value); }
        }
        bool fSystem_Account;
        public bool System_Account
        {
            get { return fSystem_Account; }
            set { SetPropertyValue<bool>(nameof(System_Account), ref fSystem_Account, value); }
        }
        string fatest;
        [Size(50)]
        public string atest
        {
            get { return fatest; }
            set { SetPropertyValue<string>(nameof(atest), ref fatest, value); }
        }
        string fHold_Comment;
        [Size(1024)]
        public string Hold_Comment
        {
            get { return fHold_Comment; }
            set { SetPropertyValue<string>(nameof(Hold_Comment), ref fHold_Comment, value); }
        }
        DateTime fDo_Not_Ship_Date_Added;
        public DateTime Do_Not_Ship_Date_Added
        {
            get { return fDo_Not_Ship_Date_Added; }
            set { SetPropertyValue<DateTime>(nameof(Do_Not_Ship_Date_Added), ref fDo_Not_Ship_Date_Added, value); }
        }
        DateTime fDo_Not_Ship_Date_Removed;
        public DateTime Do_Not_Ship_Date_Removed
        {
            get { return fDo_Not_Ship_Date_Removed; }
            set { SetPropertyValue<DateTime>(nameof(Do_Not_Ship_Date_Removed), ref fDo_Not_Ship_Date_Removed, value); }
        }
        UD_Main fDo_Not_Ship_Add_UD_Main_ID;
        [Association(@"CM_OptionsReferencesUD_Main1")]
        public UD_Main Do_Not_Ship_Add_UD_Main_ID
        {
            get { return fDo_Not_Ship_Add_UD_Main_ID; }
            set { SetPropertyValue<UD_Main>(nameof(Do_Not_Ship_Add_UD_Main_ID), ref fDo_Not_Ship_Add_UD_Main_ID, value); }
        }
        UD_Main fDo_Not_Ship_Remove_UD_Main_ID;
        [Association(@"CM_OptionsReferencesUD_Main2")]
        public UD_Main Do_Not_Ship_Remove_UD_Main_ID
        {
            get { return fDo_Not_Ship_Remove_UD_Main_ID; }
            set { SetPropertyValue<UD_Main>(nameof(Do_Not_Ship_Remove_UD_Main_ID), ref fDo_Not_Ship_Remove_UD_Main_ID, value); }
        }
        bool fHold_Flag_Check;
        public bool Hold_Flag_Check
        {
            get { return fHold_Flag_Check; }
            set { SetPropertyValue<bool>(nameof(Hold_Flag_Check), ref fHold_Flag_Check, value); }
        }
        int fHold_Place_Valid;
        public int Hold_Place_Valid
        {
            get { return fHold_Place_Valid; }
            set { SetPropertyValue<int>(nameof(Hold_Place_Valid), ref fHold_Place_Valid, value); }
        }
    }

}
