//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class CM_Xref : XPLiteObject
    {
        Guid fCM_Xref_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid CM_Xref_ID
        {
            get { return fCM_Xref_ID; }
            set { SetPropertyValue<Guid>(nameof(CM_Xref_ID), ref fCM_Xref_ID, value); }
        }
        CM_Main fCM_Main_ID;
        [Association(@"CM_XrefReferencesCM_Main")]
        public CM_Main CM_Main_ID
        {
            get { return fCM_Main_ID; }
            set { SetPropertyValue<CM_Main>(nameof(CM_Main_ID), ref fCM_Main_ID, value); }
        }
        string fXref_Name;
        public string Xref_Name
        {
            get { return fXref_Name; }
            set { SetPropertyValue<string>(nameof(Xref_Name), ref fXref_Name, value); }
        }
    }

}
