//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class CS_Main : XPLiteObject
    {
        Guid fCS_Main_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid CS_Main_ID
        {
            get { return fCS_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(CS_Main_ID), ref fCS_Main_ID, value); }
        }
        string fCS_Main_Text_Link;
        [Size(10)]
        public string CS_Main_Text_Link
        {
            get { return fCS_Main_Text_Link; }
            set { SetPropertyValue<string>(nameof(CS_Main_Text_Link), ref fCS_Main_Text_Link, value); }
        }
        string fGroup_Type;
        [Size(10)]
        public string Group_Type
        {
            get { return fGroup_Type; }
            set { SetPropertyValue<string>(nameof(Group_Type), ref fGroup_Type, value); }
        }
        string fStatistics_Description;
        [Size(50)]
        public string Statistics_Description
        {
            get { return fStatistics_Description; }
            set { SetPropertyValue<string>(nameof(Statistics_Description), ref fStatistics_Description, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        decimal fPrimary_Sort;
        public decimal Primary_Sort
        {
            get { return fPrimary_Sort; }
            set { SetPropertyValue<decimal>(nameof(Primary_Sort), ref fPrimary_Sort, value); }
        }
        decimal fSecondary_Sort;
        public decimal Secondary_Sort
        {
            get { return fSecondary_Sort; }
            set { SetPropertyValue<decimal>(nameof(Secondary_Sort), ref fSecondary_Sort, value); }
        }
        string fAN_Alpha;
        [Size(10)]
        public string AN_Alpha
        {
            get { return fAN_Alpha; }
            set { SetPropertyValue<string>(nameof(AN_Alpha), ref fAN_Alpha, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
    }

}
