//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class DL_Order_Log : XPLiteObject
    {
        Guid fDL_Order_Log_ID;
        [Key(true)]
        public Guid DL_Order_Log_ID
        {
            get { return fDL_Order_Log_ID; }
            set { SetPropertyValue<Guid>(nameof(DL_Order_Log_ID), ref fDL_Order_Log_ID, value); }
        }
        DateTime fDown_Load_DateTime;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime Down_Load_DateTime
        {
            get { return fDown_Load_DateTime; }
            set { SetPropertyValue<DateTime>(nameof(Down_Load_DateTime), ref fDown_Load_DateTime, value); }
        }
        int fOrders_Processed;
        public int Orders_Processed
        {
            get { return fOrders_Processed; }
            set { SetPropertyValue<int>(nameof(Orders_Processed), ref fOrders_Processed, value); }
        }
        int fError_Code;
        public int Error_Code
        {
            get { return fError_Code; }
            set { SetPropertyValue<int>(nameof(Error_Code), ref fError_Code, value); }
        }
        string fError_Result_Text;
        [Size(512)]
        public string Error_Result_Text
        {
            get { return fError_Result_Text; }
            set { SetPropertyValue<string>(nameof(Error_Result_Text), ref fError_Result_Text, value); }
        }
        long fBatch_Number_ID;
        public long Batch_Number_ID
        {
            get { return fBatch_Number_ID; }
            set { SetPropertyValue<long>(nameof(Batch_Number_ID), ref fBatch_Number_ID, value); }
        }
        string fFile_Mark;
        [Size(20)]
        public string File_Mark
        {
            get { return fFile_Mark; }
            set { SetPropertyValue<string>(nameof(File_Mark), ref fFile_Mark, value); }
        }
        int fOrders_To_Process;
        public int Orders_To_Process
        {
            get { return fOrders_To_Process; }
            set { SetPropertyValue<int>(nameof(Orders_To_Process), ref fOrders_To_Process, value); }
        }
        int fOrders_To_New_Pending;
        public int Orders_To_New_Pending
        {
            get { return fOrders_To_New_Pending; }
            set { SetPropertyValue<int>(nameof(Orders_To_New_Pending), ref fOrders_To_New_Pending, value); }
        }
        [Association(@"DL_Order_SummaryReferencesDL_Order_Log")]
        public XPCollection<DL_Order_Summary> DL_Order_Summarys { get { return GetCollection<DL_Order_Summary>(nameof(DL_Order_Summarys)); } }
    }

}
