//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IC_Inventory_Item_Audit : XPLiteObject
    {
        Guid fItemAuditGuid;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid ItemAuditGuid
        {
            get { return fItemAuditGuid; }
            set { SetPropertyValue<Guid>(nameof(ItemAuditGuid), ref fItemAuditGuid, value); }
        }
        IM_Main fIM_Main_ID;
        [Association(@"IC_Inventory_Item_AuditReferencesIM_Main")]
        public IM_Main IM_Main_ID
        {
            get { return fIM_Main_ID; }
            set { SetPropertyValue<IM_Main>(nameof(IM_Main_ID), ref fIM_Main_ID, value); }
        }
        string fItem_Number_Main;
        [Size(25)]
        public string Item_Number_Main
        {
            get { return fItem_Number_Main; }
            set { SetPropertyValue<string>(nameof(Item_Number_Main), ref fItem_Number_Main, value); }
        }
        string fUPC;
        [Size(12)]
        public string UPC
        {
            get { return fUPC; }
            set { SetPropertyValue<string>(nameof(UPC), ref fUPC, value); }
        }
        string fDescription;
        [Size(40)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fDefault_BL;
        public int Default_BL
        {
            get { return fDefault_BL; }
            set { SetPropertyValue<int>(nameof(Default_BL), ref fDefault_BL, value); }
        }
        pl_Unit fDefault_Unit_ID;
        [Association(@"IC_Inventory_Item_AuditReferencespl_Unit")]
        public pl_Unit Default_Unit_ID
        {
            get { return fDefault_Unit_ID; }
            set { SetPropertyValue<pl_Unit>(nameof(Default_Unit_ID), ref fDefault_Unit_ID, value); }
        }
        int fDefault_Unit;
        public int Default_Unit
        {
            get { return fDefault_Unit; }
            set { SetPropertyValue<int>(nameof(Default_Unit), ref fDefault_Unit, value); }
        }
        pl_Unit fCase_Unit_ID;
        [Association(@"IC_Inventory_Item_AuditReferencespl_Unit1")]
        public pl_Unit Case_Unit_ID
        {
            get { return fCase_Unit_ID; }
            set { SetPropertyValue<pl_Unit>(nameof(Case_Unit_ID), ref fCase_Unit_ID, value); }
        }
        int fCase_Unit;
        public int Case_Unit
        {
            get { return fCase_Unit; }
            set { SetPropertyValue<int>(nameof(Case_Unit), ref fCase_Unit, value); }
        }
        int fCase_QTY_BL;
        public int Case_QTY_BL
        {
            get { return fCase_QTY_BL; }
            set { SetPropertyValue<int>(nameof(Case_QTY_BL), ref fCase_QTY_BL, value); }
        }
        int fCase_QTY;
        public int Case_QTY
        {
            get { return fCase_QTY; }
            set { SetPropertyValue<int>(nameof(Case_QTY), ref fCase_QTY, value); }
        }
        int fQuantity;
        public int Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<int>(nameof(Quantity), ref fQuantity, value); }
        }
        string fArea;
        [Size(50)]
        public string Area
        {
            get { return fArea; }
            set { SetPropertyValue<string>(nameof(Area), ref fArea, value); }
        }
        string fRow;
        [Size(50)]
        public string Row
        {
            get { return fRow; }
            set { SetPropertyValue<string>(nameof(Row), ref fRow, value); }
        }
        string fPallet;
        [Size(50)]
        public string Pallet
        {
            get { return fPallet; }
            set { SetPropertyValue<string>(nameof(Pallet), ref fPallet, value); }
        }
        string fOther;
        [Size(50)]
        public string Other
        {
            get { return fOther; }
            set { SetPropertyValue<string>(nameof(Other), ref fOther, value); }
        }
        string fDevice_ID;
        [Size(25)]
        public string Device_ID
        {
            get { return fDevice_ID; }
            set { SetPropertyValue<string>(nameof(Device_ID), ref fDevice_ID, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        int fBaseCount;
        public int BaseCount
        {
            get { return fBaseCount; }
            set { SetPropertyValue<int>(nameof(BaseCount), ref fBaseCount, value); }
        }
        int fInventroy_Mode;
        public int Inventroy_Mode
        {
            get { return fInventroy_Mode; }
            set { SetPropertyValue<int>(nameof(Inventroy_Mode), ref fInventroy_Mode, value); }
        }
        bool fAccept_Count;
        public bool Accept_Count
        {
            get { return fAccept_Count; }
            set { SetPropertyValue<bool>(nameof(Accept_Count), ref fAccept_Count, value); }
        }
        DateTime fEntryDateTime;
        public DateTime EntryDateTime
        {
            get { return fEntryDateTime; }
            set { SetPropertyValue<DateTime>(nameof(EntryDateTime), ref fEntryDateTime, value); }
        }
        string fUserID;
        [Size(50)]
        public string UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<string>(nameof(UserID), ref fUserID, value); }
        }
        int fYear_Audit;
        [Indexed(@"IC_Inventory_Main_Audit_ID", Name = @"IX_IC_Inventory_Item_Audit_Year_Main_ID")]
        public int Year_Audit
        {
            get { return fYear_Audit; }
            set { SetPropertyValue<int>(nameof(Year_Audit), ref fYear_Audit, value); }
        }
        IC_Inventory_Main_Audit fIC_Inventory_Main_Audit_ID;
        [Association(@"IC_Inventory_Item_AuditReferencesIC_Inventory_Main_Audit")]
        public IC_Inventory_Main_Audit IC_Inventory_Main_Audit_ID
        {
            get { return fIC_Inventory_Main_Audit_ID; }
            set { SetPropertyValue<IC_Inventory_Main_Audit>(nameof(IC_Inventory_Main_Audit_ID), ref fIC_Inventory_Main_Audit_ID, value); }
        }
        int fYear_Audit_Link;
        public int Year_Audit_Link
        {
            get { return fYear_Audit_Link; }
            set { SetPropertyValue<int>(nameof(Year_Audit_Link), ref fYear_Audit_Link, value); }
        }
        int fQTY_Before_Inventory_Count;
        public int QTY_Before_Inventory_Count
        {
            get { return fQTY_Before_Inventory_Count; }
            set { SetPropertyValue<int>(nameof(QTY_Before_Inventory_Count), ref fQTY_Before_Inventory_Count, value); }
        }
        int fQTY_At_Inventory_Count;
        public int QTY_At_Inventory_Count
        {
            get { return fQTY_At_Inventory_Count; }
            set { SetPropertyValue<int>(nameof(QTY_At_Inventory_Count), ref fQTY_At_Inventory_Count, value); }
        }
        int fAccept_Count_Int;
        public int Accept_Count_Int
        {
            get { return fAccept_Count_Int; }
            set { SetPropertyValue<int>(nameof(Accept_Count_Int), ref fAccept_Count_Int, value); }
        }
        string fQuantity_Text;
        [Size(25)]
        public string Quantity_Text
        {
            get { return fQuantity_Text; }
            set { SetPropertyValue<string>(nameof(Quantity_Text), ref fQuantity_Text, value); }
        }
        string fLocation;
        [Size(203)]
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        string fLink_ID;
        [Size(30)]
        public string Link_ID
        {
            get { return fLink_ID; }
            set { SetPropertyValue<string>(nameof(Link_ID), ref fLink_ID, value); }
        }
        string flocal_Alpha;
        [Size(2)]
        public string local_Alpha
        {
            get { return flocal_Alpha; }
            set { SetPropertyValue<string>(nameof(local_Alpha), ref flocal_Alpha, value); }
        }
        Guid fLocation_Full_ID;
        public Guid Location_Full_ID
        {
            get { return fLocation_Full_ID; }
            set { SetPropertyValue<Guid>(nameof(Location_Full_ID), ref fLocation_Full_ID, value); }
        }
        int fRecord_Type;
        [ColumnDbDefaultValue("((1))")]
        public int Record_Type
        {
            get { return fRecord_Type; }
            set { SetPropertyValue<int>(nameof(Record_Type), ref fRecord_Type, value); }
        }
        string fPK;
        [Size(53)]
        public string PK
        {
            get { return fPK; }
            set { SetPropertyValue<string>(nameof(PK), ref fPK, value); }
        }
        string fLINK_PK;
        [Size(101)]
        public string LINK_PK
        {
            get { return fLINK_PK; }
            set { SetPropertyValue<string>(nameof(LINK_PK), ref fLINK_PK, value); }
        }
        string fmysort;
        [Size(10)]
        public string mysort
        {
            get { return fmysort; }
            set { SetPropertyValue<string>(nameof(mysort), ref fmysort, value); }
        }
    }

}
