//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IM_Categories : XPLiteObject
    {
        Guid fIM_Categories_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IM_Categories_ID
        {
            get { return fIM_Categories_ID; }
            set { SetPropertyValue<Guid>(nameof(IM_Categories_ID), ref fIM_Categories_ID, value); }
        }
        IM_Main fIM_Main_ID;
        [Association(@"IM_CategoriesReferencesIM_Main")]
        public IM_Main IM_Main_ID
        {
            get { return fIM_Main_ID; }
            set { SetPropertyValue<IM_Main>(nameof(IM_Main_ID), ref fIM_Main_ID, value); }
        }
        CG_Main fCG_Main_ID;
        [Association(@"IM_CategoriesReferencesCG_Main")]
        public CG_Main CG_Main_ID
        {
            get { return fCG_Main_ID; }
            set { SetPropertyValue<CG_Main>(nameof(CG_Main_ID), ref fCG_Main_ID, value); }
        }
    }

}
