//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IM_History_Credit_Data : XPLiteObject
    {
        Guid fIM_History_Credit_Data_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IM_History_Credit_Data_ID
        {
            get { return fIM_History_Credit_Data_ID; }
            set { SetPropertyValue<Guid>(nameof(IM_History_Credit_Data_ID), ref fIM_History_Credit_Data_ID, value); }
        }
        int fDatabase_Index;
        public int Database_Index
        {
            get { return fDatabase_Index; }
            set { SetPropertyValue<int>(nameof(Database_Index), ref fDatabase_Index, value); }
        }
        int fScheduled_Move_or_Delete;
        public int Scheduled_Move_or_Delete
        {
            get { return fScheduled_Move_or_Delete; }
            set { SetPropertyValue<int>(nameof(Scheduled_Move_or_Delete), ref fScheduled_Move_or_Delete, value); }
        }
        bool fRecord_Closed;
        public bool Record_Closed
        {
            get { return fRecord_Closed; }
            set { SetPropertyValue<bool>(nameof(Record_Closed), ref fRecord_Closed, value); }
        }
        IM_Main fItem_Number;
        [Association(@"IM_History_Credit_DataReferencesIM_Main")]
        public IM_Main Item_Number
        {
            get { return fItem_Number; }
            set { SetPropertyValue<IM_Main>(nameof(Item_Number), ref fItem_Number, value); }
        }
        int fYear_Invoiced;
        [Indexed(Name = @"YEAR_INVOICED")]
        public int Year_Invoiced
        {
            get { return fYear_Invoiced; }
            set { SetPropertyValue<int>(nameof(Year_Invoiced), ref fYear_Invoiced, value); }
        }
        int fQTY_Credit_01;
        public int QTY_Credit_01
        {
            get { return fQTY_Credit_01; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_01), ref fQTY_Credit_01, value); }
        }
        int fQTY_Credit_02;
        public int QTY_Credit_02
        {
            get { return fQTY_Credit_02; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_02), ref fQTY_Credit_02, value); }
        }
        int fQTY_Credit_03;
        public int QTY_Credit_03
        {
            get { return fQTY_Credit_03; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_03), ref fQTY_Credit_03, value); }
        }
        int fQTY_Credit_04;
        public int QTY_Credit_04
        {
            get { return fQTY_Credit_04; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_04), ref fQTY_Credit_04, value); }
        }
        int fQTY_Credit_05;
        public int QTY_Credit_05
        {
            get { return fQTY_Credit_05; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_05), ref fQTY_Credit_05, value); }
        }
        int fQTY_Credit_06;
        public int QTY_Credit_06
        {
            get { return fQTY_Credit_06; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_06), ref fQTY_Credit_06, value); }
        }
        int fQTY_Credit_07;
        public int QTY_Credit_07
        {
            get { return fQTY_Credit_07; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_07), ref fQTY_Credit_07, value); }
        }
        int fQTY_Credit_08;
        public int QTY_Credit_08
        {
            get { return fQTY_Credit_08; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_08), ref fQTY_Credit_08, value); }
        }
        int fQTY_Credit_09;
        public int QTY_Credit_09
        {
            get { return fQTY_Credit_09; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_09), ref fQTY_Credit_09, value); }
        }
        int fQTY_Credit_10;
        public int QTY_Credit_10
        {
            get { return fQTY_Credit_10; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_10), ref fQTY_Credit_10, value); }
        }
        int fQTY_Credit_11;
        public int QTY_Credit_11
        {
            get { return fQTY_Credit_11; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_11), ref fQTY_Credit_11, value); }
        }
        int fQTY_Credit_12;
        public int QTY_Credit_12
        {
            get { return fQTY_Credit_12; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_12), ref fQTY_Credit_12, value); }
        }
        int fQTY_Credit_YTD;
        public int QTY_Credit_YTD
        {
            get { return fQTY_Credit_YTD; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_YTD), ref fQTY_Credit_YTD, value); }
        }
        decimal fDollar_Credit_01;
        public decimal Dollar_Credit_01
        {
            get { return fDollar_Credit_01; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_01), ref fDollar_Credit_01, value); }
        }
        decimal fDollar_Credit_02;
        public decimal Dollar_Credit_02
        {
            get { return fDollar_Credit_02; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_02), ref fDollar_Credit_02, value); }
        }
        decimal fDollar_Credit_03;
        public decimal Dollar_Credit_03
        {
            get { return fDollar_Credit_03; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_03), ref fDollar_Credit_03, value); }
        }
        decimal fDollar_Credit_04;
        public decimal Dollar_Credit_04
        {
            get { return fDollar_Credit_04; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_04), ref fDollar_Credit_04, value); }
        }
        decimal fDollar_Credit_05;
        public decimal Dollar_Credit_05
        {
            get { return fDollar_Credit_05; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_05), ref fDollar_Credit_05, value); }
        }
        decimal fDollar_Credit_06;
        public decimal Dollar_Credit_06
        {
            get { return fDollar_Credit_06; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_06), ref fDollar_Credit_06, value); }
        }
        decimal fDollar_Credit_07;
        public decimal Dollar_Credit_07
        {
            get { return fDollar_Credit_07; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_07), ref fDollar_Credit_07, value); }
        }
        decimal fDollar_Credit_08;
        public decimal Dollar_Credit_08
        {
            get { return fDollar_Credit_08; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_08), ref fDollar_Credit_08, value); }
        }
        decimal fDollar_Credit_09;
        public decimal Dollar_Credit_09
        {
            get { return fDollar_Credit_09; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_09), ref fDollar_Credit_09, value); }
        }
        decimal fDollar_Credit_10;
        public decimal Dollar_Credit_10
        {
            get { return fDollar_Credit_10; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_10), ref fDollar_Credit_10, value); }
        }
        decimal fDollar_Credit_11;
        public decimal Dollar_Credit_11
        {
            get { return fDollar_Credit_11; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_11), ref fDollar_Credit_11, value); }
        }
        decimal fDollar_Credit_12;
        public decimal Dollar_Credit_12
        {
            get { return fDollar_Credit_12; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_12), ref fDollar_Credit_12, value); }
        }
        decimal fDollar_Credit_YTD;
        public decimal Dollar_Credit_YTD
        {
            get { return fDollar_Credit_YTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_YTD), ref fDollar_Credit_YTD, value); }
        }
        decimal fCost_Credit_01;
        public decimal Cost_Credit_01
        {
            get { return fCost_Credit_01; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_01), ref fCost_Credit_01, value); }
        }
        decimal fCost_Credit_02;
        public decimal Cost_Credit_02
        {
            get { return fCost_Credit_02; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_02), ref fCost_Credit_02, value); }
        }
        decimal fCost_Credit_03;
        public decimal Cost_Credit_03
        {
            get { return fCost_Credit_03; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_03), ref fCost_Credit_03, value); }
        }
        decimal fCost_Credit_04;
        public decimal Cost_Credit_04
        {
            get { return fCost_Credit_04; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_04), ref fCost_Credit_04, value); }
        }
        decimal fCost_Credit_05;
        public decimal Cost_Credit_05
        {
            get { return fCost_Credit_05; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_05), ref fCost_Credit_05, value); }
        }
        decimal fCost_Credit_06;
        public decimal Cost_Credit_06
        {
            get { return fCost_Credit_06; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_06), ref fCost_Credit_06, value); }
        }
        decimal fCost_Credit_07;
        public decimal Cost_Credit_07
        {
            get { return fCost_Credit_07; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_07), ref fCost_Credit_07, value); }
        }
        decimal fCost_Credit_08;
        public decimal Cost_Credit_08
        {
            get { return fCost_Credit_08; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_08), ref fCost_Credit_08, value); }
        }
        decimal fCost_Credit_09;
        public decimal Cost_Credit_09
        {
            get { return fCost_Credit_09; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_09), ref fCost_Credit_09, value); }
        }
        decimal fCost_Credit_10;
        public decimal Cost_Credit_10
        {
            get { return fCost_Credit_10; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_10), ref fCost_Credit_10, value); }
        }
        decimal fCost_Credit_11;
        public decimal Cost_Credit_11
        {
            get { return fCost_Credit_11; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_11), ref fCost_Credit_11, value); }
        }
        decimal fCost_Credit_12;
        public decimal Cost_Credit_12
        {
            get { return fCost_Credit_12; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_12), ref fCost_Credit_12, value); }
        }
        decimal fCost_Credit_YTD;
        public decimal Cost_Credit_YTD
        {
            get { return fCost_Credit_YTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_YTD), ref fCost_Credit_YTD, value); }
        }
        decimal fGP_Credit_01;
        public decimal GP_Credit_01
        {
            get { return fGP_Credit_01; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_01), ref fGP_Credit_01, value); }
        }
        decimal fGP_Credit_02;
        public decimal GP_Credit_02
        {
            get { return fGP_Credit_02; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_02), ref fGP_Credit_02, value); }
        }
        decimal fGP_Credit_03;
        public decimal GP_Credit_03
        {
            get { return fGP_Credit_03; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_03), ref fGP_Credit_03, value); }
        }
        decimal fGP_Credit_04;
        public decimal GP_Credit_04
        {
            get { return fGP_Credit_04; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_04), ref fGP_Credit_04, value); }
        }
        decimal fGP_Credit_05;
        public decimal GP_Credit_05
        {
            get { return fGP_Credit_05; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_05), ref fGP_Credit_05, value); }
        }
        decimal fGP_Credit_06;
        public decimal GP_Credit_06
        {
            get { return fGP_Credit_06; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_06), ref fGP_Credit_06, value); }
        }
        decimal fGP_Credit_07;
        public decimal GP_Credit_07
        {
            get { return fGP_Credit_07; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_07), ref fGP_Credit_07, value); }
        }
        decimal fGP_Credit_08;
        public decimal GP_Credit_08
        {
            get { return fGP_Credit_08; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_08), ref fGP_Credit_08, value); }
        }
        decimal fGP_Credit_09;
        public decimal GP_Credit_09
        {
            get { return fGP_Credit_09; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_09), ref fGP_Credit_09, value); }
        }
        decimal fGP_Credit_10;
        public decimal GP_Credit_10
        {
            get { return fGP_Credit_10; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_10), ref fGP_Credit_10, value); }
        }
        decimal fGP_Credit_11;
        public decimal GP_Credit_11
        {
            get { return fGP_Credit_11; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_11), ref fGP_Credit_11, value); }
        }
        decimal fGP_Credit_12;
        public decimal GP_Credit_12
        {
            get { return fGP_Credit_12; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_12), ref fGP_Credit_12, value); }
        }
        decimal fGP_Credit_YTD;
        public decimal GP_Credit_YTD
        {
            get { return fGP_Credit_YTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_YTD), ref fGP_Credit_YTD, value); }
        }
    }

}
