//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IM_History_Tracking : XPLiteObject
    {
        Guid fIM_History_Tracking_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IM_History_Tracking_ID
        {
            get { return fIM_History_Tracking_ID; }
            set { SetPropertyValue<Guid>(nameof(IM_History_Tracking_ID), ref fIM_History_Tracking_ID, value); }
        }
        IM_Main fIM_Main_ID;
        [Association(@"IM_History_TrackingReferencesIM_Main")]
        public IM_Main IM_Main_ID
        {
            get { return fIM_Main_ID; }
            set { SetPropertyValue<IM_Main>(nameof(IM_Main_ID), ref fIM_Main_ID, value); }
        }
        int fCurrent_Year;
        public int Current_Year
        {
            get { return fCurrent_Year; }
            set { SetPropertyValue<int>(nameof(Current_Year), ref fCurrent_Year, value); }
        }
        int fCurrent_Month;
        public int Current_Month
        {
            get { return fCurrent_Month; }
            set { SetPropertyValue<int>(nameof(Current_Month), ref fCurrent_Month, value); }
        }
        int fQTY_On_Hand;
        public int QTY_On_Hand
        {
            get { return fQTY_On_Hand; }
            set { SetPropertyValue<int>(nameof(QTY_On_Hand), ref fQTY_On_Hand, value); }
        }
        int fQTY_Open_SUM;
        public int QTY_Open_SUM
        {
            get { return fQTY_Open_SUM; }
            set { SetPropertyValue<int>(nameof(QTY_Open_SUM), ref fQTY_Open_SUM, value); }
        }
        int fQTY_Open_On_Hold_SUM;
        public int QTY_Open_On_Hold_SUM
        {
            get { return fQTY_Open_On_Hold_SUM; }
            set { SetPropertyValue<int>(nameof(QTY_Open_On_Hold_SUM), ref fQTY_Open_On_Hold_SUM, value); }
        }
        int fQTY_Open_Allocated_SUM;
        public int QTY_Open_Allocated_SUM
        {
            get { return fQTY_Open_Allocated_SUM; }
            set { SetPropertyValue<int>(nameof(QTY_Open_Allocated_SUM), ref fQTY_Open_Allocated_SUM, value); }
        }
        decimal fPrice_Open_SUM;
        public decimal Price_Open_SUM
        {
            get { return fPrice_Open_SUM; }
            set { SetPropertyValue<decimal>(nameof(Price_Open_SUM), ref fPrice_Open_SUM, value); }
        }
        decimal fCost_Open_SUM;
        public decimal Cost_Open_SUM
        {
            get { return fCost_Open_SUM; }
            set { SetPropertyValue<decimal>(nameof(Cost_Open_SUM), ref fCost_Open_SUM, value); }
        }
        int fQTY_Open_BO_SUM;
        public int QTY_Open_BO_SUM
        {
            get { return fQTY_Open_BO_SUM; }
            set { SetPropertyValue<int>(nameof(QTY_Open_BO_SUM), ref fQTY_Open_BO_SUM, value); }
        }
        int fQTY_Open_On_Hold_BO_SUM;
        public int QTY_Open_On_Hold_BO_SUM
        {
            get { return fQTY_Open_On_Hold_BO_SUM; }
            set { SetPropertyValue<int>(nameof(QTY_Open_On_Hold_BO_SUM), ref fQTY_Open_On_Hold_BO_SUM, value); }
        }
        int fQTY_Open_Allocated_BO_SUM;
        public int QTY_Open_Allocated_BO_SUM
        {
            get { return fQTY_Open_Allocated_BO_SUM; }
            set { SetPropertyValue<int>(nameof(QTY_Open_Allocated_BO_SUM), ref fQTY_Open_Allocated_BO_SUM, value); }
        }
        decimal fPrice_Open_BO_SUM;
        public decimal Price_Open_BO_SUM
        {
            get { return fPrice_Open_BO_SUM; }
            set { SetPropertyValue<decimal>(nameof(Price_Open_BO_SUM), ref fPrice_Open_BO_SUM, value); }
        }
        decimal fCost_Open_BO_SUM;
        public decimal Cost_Open_BO_SUM
        {
            get { return fCost_Open_BO_SUM; }
            set { SetPropertyValue<decimal>(nameof(Cost_Open_BO_SUM), ref fCost_Open_BO_SUM, value); }
        }
        int fBO_Open_COUNT;
        public int BO_Open_COUNT
        {
            get { return fBO_Open_COUNT; }
            set { SetPropertyValue<int>(nameof(BO_Open_COUNT), ref fBO_Open_COUNT, value); }
        }
        int fOrder_Open_COUNT;
        public int Order_Open_COUNT
        {
            get { return fOrder_Open_COUNT; }
            set { SetPropertyValue<int>(nameof(Order_Open_COUNT), ref fOrder_Open_COUNT, value); }
        }
        int fQTY_Open_PO_SUM;
        public int QTY_Open_PO_SUM
        {
            get { return fQTY_Open_PO_SUM; }
            set { SetPropertyValue<int>(nameof(QTY_Open_PO_SUM), ref fQTY_Open_PO_SUM, value); }
        }
        int fOrder_Open_PO_COUNT;
        public int Order_Open_PO_COUNT
        {
            get { return fOrder_Open_PO_COUNT; }
            set { SetPropertyValue<int>(nameof(Order_Open_PO_COUNT), ref fOrder_Open_PO_COUNT, value); }
        }
        int fQTY_Open_On_Water_SUM;
        public int QTY_Open_On_Water_SUM
        {
            get { return fQTY_Open_On_Water_SUM; }
            set { SetPropertyValue<int>(nameof(QTY_Open_On_Water_SUM), ref fQTY_Open_On_Water_SUM, value); }
        }
        int fOpen_On_Water_COUNT;
        public int Open_On_Water_COUNT
        {
            get { return fOpen_On_Water_COUNT; }
            set { SetPropertyValue<int>(nameof(Open_On_Water_COUNT), ref fOpen_On_Water_COUNT, value); }
        }
        int fQTY_At_Inventory_Count;
        public int QTY_At_Inventory_Count
        {
            get { return fQTY_At_Inventory_Count; }
            set { SetPropertyValue<int>(nameof(QTY_At_Inventory_Count), ref fQTY_At_Inventory_Count, value); }
        }
        DateTime fDate_Of_Inventory_Count;
        public DateTime Date_Of_Inventory_Count
        {
            get { return fDate_Of_Inventory_Count; }
            set { SetPropertyValue<DateTime>(nameof(Date_Of_Inventory_Count), ref fDate_Of_Inventory_Count, value); }
        }
        int fReorders_MTD;
        public int Reorders_MTD
        {
            get { return fReorders_MTD; }
            set { SetPropertyValue<int>(nameof(Reorders_MTD), ref fReorders_MTD, value); }
        }
        int fReorders_YTD;
        public int Reorders_YTD
        {
            get { return fReorders_YTD; }
            set { SetPropertyValue<int>(nameof(Reorders_YTD), ref fReorders_YTD, value); }
        }
        int fReorders_Line_To_Date;
        public int Reorders_Line_To_Date
        {
            get { return fReorders_Line_To_Date; }
            set { SetPropertyValue<int>(nameof(Reorders_Line_To_Date), ref fReorders_Line_To_Date, value); }
        }
        int fQTY_Sold_MTD;
        public int QTY_Sold_MTD
        {
            get { return fQTY_Sold_MTD; }
            set { SetPropertyValue<int>(nameof(QTY_Sold_MTD), ref fQTY_Sold_MTD, value); }
        }
        decimal fDollar_Sold_MTD;
        public decimal Dollar_Sold_MTD
        {
            get { return fDollar_Sold_MTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Sold_MTD), ref fDollar_Sold_MTD, value); }
        }
        decimal fCost_Sold_MTD;
        public decimal Cost_Sold_MTD
        {
            get { return fCost_Sold_MTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Sold_MTD), ref fCost_Sold_MTD, value); }
        }
        decimal fGP_Sold_MTD;
        public decimal GP_Sold_MTD
        {
            get { return fGP_Sold_MTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Sold_MTD), ref fGP_Sold_MTD, value); }
        }
        int fQTY_Credit_MTD;
        public int QTY_Credit_MTD
        {
            get { return fQTY_Credit_MTD; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_MTD), ref fQTY_Credit_MTD, value); }
        }
        decimal fDollar_Credit_MTD;
        public decimal Dollar_Credit_MTD
        {
            get { return fDollar_Credit_MTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_MTD), ref fDollar_Credit_MTD, value); }
        }
        decimal fCost_Credit_MTD;
        public decimal Cost_Credit_MTD
        {
            get { return fCost_Credit_MTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_MTD), ref fCost_Credit_MTD, value); }
        }
        decimal fGP_Credit_MTD;
        public decimal GP_Credit_MTD
        {
            get { return fGP_Credit_MTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_MTD), ref fGP_Credit_MTD, value); }
        }
        int fQTY_Return_MTD;
        public int QTY_Return_MTD
        {
            get { return fQTY_Return_MTD; }
            set { SetPropertyValue<int>(nameof(QTY_Return_MTD), ref fQTY_Return_MTD, value); }
        }
        decimal fDollar_Return_MTD;
        public decimal Dollar_Return_MTD
        {
            get { return fDollar_Return_MTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Return_MTD), ref fDollar_Return_MTD, value); }
        }
        decimal fCost_Return_MTD;
        public decimal Cost_Return_MTD
        {
            get { return fCost_Return_MTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Return_MTD), ref fCost_Return_MTD, value); }
        }
        decimal fGP_Return_MTD;
        public decimal GP_Return_MTD
        {
            get { return fGP_Return_MTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Return_MTD), ref fGP_Return_MTD, value); }
        }
        int fQTY_Stock_Outs_MTD;
        public int QTY_Stock_Outs_MTD
        {
            get { return fQTY_Stock_Outs_MTD; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_MTD), ref fQTY_Stock_Outs_MTD, value); }
        }
        decimal fDollar_Stock_Outs_MTD;
        public decimal Dollar_Stock_Outs_MTD
        {
            get { return fDollar_Stock_Outs_MTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_MTD), ref fDollar_Stock_Outs_MTD, value); }
        }
        decimal fCost_Stock_Outs_MTD;
        public decimal Cost_Stock_Outs_MTD
        {
            get { return fCost_Stock_Outs_MTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_MTD), ref fCost_Stock_Outs_MTD, value); }
        }
        decimal fGP_Stock_Outs_MTD;
        public decimal GP_Stock_Outs_MTD
        {
            get { return fGP_Stock_Outs_MTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_MTD), ref fGP_Stock_Outs_MTD, value); }
        }
        int fQTY_Lost_Sales_MTD;
        public int QTY_Lost_Sales_MTD
        {
            get { return fQTY_Lost_Sales_MTD; }
            set { SetPropertyValue<int>(nameof(QTY_Lost_Sales_MTD), ref fQTY_Lost_Sales_MTD, value); }
        }
        decimal fDollar_Lost_Sales_MTD;
        public decimal Dollar_Lost_Sales_MTD
        {
            get { return fDollar_Lost_Sales_MTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Lost_Sales_MTD), ref fDollar_Lost_Sales_MTD, value); }
        }
        decimal fCost_Lost_Sales_MTD;
        public decimal Cost_Lost_Sales_MTD
        {
            get { return fCost_Lost_Sales_MTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Lost_Sales_MTD), ref fCost_Lost_Sales_MTD, value); }
        }
        decimal fGP_Lost_Sales_MTD;
        public decimal GP_Lost_Sales_MTD
        {
            get { return fGP_Lost_Sales_MTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Lost_Sales_MTD), ref fGP_Lost_Sales_MTD, value); }
        }
        int fQTY_Sold_YTD;
        public int QTY_Sold_YTD
        {
            get { return fQTY_Sold_YTD; }
            set { SetPropertyValue<int>(nameof(QTY_Sold_YTD), ref fQTY_Sold_YTD, value); }
        }
        decimal fDollar_Sold_YTD;
        public decimal Dollar_Sold_YTD
        {
            get { return fDollar_Sold_YTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Sold_YTD), ref fDollar_Sold_YTD, value); }
        }
        decimal fCost_Sold_YTD;
        public decimal Cost_Sold_YTD
        {
            get { return fCost_Sold_YTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Sold_YTD), ref fCost_Sold_YTD, value); }
        }
        decimal fGP_Sold_YTD;
        public decimal GP_Sold_YTD
        {
            get { return fGP_Sold_YTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Sold_YTD), ref fGP_Sold_YTD, value); }
        }
        int fQTY_Credit_YTD;
        public int QTY_Credit_YTD
        {
            get { return fQTY_Credit_YTD; }
            set { SetPropertyValue<int>(nameof(QTY_Credit_YTD), ref fQTY_Credit_YTD, value); }
        }
        decimal fDollar_Credit_YTD;
        public decimal Dollar_Credit_YTD
        {
            get { return fDollar_Credit_YTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Credit_YTD), ref fDollar_Credit_YTD, value); }
        }
        decimal fCost_Credit_YTD;
        public decimal Cost_Credit_YTD
        {
            get { return fCost_Credit_YTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Credit_YTD), ref fCost_Credit_YTD, value); }
        }
        decimal fGP_Credit_YTD;
        public decimal GP_Credit_YTD
        {
            get { return fGP_Credit_YTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Credit_YTD), ref fGP_Credit_YTD, value); }
        }
        int fQTY_Return_YTD;
        public int QTY_Return_YTD
        {
            get { return fQTY_Return_YTD; }
            set { SetPropertyValue<int>(nameof(QTY_Return_YTD), ref fQTY_Return_YTD, value); }
        }
        decimal fDollar_Return_YTD;
        public decimal Dollar_Return_YTD
        {
            get { return fDollar_Return_YTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Return_YTD), ref fDollar_Return_YTD, value); }
        }
        decimal fCost_Return_YTD;
        public decimal Cost_Return_YTD
        {
            get { return fCost_Return_YTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Return_YTD), ref fCost_Return_YTD, value); }
        }
        decimal fGP_Return_YTD;
        public decimal GP_Return_YTD
        {
            get { return fGP_Return_YTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Return_YTD), ref fGP_Return_YTD, value); }
        }
        int fQTY_Stock_Outs_YTD;
        public int QTY_Stock_Outs_YTD
        {
            get { return fQTY_Stock_Outs_YTD; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_YTD), ref fQTY_Stock_Outs_YTD, value); }
        }
        decimal fDollar_Stock_Outs_YTD;
        public decimal Dollar_Stock_Outs_YTD
        {
            get { return fDollar_Stock_Outs_YTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_YTD), ref fDollar_Stock_Outs_YTD, value); }
        }
        decimal fCost_Stock_Outs_YTD;
        public decimal Cost_Stock_Outs_YTD
        {
            get { return fCost_Stock_Outs_YTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_YTD), ref fCost_Stock_Outs_YTD, value); }
        }
        decimal fGP_Stock_Outs_YTD;
        public decimal GP_Stock_Outs_YTD
        {
            get { return fGP_Stock_Outs_YTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_YTD), ref fGP_Stock_Outs_YTD, value); }
        }
        int fQTY_Lost_Sales_YTD;
        public int QTY_Lost_Sales_YTD
        {
            get { return fQTY_Lost_Sales_YTD; }
            set { SetPropertyValue<int>(nameof(QTY_Lost_Sales_YTD), ref fQTY_Lost_Sales_YTD, value); }
        }
        decimal fDollar_Lost_Sales_YTD;
        public decimal Dollar_Lost_Sales_YTD
        {
            get { return fDollar_Lost_Sales_YTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Lost_Sales_YTD), ref fDollar_Lost_Sales_YTD, value); }
        }
        decimal fCost_Lost_Sales_YTD;
        public decimal Cost_Lost_Sales_YTD
        {
            get { return fCost_Lost_Sales_YTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Lost_Sales_YTD), ref fCost_Lost_Sales_YTD, value); }
        }
        decimal fGP_Lost_Sales_YTD;
        public decimal GP_Lost_Sales_YTD
        {
            get { return fGP_Lost_Sales_YTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Lost_Sales_YTD), ref fGP_Lost_Sales_YTD, value); }
        }
        Guid fIM_History_Tracking1;
        [Persistent(@"IM_History_Tracking")]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IM_History_Tracking1
        {
            get { return fIM_History_Tracking1; }
            set { SetPropertyValue<Guid>(nameof(IM_History_Tracking1), ref fIM_History_Tracking1, value); }
        }
    }

}
