//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IM_History_Stock_Outs_Data : XPLiteObject
    {
        Guid fIM_History_Stock_Outs_Data_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IM_History_Stock_Outs_Data_ID
        {
            get { return fIM_History_Stock_Outs_Data_ID; }
            set { SetPropertyValue<Guid>(nameof(IM_History_Stock_Outs_Data_ID), ref fIM_History_Stock_Outs_Data_ID, value); }
        }
        int fDatabase_Index;
        public int Database_Index
        {
            get { return fDatabase_Index; }
            set { SetPropertyValue<int>(nameof(Database_Index), ref fDatabase_Index, value); }
        }
        int fScheduled_Move_or_Delete;
        public int Scheduled_Move_or_Delete
        {
            get { return fScheduled_Move_or_Delete; }
            set { SetPropertyValue<int>(nameof(Scheduled_Move_or_Delete), ref fScheduled_Move_or_Delete, value); }
        }
        bool fRecord_Closed;
        public bool Record_Closed
        {
            get { return fRecord_Closed; }
            set { SetPropertyValue<bool>(nameof(Record_Closed), ref fRecord_Closed, value); }
        }
        IM_Main fItem_Number;
        [Association(@"IM_History_Stock_Outs_DataReferencesIM_Main")]
        public IM_Main Item_Number
        {
            get { return fItem_Number; }
            set { SetPropertyValue<IM_Main>(nameof(Item_Number), ref fItem_Number, value); }
        }
        int fYear_Invoiced;
        public int Year_Invoiced
        {
            get { return fYear_Invoiced; }
            set { SetPropertyValue<int>(nameof(Year_Invoiced), ref fYear_Invoiced, value); }
        }
        int fQTY_Stock_Outs_01;
        public int QTY_Stock_Outs_01
        {
            get { return fQTY_Stock_Outs_01; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_01), ref fQTY_Stock_Outs_01, value); }
        }
        int fQTY_Stock_Outs_02;
        public int QTY_Stock_Outs_02
        {
            get { return fQTY_Stock_Outs_02; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_02), ref fQTY_Stock_Outs_02, value); }
        }
        int fQTY_Stock_Outs_03;
        public int QTY_Stock_Outs_03
        {
            get { return fQTY_Stock_Outs_03; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_03), ref fQTY_Stock_Outs_03, value); }
        }
        int fQTY_Stock_Outs_04;
        public int QTY_Stock_Outs_04
        {
            get { return fQTY_Stock_Outs_04; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_04), ref fQTY_Stock_Outs_04, value); }
        }
        int fQTY_Stock_Outs_05;
        public int QTY_Stock_Outs_05
        {
            get { return fQTY_Stock_Outs_05; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_05), ref fQTY_Stock_Outs_05, value); }
        }
        int fQTY_Stock_Outs_06;
        public int QTY_Stock_Outs_06
        {
            get { return fQTY_Stock_Outs_06; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_06), ref fQTY_Stock_Outs_06, value); }
        }
        int fQTY_Stock_Outs_07;
        public int QTY_Stock_Outs_07
        {
            get { return fQTY_Stock_Outs_07; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_07), ref fQTY_Stock_Outs_07, value); }
        }
        int fQTY_Stock_Outs_08;
        public int QTY_Stock_Outs_08
        {
            get { return fQTY_Stock_Outs_08; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_08), ref fQTY_Stock_Outs_08, value); }
        }
        int fQTY_Stock_Outs_09;
        public int QTY_Stock_Outs_09
        {
            get { return fQTY_Stock_Outs_09; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_09), ref fQTY_Stock_Outs_09, value); }
        }
        int fQTY_Stock_Outs_10;
        public int QTY_Stock_Outs_10
        {
            get { return fQTY_Stock_Outs_10; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_10), ref fQTY_Stock_Outs_10, value); }
        }
        int fQTY_Stock_Outs_11;
        public int QTY_Stock_Outs_11
        {
            get { return fQTY_Stock_Outs_11; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_11), ref fQTY_Stock_Outs_11, value); }
        }
        int fQTY_Stock_Outs_12;
        public int QTY_Stock_Outs_12
        {
            get { return fQTY_Stock_Outs_12; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_12), ref fQTY_Stock_Outs_12, value); }
        }
        int fQTY_Stock_Outs_YTD;
        public int QTY_Stock_Outs_YTD
        {
            get { return fQTY_Stock_Outs_YTD; }
            set { SetPropertyValue<int>(nameof(QTY_Stock_Outs_YTD), ref fQTY_Stock_Outs_YTD, value); }
        }
        decimal fDollar_Stock_Outs_01;
        public decimal Dollar_Stock_Outs_01
        {
            get { return fDollar_Stock_Outs_01; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_01), ref fDollar_Stock_Outs_01, value); }
        }
        decimal fDollar_Stock_Outs_02;
        public decimal Dollar_Stock_Outs_02
        {
            get { return fDollar_Stock_Outs_02; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_02), ref fDollar_Stock_Outs_02, value); }
        }
        decimal fDollar_Stock_Outs_03;
        public decimal Dollar_Stock_Outs_03
        {
            get { return fDollar_Stock_Outs_03; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_03), ref fDollar_Stock_Outs_03, value); }
        }
        decimal fDollar_Stock_Outs_04;
        public decimal Dollar_Stock_Outs_04
        {
            get { return fDollar_Stock_Outs_04; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_04), ref fDollar_Stock_Outs_04, value); }
        }
        decimal fDollar_Stock_Outs_05;
        public decimal Dollar_Stock_Outs_05
        {
            get { return fDollar_Stock_Outs_05; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_05), ref fDollar_Stock_Outs_05, value); }
        }
        decimal fDollar_Stock_Outs_06;
        public decimal Dollar_Stock_Outs_06
        {
            get { return fDollar_Stock_Outs_06; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_06), ref fDollar_Stock_Outs_06, value); }
        }
        decimal fDollar_Stock_Outs_07;
        public decimal Dollar_Stock_Outs_07
        {
            get { return fDollar_Stock_Outs_07; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_07), ref fDollar_Stock_Outs_07, value); }
        }
        decimal fDollar_Stock_Outs_08;
        public decimal Dollar_Stock_Outs_08
        {
            get { return fDollar_Stock_Outs_08; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_08), ref fDollar_Stock_Outs_08, value); }
        }
        decimal fDollar_Stock_Outs_09;
        public decimal Dollar_Stock_Outs_09
        {
            get { return fDollar_Stock_Outs_09; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_09), ref fDollar_Stock_Outs_09, value); }
        }
        decimal fDollar_Stock_Outs_10;
        public decimal Dollar_Stock_Outs_10
        {
            get { return fDollar_Stock_Outs_10; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_10), ref fDollar_Stock_Outs_10, value); }
        }
        decimal fDollar_Stock_Outs_11;
        public decimal Dollar_Stock_Outs_11
        {
            get { return fDollar_Stock_Outs_11; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_11), ref fDollar_Stock_Outs_11, value); }
        }
        decimal fDollar_Stock_Outs_12;
        public decimal Dollar_Stock_Outs_12
        {
            get { return fDollar_Stock_Outs_12; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_12), ref fDollar_Stock_Outs_12, value); }
        }
        decimal fDollar_Stock_Outs_YTD;
        public decimal Dollar_Stock_Outs_YTD
        {
            get { return fDollar_Stock_Outs_YTD; }
            set { SetPropertyValue<decimal>(nameof(Dollar_Stock_Outs_YTD), ref fDollar_Stock_Outs_YTD, value); }
        }
        decimal fCost_Stock_Outs_01;
        public decimal Cost_Stock_Outs_01
        {
            get { return fCost_Stock_Outs_01; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_01), ref fCost_Stock_Outs_01, value); }
        }
        decimal fCost_Stock_Outs_02;
        public decimal Cost_Stock_Outs_02
        {
            get { return fCost_Stock_Outs_02; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_02), ref fCost_Stock_Outs_02, value); }
        }
        decimal fCost_Stock_Outs_03;
        public decimal Cost_Stock_Outs_03
        {
            get { return fCost_Stock_Outs_03; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_03), ref fCost_Stock_Outs_03, value); }
        }
        decimal fCost_Stock_Outs_04;
        public decimal Cost_Stock_Outs_04
        {
            get { return fCost_Stock_Outs_04; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_04), ref fCost_Stock_Outs_04, value); }
        }
        decimal fCost_Stock_Outs_05;
        public decimal Cost_Stock_Outs_05
        {
            get { return fCost_Stock_Outs_05; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_05), ref fCost_Stock_Outs_05, value); }
        }
        decimal fCost_Stock_Outs_06;
        public decimal Cost_Stock_Outs_06
        {
            get { return fCost_Stock_Outs_06; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_06), ref fCost_Stock_Outs_06, value); }
        }
        decimal fCost_Stock_Outs_07;
        public decimal Cost_Stock_Outs_07
        {
            get { return fCost_Stock_Outs_07; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_07), ref fCost_Stock_Outs_07, value); }
        }
        decimal fCost_Stock_Outs_08;
        public decimal Cost_Stock_Outs_08
        {
            get { return fCost_Stock_Outs_08; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_08), ref fCost_Stock_Outs_08, value); }
        }
        decimal fCost_Stock_Outs_09;
        public decimal Cost_Stock_Outs_09
        {
            get { return fCost_Stock_Outs_09; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_09), ref fCost_Stock_Outs_09, value); }
        }
        decimal fCost_Stock_Outs_10;
        public decimal Cost_Stock_Outs_10
        {
            get { return fCost_Stock_Outs_10; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_10), ref fCost_Stock_Outs_10, value); }
        }
        decimal fCost_Stock_Outs_11;
        public decimal Cost_Stock_Outs_11
        {
            get { return fCost_Stock_Outs_11; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_11), ref fCost_Stock_Outs_11, value); }
        }
        decimal fCost_Stock_Outs_12;
        public decimal Cost_Stock_Outs_12
        {
            get { return fCost_Stock_Outs_12; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_12), ref fCost_Stock_Outs_12, value); }
        }
        decimal fCost_Stock_Outs_YTD;
        public decimal Cost_Stock_Outs_YTD
        {
            get { return fCost_Stock_Outs_YTD; }
            set { SetPropertyValue<decimal>(nameof(Cost_Stock_Outs_YTD), ref fCost_Stock_Outs_YTD, value); }
        }
        decimal fGP_Stock_Outs_01;
        public decimal GP_Stock_Outs_01
        {
            get { return fGP_Stock_Outs_01; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_01), ref fGP_Stock_Outs_01, value); }
        }
        decimal fGP_Stock_Outs_02;
        public decimal GP_Stock_Outs_02
        {
            get { return fGP_Stock_Outs_02; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_02), ref fGP_Stock_Outs_02, value); }
        }
        decimal fGP_Stock_Outs_03;
        public decimal GP_Stock_Outs_03
        {
            get { return fGP_Stock_Outs_03; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_03), ref fGP_Stock_Outs_03, value); }
        }
        decimal fGP_Stock_Outs_04;
        public decimal GP_Stock_Outs_04
        {
            get { return fGP_Stock_Outs_04; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_04), ref fGP_Stock_Outs_04, value); }
        }
        decimal fGP_Stock_Outs_05;
        public decimal GP_Stock_Outs_05
        {
            get { return fGP_Stock_Outs_05; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_05), ref fGP_Stock_Outs_05, value); }
        }
        decimal fGP_Stock_Outs_06;
        public decimal GP_Stock_Outs_06
        {
            get { return fGP_Stock_Outs_06; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_06), ref fGP_Stock_Outs_06, value); }
        }
        decimal fGP_Stock_Outs_07;
        public decimal GP_Stock_Outs_07
        {
            get { return fGP_Stock_Outs_07; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_07), ref fGP_Stock_Outs_07, value); }
        }
        decimal fGP_Stock_Outs_08;
        public decimal GP_Stock_Outs_08
        {
            get { return fGP_Stock_Outs_08; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_08), ref fGP_Stock_Outs_08, value); }
        }
        decimal fGP_Stock_Outs_09;
        public decimal GP_Stock_Outs_09
        {
            get { return fGP_Stock_Outs_09; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_09), ref fGP_Stock_Outs_09, value); }
        }
        decimal fGP_Stock_Outs_10;
        public decimal GP_Stock_Outs_10
        {
            get { return fGP_Stock_Outs_10; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_10), ref fGP_Stock_Outs_10, value); }
        }
        decimal fGP_Stock_Outs_11;
        public decimal GP_Stock_Outs_11
        {
            get { return fGP_Stock_Outs_11; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_11), ref fGP_Stock_Outs_11, value); }
        }
        decimal fGP_Stock_Outs_12;
        public decimal GP_Stock_Outs_12
        {
            get { return fGP_Stock_Outs_12; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_12), ref fGP_Stock_Outs_12, value); }
        }
        decimal fGP_Stock_Outs_YTD;
        public decimal GP_Stock_Outs_YTD
        {
            get { return fGP_Stock_Outs_YTD; }
            set { SetPropertyValue<decimal>(nameof(GP_Stock_Outs_YTD), ref fGP_Stock_Outs_YTD, value); }
        }
    }

}
