//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IM_Inner_Pack : XPLiteObject
    {
        Guid fIM_Inner_Pack_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IM_Inner_Pack_ID
        {
            get { return fIM_Inner_Pack_ID; }
            set { SetPropertyValue<Guid>(nameof(IM_Inner_Pack_ID), ref fIM_Inner_Pack_ID, value); }
        }
        IM_Main fIM_Main_ID;
        [Association(@"IM_Inner_PackReferencesIM_Main")]
        public IM_Main IM_Main_ID
        {
            get { return fIM_Main_ID; }
            set { SetPropertyValue<IM_Main>(nameof(IM_Main_ID), ref fIM_Main_ID, value); }
        }
        int fInner_Pack_QTY;
        public int Inner_Pack_QTY
        {
            get { return fInner_Pack_QTY; }
            set { SetPropertyValue<int>(nameof(Inner_Pack_QTY), ref fInner_Pack_QTY, value); }
        }
        pl_Unit fInner_Pack_Each_Unit;
        [Association(@"IM_Inner_PackReferencespl_Unit")]
        public pl_Unit Inner_Pack_Each_Unit
        {
            get { return fInner_Pack_Each_Unit; }
            set { SetPropertyValue<pl_Unit>(nameof(Inner_Pack_Each_Unit), ref fInner_Pack_Each_Unit, value); }
        }
        int fInner_Pack_Each_BL;
        public int Inner_Pack_Each_BL
        {
            get { return fInner_Pack_Each_BL; }
            set { SetPropertyValue<int>(nameof(Inner_Pack_Each_BL), ref fInner_Pack_Each_BL, value); }
        }
        pl_How_Each_Packed fInner_Pack_Each;
        [Association(@"IM_Inner_PackReferencespl_How_Each_Packed")]
        public pl_How_Each_Packed Inner_Pack_Each
        {
            get { return fInner_Pack_Each; }
            set { SetPropertyValue<pl_How_Each_Packed>(nameof(Inner_Pack_Each), ref fInner_Pack_Each, value); }
        }
    }

}
