//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IM_QTY_Cost : XPLiteObject
    {
        Guid fIM_QTY_Cost_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IM_QTY_Cost_ID
        {
            get { return fIM_QTY_Cost_ID; }
            set { SetPropertyValue<Guid>(nameof(IM_QTY_Cost_ID), ref fIM_QTY_Cost_ID, value); }
        }
        IM_Main fIM_Main_ID;
        [Association(@"IM_QTY_CostReferencesIM_Main")]
        public IM_Main IM_Main_ID
        {
            get { return fIM_Main_ID; }
            set { SetPropertyValue<IM_Main>(nameof(IM_Main_ID), ref fIM_Main_ID, value); }
        }
        decimal fFirst_Cost;
        public decimal First_Cost
        {
            get { return fFirst_Cost; }
            set { SetPropertyValue<decimal>(nameof(First_Cost), ref fFirst_Cost, value); }
        }
        decimal fLanded_Cost;
        public decimal Landed_Cost
        {
            get { return fLanded_Cost; }
            set { SetPropertyValue<decimal>(nameof(Landed_Cost), ref fLanded_Cost, value); }
        }
        decimal fAverage_Cost;
        public decimal Average_Cost
        {
            get { return fAverage_Cost; }
            set { SetPropertyValue<decimal>(nameof(Average_Cost), ref fAverage_Cost, value); }
        }
        decimal fReplacement_Cost;
        public decimal Replacement_Cost
        {
            get { return fReplacement_Cost; }
            set { SetPropertyValue<decimal>(nameof(Replacement_Cost), ref fReplacement_Cost, value); }
        }
    }

}
