//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IP_Data : XPLiteObject
    {
        Guid fIP_Data_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IP_Data_ID
        {
            get { return fIP_Data_ID; }
            set { SetPropertyValue<Guid>(nameof(IP_Data_ID), ref fIP_Data_ID, value); }
        }
        int fImprint_Data_ID;
        public int Imprint_Data_ID
        {
            get { return fImprint_Data_ID; }
            set { SetPropertyValue<int>(nameof(Imprint_Data_ID), ref fImprint_Data_ID, value); }
        }
        string fState;
        [Size(2)]
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>(nameof(State), ref fState, value); }
        }
        string fState_Name;
        [Size(50)]
        public string State_Name
        {
            get { return fState_Name; }
            set { SetPropertyValue<string>(nameof(State_Name), ref fState_Name, value); }
        }
        string fText_Line_1;
        [Size(160)]
        public string Text_Line_1
        {
            get { return fText_Line_1; }
            set { SetPropertyValue<string>(nameof(Text_Line_1), ref fText_Line_1, value); }
        }
        string fText_Line_2;
        [Size(160)]
        public string Text_Line_2
        {
            get { return fText_Line_2; }
            set { SetPropertyValue<string>(nameof(Text_Line_2), ref fText_Line_2, value); }
        }
        string fText_Line_3;
        [Size(160)]
        public string Text_Line_3
        {
            get { return fText_Line_3; }
            set { SetPropertyValue<string>(nameof(Text_Line_3), ref fText_Line_3, value); }
        }
        string fText_Line_4;
        [Size(160)]
        public string Text_Line_4
        {
            get { return fText_Line_4; }
            set { SetPropertyValue<string>(nameof(Text_Line_4), ref fText_Line_4, value); }
        }
        string fText_Line_5;
        [Size(160)]
        public string Text_Line_5
        {
            get { return fText_Line_5; }
            set { SetPropertyValue<string>(nameof(Text_Line_5), ref fText_Line_5, value); }
        }
        string fComment_Remark;
        [Size(160)]
        public string Comment_Remark
        {
            get { return fComment_Remark; }
            set { SetPropertyValue<string>(nameof(Comment_Remark), ref fComment_Remark, value); }
        }
        string fFilm_Sizes;
        [Size(SizeAttribute.Unlimited)]
        public string Film_Sizes
        {
            get { return fFilm_Sizes; }
            set { SetPropertyValue<string>(nameof(Film_Sizes), ref fFilm_Sizes, value); }
        }
        bool fNeed_Film;
        public bool Need_Film
        {
            get { return fNeed_Film; }
            set { SetPropertyValue<bool>(nameof(Need_Film), ref fNeed_Film, value); }
        }
        DateTime fDate_Ordered;
        public DateTime Date_Ordered
        {
            get { return fDate_Ordered; }
            set { SetPropertyValue<DateTime>(nameof(Date_Ordered), ref fDate_Ordered, value); }
        }
        DateTime fDate_Received;
        public DateTime Date_Received
        {
            get { return fDate_Received; }
            set { SetPropertyValue<DateTime>(nameof(Date_Received), ref fDate_Received, value); }
        }
        int fMove_Match_Key;
        public int Move_Match_Key
        {
            get { return fMove_Match_Key; }
            set { SetPropertyValue<int>(nameof(Move_Match_Key), ref fMove_Match_Key, value); }
        }
        string fSum_Line_NO_SPACES;
        [Size(SizeAttribute.Unlimited)]
        public string Sum_Line_NO_SPACES
        {
            get { return fSum_Line_NO_SPACES; }
            set { SetPropertyValue<string>(nameof(Sum_Line_NO_SPACES), ref fSum_Line_NO_SPACES, value); }
        }
        string fSum_Line;
        [Size(SizeAttribute.Unlimited)]
        public string Sum_Line
        {
            get { return fSum_Line; }
            set { SetPropertyValue<string>(nameof(Sum_Line), ref fSum_Line, value); }
        }
        string fAlpha_Code;
        [Size(1)]
        public string Alpha_Code
        {
            get { return fAlpha_Code; }
            set { SetPropertyValue<string>(nameof(Alpha_Code), ref fAlpha_Code, value); }
        }
        [Association(@"RM_Line_ItemsReferencesIP_Data")]
        public XPCollection<RM_Line_Items> RM_Line_Itemss { get { return GetCollection<RM_Line_Items>(nameof(RM_Line_Itemss)); } }
    }

}
