//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IR_Main : XPLiteObject
    {
        Guid fIR_Main_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IR_Main_ID
        {
            get { return fIR_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(IR_Main_ID), ref fIR_Main_ID, value); }
        }
        IR_Batch fIR_Batch_ID;
        [Association(@"IR_MainReferencesIR_Batch")]
        public IR_Batch IR_Batch_ID
        {
            get { return fIR_Batch_ID; }
            set { SetPropertyValue<IR_Batch>(nameof(IR_Batch_ID), ref fIR_Batch_ID, value); }
        }
        Guid fIR_Item_ID;
        public Guid IR_Item_ID
        {
            get { return fIR_Item_ID; }
            set { SetPropertyValue<Guid>(nameof(IR_Item_ID), ref fIR_Item_ID, value); }
        }
        DateTime fReceipt_Posting_Date;
        public DateTime Receipt_Posting_Date
        {
            get { return fReceipt_Posting_Date; }
            set { SetPropertyValue<DateTime>(nameof(Receipt_Posting_Date), ref fReceipt_Posting_Date, value); }
        }
        IM_Main fIM_Main_ID;
        [Association(@"IR_MainReferencesIM_Main")]
        public IM_Main IM_Main_ID
        {
            get { return fIM_Main_ID; }
            set { SetPropertyValue<IM_Main>(nameof(IM_Main_ID), ref fIM_Main_ID, value); }
        }
        int fDefault_BL;
        public int Default_BL
        {
            get { return fDefault_BL; }
            set { SetPropertyValue<int>(nameof(Default_BL), ref fDefault_BL, value); }
        }
        int fQTY_Before_Receipt;
        public int QTY_Before_Receipt
        {
            get { return fQTY_Before_Receipt; }
            set { SetPropertyValue<int>(nameof(QTY_Before_Receipt), ref fQTY_Before_Receipt, value); }
        }
        decimal fCost_Before_Receipt;
        public decimal Cost_Before_Receipt
        {
            get { return fCost_Before_Receipt; }
            set { SetPropertyValue<decimal>(nameof(Cost_Before_Receipt), ref fCost_Before_Receipt, value); }
        }
        int fQTY_on_Receipt;
        public int QTY_on_Receipt
        {
            get { return fQTY_on_Receipt; }
            set { SetPropertyValue<int>(nameof(QTY_on_Receipt), ref fQTY_on_Receipt, value); }
        }
        decimal fCost_on_Receipt;
        public decimal Cost_on_Receipt
        {
            get { return fCost_on_Receipt; }
            set { SetPropertyValue<decimal>(nameof(Cost_on_Receipt), ref fCost_on_Receipt, value); }
        }
        int fNew_QTY_ON_Hand;
        public int New_QTY_ON_Hand
        {
            get { return fNew_QTY_ON_Hand; }
            set { SetPropertyValue<int>(nameof(New_QTY_ON_Hand), ref fNew_QTY_ON_Hand, value); }
        }
        decimal fNew_Average_Cost;
        public decimal New_Average_Cost
        {
            get { return fNew_Average_Cost; }
            set { SetPropertyValue<decimal>(nameof(New_Average_Cost), ref fNew_Average_Cost, value); }
        }
        PO_Main fPO_Main_ID;
        [Association(@"IR_MainReferencesPO_Main")]
        public PO_Main PO_Main_ID
        {
            get { return fPO_Main_ID; }
            set { SetPropertyValue<PO_Main>(nameof(PO_Main_ID), ref fPO_Main_ID, value); }
        }
        PO_Line_Items fPO_Line_Items_ID;
        [Association(@"IR_MainReferencesPO_Line_Items")]
        public PO_Line_Items PO_Line_Items_ID
        {
            get { return fPO_Line_Items_ID; }
            set { SetPropertyValue<PO_Line_Items>(nameof(PO_Line_Items_ID), ref fPO_Line_Items_ID, value); }
        }
        pl_Vessel_Name fVessel_ID;
        [Association(@"IR_MainReferencespl_Vessel_Name")]
        public pl_Vessel_Name Vessel_ID
        {
            get { return fVessel_ID; }
            set { SetPropertyValue<pl_Vessel_Name>(nameof(Vessel_ID), ref fVessel_ID, value); }
        }
        DateTime fDate_Time_Received;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime Date_Time_Received
        {
            get { return fDate_Time_Received; }
            set { SetPropertyValue<DateTime>(nameof(Date_Time_Received), ref fDate_Time_Received, value); }
        }
        string fQTY_Before_Receipt_Text;
        [Size(25)]
        public string QTY_Before_Receipt_Text
        {
            get { return fQTY_Before_Receipt_Text; }
            set { SetPropertyValue<string>(nameof(QTY_Before_Receipt_Text), ref fQTY_Before_Receipt_Text, value); }
        }
        string fQTY_on_Receipt_Text;
        [Size(25)]
        public string QTY_on_Receipt_Text
        {
            get { return fQTY_on_Receipt_Text; }
            set { SetPropertyValue<string>(nameof(QTY_on_Receipt_Text), ref fQTY_on_Receipt_Text, value); }
        }
        string fNew_QTY_ON_Hand_Text;
        [Size(25)]
        public string New_QTY_ON_Hand_Text
        {
            get { return fNew_QTY_ON_Hand_Text; }
            set { SetPropertyValue<string>(nameof(New_QTY_ON_Hand_Text), ref fNew_QTY_ON_Hand_Text, value); }
        }
    }

}
