//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class IV_Main : XPLiteObject
    {
        Guid fIV_Main_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid IV_Main_ID
        {
            get { return fIV_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(IV_Main_ID), ref fIV_Main_ID, value); }
        }
        string fInvoice_Number;
        [Size(25)]
        public string Invoice_Number
        {
            get { return fInvoice_Number; }
            set { SetPropertyValue<string>(nameof(Invoice_Number), ref fInvoice_Number, value); }
        }
        pl_Transaction fTransaction_Type;
        [Association(@"IV_MainReferencespl_Transaction")]
        public pl_Transaction Transaction_Type
        {
            get { return fTransaction_Type; }
            set { SetPropertyValue<pl_Transaction>(nameof(Transaction_Type), ref fTransaction_Type, value); }
        }
        CM_Main fCM_Main_ID;
        [Association(@"IV_MainReferencesCM_Main")]
        public CM_Main CM_Main_ID
        {
            get { return fCM_Main_ID; }
            set { SetPropertyValue<CM_Main>(nameof(CM_Main_ID), ref fCM_Main_ID, value); }
        }
        DateTime fInvoice_Date;
        public DateTime Invoice_Date
        {
            get { return fInvoice_Date; }
            set { SetPropertyValue<DateTime>(nameof(Invoice_Date), ref fInvoice_Date, value); }
        }
        decimal fTotal_Invoice_Amount;
        public decimal Total_Invoice_Amount
        {
            get { return fTotal_Invoice_Amount; }
            set { SetPropertyValue<decimal>(nameof(Total_Invoice_Amount), ref fTotal_Invoice_Amount, value); }
        }
        decimal fInvoice_Items_Amount;
        public decimal Invoice_Items_Amount
        {
            get { return fInvoice_Items_Amount; }
            set { SetPropertyValue<decimal>(nameof(Invoice_Items_Amount), ref fInvoice_Items_Amount, value); }
        }
        RM_Main fRM_Main_ID;
        [Association(@"IV_MainReferencesRM_Main")]
        public RM_Main RM_Main_ID
        {
            get { return fRM_Main_ID; }
            set { SetPropertyValue<RM_Main>(nameof(RM_Main_ID), ref fRM_Main_ID, value); }
        }
        decimal fInvoice_Balance;
        public decimal Invoice_Balance
        {
            get { return fInvoice_Balance; }
            set { SetPropertyValue<decimal>(nameof(Invoice_Balance), ref fInvoice_Balance, value); }
        }
    }

}
