//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class OS_Raw_Order_Header : XPLiteObject
    {
        Guid fOS_Raw_Order_Header_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid OS_Raw_Order_Header_ID
        {
            get { return fOS_Raw_Order_Header_ID; }
            set { SetPropertyValue<Guid>(nameof(OS_Raw_Order_Header_ID), ref fOS_Raw_Order_Header_ID, value); }
        }
        string fNew_Order_Number;
        [Size(25)]
        public string New_Order_Number
        {
            get { return fNew_Order_Number; }
            set { SetPropertyValue<string>(nameof(New_Order_Number), ref fNew_Order_Number, value); }
        }
        string fHotSyncName;
        [Size(255)]
        public string HotSyncName
        {
            get { return fHotSyncName; }
            set { SetPropertyValue<string>(nameof(HotSyncName), ref fHotSyncName, value); }
        }
        string fOrderDate;
        [Size(255)]
        public string OrderDate
        {
            get { return fOrderDate; }
            set { SetPropertyValue<string>(nameof(OrderDate), ref fOrderDate, value); }
        }
        string fExpectedDate;
        [Size(255)]
        public string ExpectedDate
        {
            get { return fExpectedDate; }
            set { SetPropertyValue<string>(nameof(ExpectedDate), ref fExpectedDate, value); }
        }
        string fCancelDate;
        [Size(255)]
        public string CancelDate
        {
            get { return fCancelDate; }
            set { SetPropertyValue<string>(nameof(CancelDate), ref fCancelDate, value); }
        }
        string fLastVisitDate;
        [Size(255)]
        public string LastVisitDate
        {
            get { return fLastVisitDate; }
            set { SetPropertyValue<string>(nameof(LastVisitDate), ref fLastVisitDate, value); }
        }
        string fNextVisitDate;
        [Size(255)]
        public string NextVisitDate
        {
            get { return fNextVisitDate; }
            set { SetPropertyValue<string>(nameof(NextVisitDate), ref fNextVisitDate, value); }
        }
        string fOpenStatus;
        [Size(255)]
        public string OpenStatus
        {
            get { return fOpenStatus; }
            set { SetPropertyValue<string>(nameof(OpenStatus), ref fOpenStatus, value); }
        }
        string fNewCustomerStatus;
        [Size(255)]
        public string NewCustomerStatus
        {
            get { return fNewCustomerStatus; }
            set { SetPropertyValue<string>(nameof(NewCustomerStatus), ref fNewCustomerStatus, value); }
        }
        string fNewAccount;
        [Size(255)]
        public string NewAccount
        {
            get { return fNewAccount; }
            set { SetPropertyValue<string>(nameof(NewAccount), ref fNewAccount, value); }
        }
        string fOnHoldStatus;
        [Size(255)]
        public string OnHoldStatus
        {
            get { return fOnHoldStatus; }
            set { SetPropertyValue<string>(nameof(OnHoldStatus), ref fOnHoldStatus, value); }
        }
        string fNumDetailLines;
        [Size(255)]
        public string NumDetailLines
        {
            get { return fNumDetailLines; }
            set { SetPropertyValue<string>(nameof(NumDetailLines), ref fNumDetailLines, value); }
        }
        string fType;
        [Size(255)]
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>(nameof(Type), ref fType, value); }
        }
        string fOrderNumber;
        [Indexed(Name = @"IX_OS_Raw_Order_Header")]
        [Size(255)]
        public string OrderNumber
        {
            get { return fOrderNumber; }
            set { SetPropertyValue<string>(nameof(OrderNumber), ref fOrderNumber, value); }
        }
        string fCustomerNumber;
        [Size(255)]
        public string CustomerNumber
        {
            get { return fCustomerNumber; }
            set { SetPropertyValue<string>(nameof(CustomerNumber), ref fCustomerNumber, value); }
        }
        string fCustomerName;
        [Size(255)]
        public string CustomerName
        {
            get { return fCustomerName; }
            set { SetPropertyValue<string>(nameof(CustomerName), ref fCustomerName, value); }
        }
        string fAddress1;
        [Size(255)]
        public string Address1
        {
            get { return fAddress1; }
            set { SetPropertyValue<string>(nameof(Address1), ref fAddress1, value); }
        }
        string fAddress2;
        [Size(255)]
        public string Address2
        {
            get { return fAddress2; }
            set { SetPropertyValue<string>(nameof(Address2), ref fAddress2, value); }
        }
        string fCity;
        [Size(255)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fState_Province;
        [Size(255)]
        public string State_Province
        {
            get { return fState_Province; }
            set { SetPropertyValue<string>(nameof(State_Province), ref fState_Province, value); }
        }
        string fZip_PostalCode;
        [Size(255)]
        public string Zip_PostalCode
        {
            get { return fZip_PostalCode; }
            set { SetPropertyValue<string>(nameof(Zip_PostalCode), ref fZip_PostalCode, value); }
        }
        string fCountry;
        [Size(255)]
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
        string fPhone;
        [Size(255)]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fContact;
        [Size(255)]
        public string Contact
        {
            get { return fContact; }
            set { SetPropertyValue<string>(nameof(Contact), ref fContact, value); }
        }
        string fSalesRep;
        [Size(255)]
        public string SalesRep
        {
            get { return fSalesRep; }
            set { SetPropertyValue<string>(nameof(SalesRep), ref fSalesRep, value); }
        }
        string fLocation;
        [Size(255)]
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        string fCompanyCode;
        [Size(255)]
        public string CompanyCode
        {
            get { return fCompanyCode; }
            set { SetPropertyValue<string>(nameof(CompanyCode), ref fCompanyCode, value); }
        }
        string fUnitID;
        [Size(255)]
        public string UnitID
        {
            get { return fUnitID; }
            set { SetPropertyValue<string>(nameof(UnitID), ref fUnitID, value); }
        }
        string fPurchaseOrder;
        [Size(255)]
        public string PurchaseOrder
        {
            get { return fPurchaseOrder; }
            set { SetPropertyValue<string>(nameof(PurchaseOrder), ref fPurchaseOrder, value); }
        }
        string fTerms;
        [Size(255)]
        public string Terms
        {
            get { return fTerms; }
            set { SetPropertyValue<string>(nameof(Terms), ref fTerms, value); }
        }
        string fGlobalDiscount;
        [Size(255)]
        public string GlobalDiscount
        {
            get { return fGlobalDiscount; }
            set { SetPropertyValue<string>(nameof(GlobalDiscount), ref fGlobalDiscount, value); }
        }
        string fPDARep;
        [Size(255)]
        public string PDARep
        {
            get { return fPDARep; }
            set { SetPropertyValue<string>(nameof(PDARep), ref fPDARep, value); }
        }
        string fWrittenBy;
        [Size(255)]
        public string WrittenBy
        {
            get { return fWrittenBy; }
            set { SetPropertyValue<string>(nameof(WrittenBy), ref fWrittenBy, value); }
        }
        string fCustomerStatus;
        [Size(255)]
        public string CustomerStatus
        {
            get { return fCustomerStatus; }
            set { SetPropertyValue<string>(nameof(CustomerStatus), ref fCustomerStatus, value); }
        }
        string fLastUpdateTime;
        [Size(255)]
        public string LastUpdateTime
        {
            get { return fLastUpdateTime; }
            set { SetPropertyValue<string>(nameof(LastUpdateTime), ref fLastUpdateTime, value); }
        }
        string fMfgCode;
        [Size(255)]
        public string MfgCode
        {
            get { return fMfgCode; }
            set { SetPropertyValue<string>(nameof(MfgCode), ref fMfgCode, value); }
        }
        string fOrderTag;
        [Size(255)]
        public string OrderTag
        {
            get { return fOrderTag; }
            set { SetPropertyValue<string>(nameof(OrderTag), ref fOrderTag, value); }
        }
        string fShipToNumber;
        [Size(255)]
        public string ShipToNumber
        {
            get { return fShipToNumber; }
            set { SetPropertyValue<string>(nameof(ShipToNumber), ref fShipToNumber, value); }
        }
        string fShipToName;
        [Size(255)]
        public string ShipToName
        {
            get { return fShipToName; }
            set { SetPropertyValue<string>(nameof(ShipToName), ref fShipToName, value); }
        }
        string fShipToAddress1;
        [Size(255)]
        public string ShipToAddress1
        {
            get { return fShipToAddress1; }
            set { SetPropertyValue<string>(nameof(ShipToAddress1), ref fShipToAddress1, value); }
        }
        string fShipToAddress2;
        [Size(255)]
        public string ShipToAddress2
        {
            get { return fShipToAddress2; }
            set { SetPropertyValue<string>(nameof(ShipToAddress2), ref fShipToAddress2, value); }
        }
        string fShipToCity;
        [Size(255)]
        public string ShipToCity
        {
            get { return fShipToCity; }
            set { SetPropertyValue<string>(nameof(ShipToCity), ref fShipToCity, value); }
        }
        string fShipToState_Province;
        [Size(255)]
        public string ShipToState_Province
        {
            get { return fShipToState_Province; }
            set { SetPropertyValue<string>(nameof(ShipToState_Province), ref fShipToState_Province, value); }
        }
        string fShipToZip_PostalCode;
        [Size(255)]
        public string ShipToZip_PostalCode
        {
            get { return fShipToZip_PostalCode; }
            set { SetPropertyValue<string>(nameof(ShipToZip_PostalCode), ref fShipToZip_PostalCode, value); }
        }
        string fShipToCountry;
        [Size(255)]
        public string ShipToCountry
        {
            get { return fShipToCountry; }
            set { SetPropertyValue<string>(nameof(ShipToCountry), ref fShipToCountry, value); }
        }
        string fShipToPhone;
        [Size(255)]
        public string ShipToPhone
        {
            get { return fShipToPhone; }
            set { SetPropertyValue<string>(nameof(ShipToPhone), ref fShipToPhone, value); }
        }
        string fHDName;
        [Size(255)]
        public string HDName
        {
            get { return fHDName; }
            set { SetPropertyValue<string>(nameof(HDName), ref fHDName, value); }
        }
        string fHDAddress1;
        [Size(255)]
        public string HDAddress1
        {
            get { return fHDAddress1; }
            set { SetPropertyValue<string>(nameof(HDAddress1), ref fHDAddress1, value); }
        }
        string fHDAddress2;
        [Size(255)]
        public string HDAddress2
        {
            get { return fHDAddress2; }
            set { SetPropertyValue<string>(nameof(HDAddress2), ref fHDAddress2, value); }
        }
        string fHDCity;
        [Size(255)]
        public string HDCity
        {
            get { return fHDCity; }
            set { SetPropertyValue<string>(nameof(HDCity), ref fHDCity, value); }
        }
        string fHDProvince;
        [Size(255)]
        public string HDProvince
        {
            get { return fHDProvince; }
            set { SetPropertyValue<string>(nameof(HDProvince), ref fHDProvince, value); }
        }
        string fHDPostalCode;
        [Size(255)]
        public string HDPostalCode
        {
            get { return fHDPostalCode; }
            set { SetPropertyValue<string>(nameof(HDPostalCode), ref fHDPostalCode, value); }
        }
        string fHDCountry;
        [Size(255)]
        public string HDCountry
        {
            get { return fHDCountry; }
            set { SetPropertyValue<string>(nameof(HDCountry), ref fHDCountry, value); }
        }
        string fHDPhone;
        [Size(255)]
        public string HDPhone
        {
            get { return fHDPhone; }
            set { SetPropertyValue<string>(nameof(HDPhone), ref fHDPhone, value); }
        }
        string fComment;
        [Size(255)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        string fCustom1;
        [Size(255)]
        public string Custom1
        {
            get { return fCustom1; }
            set { SetPropertyValue<string>(nameof(Custom1), ref fCustom1, value); }
        }
        string fCustom2;
        [Size(255)]
        public string Custom2
        {
            get { return fCustom2; }
            set { SetPropertyValue<string>(nameof(Custom2), ref fCustom2, value); }
        }
        string fCustom3;
        [Size(255)]
        public string Custom3
        {
            get { return fCustom3; }
            set { SetPropertyValue<string>(nameof(Custom3), ref fCustom3, value); }
        }
        string fCustom4;
        [Size(255)]
        public string Custom4
        {
            get { return fCustom4; }
            set { SetPropertyValue<string>(nameof(Custom4), ref fCustom4, value); }
        }
        int fRow_Index;
        public int Row_Index
        {
            get { return fRow_Index; }
            set { SetPropertyValue<int>(nameof(Row_Index), ref fRow_Index, value); }
        }
        string fShipViaCompressed;
        [Size(255)]
        public string ShipViaCompressed
        {
            get { return fShipViaCompressed; }
            set { SetPropertyValue<string>(nameof(ShipViaCompressed), ref fShipViaCompressed, value); }
        }
        string fTermsCompressed;
        [Size(255)]
        public string TermsCompressed
        {
            get { return fTermsCompressed; }
            set { SetPropertyValue<string>(nameof(TermsCompressed), ref fTermsCompressed, value); }
        }
        DateTime fCreate_Date_Time;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime Create_Date_Time
        {
            get { return fCreate_Date_Time; }
            set { SetPropertyValue<DateTime>(nameof(Create_Date_Time), ref fCreate_Date_Time, value); }
        }
        string fFile_Name;
        [Size(255)]
        public string File_Name
        {
            get { return fFile_Name; }
            set { SetPropertyValue<string>(nameof(File_Name), ref fFile_Name, value); }
        }
        [Association(@"OS_Raw_Order_LineReferencesOS_Raw_Order_Header")]
        public XPCollection<OS_Raw_Order_Line> OS_Raw_Order_Lines { get { return GetCollection<OS_Raw_Order_Line>(nameof(OS_Raw_Order_Lines)); } }
    }

}
