//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class OS_Raw_Export_Log : XPLiteObject
    {
        Guid fOS_Raw_Export_Log_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid OS_Raw_Export_Log_ID
        {
            get { return fOS_Raw_Export_Log_ID; }
            set { SetPropertyValue<Guid>(nameof(OS_Raw_Export_Log_ID), ref fOS_Raw_Export_Log_ID, value); }
        }
        int fNew_Accounts;
        public int New_Accounts
        {
            get { return fNew_Accounts; }
            set { SetPropertyValue<int>(nameof(New_Accounts), ref fNew_Accounts, value); }
        }
        int fLog_Export_Count;
        public int Log_Export_Count
        {
            get { return fLog_Export_Count; }
            set { SetPropertyValue<int>(nameof(Log_Export_Count), ref fLog_Export_Count, value); }
        }
        string fFile_Mark;
        [Size(20)]
        public string File_Mark
        {
            get { return fFile_Mark; }
            set { SetPropertyValue<string>(nameof(File_Mark), ref fFile_Mark, value); }
        }
        int fOrders_Found;
        public int Orders_Found
        {
            get { return fOrders_Found; }
            set { SetPropertyValue<int>(nameof(Orders_Found), ref fOrders_Found, value); }
        }
        int fErrors_Found;
        public int Errors_Found
        {
            get { return fErrors_Found; }
            set { SetPropertyValue<int>(nameof(Errors_Found), ref fErrors_Found, value); }
        }
        string fError_Text;
        [Size(512)]
        public string Error_Text
        {
            get { return fError_Text; }
            set { SetPropertyValue<string>(nameof(Error_Text), ref fError_Text, value); }
        }
    }

}
