//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class pl_Country : XPLiteObject
    {
        Guid fpl_Country_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid pl_Country_ID
        {
            get { return fpl_Country_ID; }
            set { SetPropertyValue<Guid>(nameof(pl_Country_ID), ref fpl_Country_ID, value); }
        }
        decimal fSort_Order;
        [Indexed(@"Description", Name = @"IX_pl_Country")]
        [ColumnDbDefaultValue("((0))")]
        public decimal Sort_Order
        {
            get { return fSort_Order; }
            set { SetPropertyValue<decimal>(nameof(Sort_Order), ref fSort_Order, value); }
        }
        string fDescription;
        [Size(50)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fDescription_Short;
        [Size(50)]
        public string Description_Short
        {
            get { return fDescription_Short; }
            set { SetPropertyValue<string>(nameof(Description_Short), ref fDescription_Short, value); }
        }
        string fOptional_Data_Text;
        [Size(50)]
        public string Optional_Data_Text
        {
            get { return fOptional_Data_Text; }
            set { SetPropertyValue<string>(nameof(Optional_Data_Text), ref fOptional_Data_Text, value); }
        }
        int fOptional_Data_Int;
        public int Optional_Data_Int
        {
            get { return fOptional_Data_Int; }
            set { SetPropertyValue<int>(nameof(Optional_Data_Int), ref fOptional_Data_Int, value); }
        }
        int fUser_Select_UI;
        public int User_Select_UI
        {
            get { return fUser_Select_UI; }
            set { SetPropertyValue<int>(nameof(User_Select_UI), ref fUser_Select_UI, value); }
        }
        bool fDeleted_Item;
        public bool Deleted_Item
        {
            get { return fDeleted_Item; }
            set { SetPropertyValue<bool>(nameof(Deleted_Item), ref fDeleted_Item, value); }
        }
        decimal fLookup_ID;
        public decimal Lookup_ID
        {
            get { return fLookup_ID; }
            set { SetPropertyValue<decimal>(nameof(Lookup_ID), ref fLookup_ID, value); }
        }
        [Association(@"CD_AddressReferencespl_Country")]
        public XPCollection<CD_Address> CD_Addresss { get { return GetCollection<CD_Address>(nameof(CD_Addresss)); } }
        [Association(@"CD_MainReferencespl_Country")]
        public XPCollection<CD_Main> CD_Mains { get { return GetCollection<CD_Main>(nameof(CD_Mains)); } }
        [Association(@"IM_OptionsReferencespl_Country")]
        public XPCollection<IM_Options> IM_Optionss { get { return GetCollection<IM_Options>(nameof(IM_Optionss)); } }
        [Association(@"RM_MainReferencespl_Country")]
        public XPCollection<RM_Main> RM_Mains { get { return GetCollection<RM_Main>(nameof(RM_Mains)); } }
        [Association(@"RM_MainReferencespl_Country1")]
        public XPCollection<RM_Main> RM_Mains1 { get { return GetCollection<RM_Main>(nameof(RM_Mains1)); } }
        [Association(@"SD_MainReferencespl_Country")]
        public XPCollection<SD_Main> SD_Mains { get { return GetCollection<SD_Main>(nameof(SD_Mains)); } }
        [Association(@"SL_MainReferencespl_Country")]
        public XPCollection<SL_Main> SL_Mains { get { return GetCollection<SL_Main>(nameof(SL_Mains)); } }
        [Association(@"SM_MainReferencespl_Country")]
        public XPCollection<SM_Main> SM_Mains { get { return GetCollection<SM_Main>(nameof(SM_Mains)); } }
        [Association(@"SM_MainReferencespl_Country1")]
        public XPCollection<SM_Main> SM_Mains1 { get { return GetCollection<SM_Main>(nameof(SM_Mains1)); } }
        [Association(@"UD_MainReferencespl_Country")]
        public XPCollection<UD_Main> UD_Mains { get { return GetCollection<UD_Main>(nameof(UD_Mains)); } }
    }

}
