//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class pl_Phone_Type : XPLiteObject
    {
        Guid fpl_Phone_Type_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid pl_Phone_Type_ID
        {
            get { return fpl_Phone_Type_ID; }
            set { SetPropertyValue<Guid>(nameof(pl_Phone_Type_ID), ref fpl_Phone_Type_ID, value); }
        }
        decimal fSort_Order;
        [Indexed(@"Description", Name = @"IX_pl_Phone_Type")]
        [ColumnDbDefaultValue("((0))")]
        public decimal Sort_Order
        {
            get { return fSort_Order; }
            set { SetPropertyValue<decimal>(nameof(Sort_Order), ref fSort_Order, value); }
        }
        string fDescription;
        [Size(50)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fDescription_Short;
        [Size(50)]
        public string Description_Short
        {
            get { return fDescription_Short; }
            set { SetPropertyValue<string>(nameof(Description_Short), ref fDescription_Short, value); }
        }
        string fOptional_Data_Text;
        [Size(50)]
        public string Optional_Data_Text
        {
            get { return fOptional_Data_Text; }
            set { SetPropertyValue<string>(nameof(Optional_Data_Text), ref fOptional_Data_Text, value); }
        }
        int fOptional_Data_Int;
        public int Optional_Data_Int
        {
            get { return fOptional_Data_Int; }
            set { SetPropertyValue<int>(nameof(Optional_Data_Int), ref fOptional_Data_Int, value); }
        }
        int fUser_Select_UI;
        public int User_Select_UI
        {
            get { return fUser_Select_UI; }
            set { SetPropertyValue<int>(nameof(User_Select_UI), ref fUser_Select_UI, value); }
        }
        bool fDeleted_Item;
        public bool Deleted_Item
        {
            get { return fDeleted_Item; }
            set { SetPropertyValue<bool>(nameof(Deleted_Item), ref fDeleted_Item, value); }
        }
        decimal fLookup_ID;
        public decimal Lookup_ID
        {
            get { return fLookup_ID; }
            set { SetPropertyValue<decimal>(nameof(Lookup_ID), ref fLookup_ID, value); }
        }
        [Association(@"CM_ContactsReferencespl_Phone_Type")]
        public XPCollection<CM_Contacts> CM_Contactss { get { return GetCollection<CM_Contacts>(nameof(CM_Contactss)); } }
        [Association(@"SD_MainReferencespl_Phone_Type")]
        public XPCollection<SD_Main> SD_Mains { get { return GetCollection<SD_Main>(nameof(SD_Mains)); } }
        [Association(@"SM_MainReferencespl_Phone_Type")]
        public XPCollection<SM_Main> SM_Mains { get { return GetCollection<SM_Main>(nameof(SM_Mains)); } }
        [Association(@"SM_MainReferencespl_Phone_Type1")]
        public XPCollection<SM_Main> SM_Mains1 { get { return GetCollection<SM_Main>(nameof(SM_Mains1)); } }
        [Association(@"SM_MainReferencespl_Phone_Type2")]
        public XPCollection<SM_Main> SM_Mains2 { get { return GetCollection<SM_Main>(nameof(SM_Mains2)); } }
        [Association(@"SM_MainReferencespl_Phone_Type3")]
        public XPCollection<SM_Main> SM_Mains3 { get { return GetCollection<SM_Main>(nameof(SM_Mains3)); } }
    }

}
