//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class pl_Transaction : XPLiteObject
    {
        Guid fpl_Transaction_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid pl_Transaction_ID
        {
            get { return fpl_Transaction_ID; }
            set { SetPropertyValue<Guid>(nameof(pl_Transaction_ID), ref fpl_Transaction_ID, value); }
        }
        decimal fSort_Order;
        [Indexed(@"Description", Name = @"IX_pl_Transaction")]
        [ColumnDbDefaultValue("((0))")]
        public decimal Sort_Order
        {
            get { return fSort_Order; }
            set { SetPropertyValue<decimal>(nameof(Sort_Order), ref fSort_Order, value); }
        }
        string fDescription;
        [Size(50)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fDescription_Short;
        [Size(50)]
        public string Description_Short
        {
            get { return fDescription_Short; }
            set { SetPropertyValue<string>(nameof(Description_Short), ref fDescription_Short, value); }
        }
        string fOptional_Data_Text;
        [Size(50)]
        public string Optional_Data_Text
        {
            get { return fOptional_Data_Text; }
            set { SetPropertyValue<string>(nameof(Optional_Data_Text), ref fOptional_Data_Text, value); }
        }
        int fOptional_Data_Int;
        public int Optional_Data_Int
        {
            get { return fOptional_Data_Int; }
            set { SetPropertyValue<int>(nameof(Optional_Data_Int), ref fOptional_Data_Int, value); }
        }
        int fUser_Select_UI;
        public int User_Select_UI
        {
            get { return fUser_Select_UI; }
            set { SetPropertyValue<int>(nameof(User_Select_UI), ref fUser_Select_UI, value); }
        }
        bool fDeleted_Item;
        public bool Deleted_Item
        {
            get { return fDeleted_Item; }
            set { SetPropertyValue<bool>(nameof(Deleted_Item), ref fDeleted_Item, value); }
        }
        decimal fLookup_ID;
        public decimal Lookup_ID
        {
            get { return fLookup_ID; }
            set { SetPropertyValue<decimal>(nameof(Lookup_ID), ref fLookup_ID, value); }
        }
        int fTransaction_Direction;
        public int Transaction_Direction
        {
            get { return fTransaction_Direction; }
            set { SetPropertyValue<int>(nameof(Transaction_Direction), ref fTransaction_Direction, value); }
        }
        int fTD_Due_Days_Link;
        public int TD_Due_Days_Link
        {
            get { return fTD_Due_Days_Link; }
            set { SetPropertyValue<int>(nameof(TD_Due_Days_Link), ref fTD_Due_Days_Link, value); }
        }
        int fUnapplied_Key;
        public int Unapplied_Key
        {
            get { return fUnapplied_Key; }
            set { SetPropertyValue<int>(nameof(Unapplied_Key), ref fUnapplied_Key, value); }
        }
        int fApplied_Key;
        public int Applied_Key
        {
            get { return fApplied_Key; }
            set { SetPropertyValue<int>(nameof(Applied_Key), ref fApplied_Key, value); }
        }
        string fUnified_Description;
        [Size(8000)]
        public string Unified_Description
        {
            get { return fUnified_Description; }
            set { SetPropertyValue<string>(nameof(Unified_Description), ref fUnified_Description, value); }
        }
        string fUnified_Description_Short;
        [Size(8000)]
        public string Unified_Description_Short
        {
            get { return fUnified_Description_Short; }
            set { SetPropertyValue<string>(nameof(Unified_Description_Short), ref fUnified_Description_Short, value); }
        }
        [Association(@"AI_ItemsReferencespl_Transaction")]
        public XPCollection<AI_Items> AI_Itemss { get { return GetCollection<AI_Items>(nameof(AI_Itemss)); } }
        [Association(@"AI_MainReferencespl_Transaction")]
        public XPCollection<AI_Main> AI_Mains { get { return GetCollection<AI_Main>(nameof(AI_Mains)); } }
        [Association(@"CM_Credit_TrackingReferencespl_Transaction")]
        public XPCollection<CM_Credit_Tracking> CM_Credit_Trackings { get { return GetCollection<CM_Credit_Tracking>(nameof(CM_Credit_Trackings)); } }
        [Association(@"CM_HistoryReferencespl_Transaction")]
        public XPCollection<CM_History> CM_Historys { get { return GetCollection<CM_History>(nameof(CM_Historys)); } }
        [Association(@"IV_MainReferencespl_Transaction")]
        public XPCollection<IV_Main> IV_Mains { get { return GetCollection<IV_Main>(nameof(IV_Mains)); } }
        [Association(@"OI_ItemsReferencespl_Transaction")]
        public XPCollection<OI_Items> OI_Itemss { get { return GetCollection<OI_Items>(nameof(OI_Itemss)); } }
        [Association(@"OI_MainReferencespl_Transaction")]
        public XPCollection<OI_Main> OI_Mains { get { return GetCollection<OI_Main>(nameof(OI_Mains)); } }
        [Association(@"OI_UnappliedReferencespl_Transaction")]
        public XPCollection<OI_Unapplied> OI_Unapplieds { get { return GetCollection<OI_Unapplied>(nameof(OI_Unapplieds)); } }
    }

}
