//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class PSV_Type : XPLiteObject
    {
        Guid fPSVTypeID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid PSVTypeID
        {
            get { return fPSVTypeID; }
            set { SetPropertyValue<Guid>(nameof(PSVTypeID), ref fPSVTypeID, value); }
        }
        string fDescription;
        [Size(50)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        Guid fParent;
        public Guid Parent
        {
            get { return fParent; }
            set { SetPropertyValue<Guid>(nameof(Parent), ref fParent, value); }
        }
        string fLevel;
        [Size(2000)]
        public string Level
        {
            get { return fLevel; }
            set { SetPropertyValue<string>(nameof(Level), ref fLevel, value); }
        }
        string fTemplate;
        [Size(SizeAttribute.Unlimited)]
        public string Template
        {
            get { return fTemplate; }
            set { SetPropertyValue<string>(nameof(Template), ref fTemplate, value); }
        }
        PSV_Process fProcessID;
        [Association(@"PSV_TypeReferencesPSV_Process")]
        public PSV_Process ProcessID
        {
            get { return fProcessID; }
            set { SetPropertyValue<PSV_Process>(nameof(ProcessID), ref fProcessID, value); }
        }
        [Association(@"PSV_Process_StepsReferencesPSV_Type")]
        public XPCollection<PSV_Process_Steps> PSV_Process_Stepss { get { return GetCollection<PSV_Process_Steps>(nameof(PSV_Process_Stepss)); } }
        [Association(@"PSV_ResponsesReferencesPSV_Type")]
        public XPCollection<PSV_Responses> PSV_Responsess { get { return GetCollection<PSV_Responses>(nameof(PSV_Responsess)); } }
    }

}
