//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class PSV_Templates : XPLiteObject
    {
        Guid fPSVTemplateTypeID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid PSVTemplateTypeID
        {
            get { return fPSVTemplateTypeID; }
            set { SetPropertyValue<Guid>(nameof(PSVTemplateTypeID), ref fPSVTemplateTypeID, value); }
        }
        string fPSVTemplateType;
        [Size(50)]
        public string PSVTemplateType
        {
            get { return fPSVTemplateType; }
            set { SetPropertyValue<string>(nameof(PSVTemplateType), ref fPSVTemplateType, value); }
        }
        string fPSVTemplate;
        [Size(SizeAttribute.Unlimited)]
        public string PSVTemplate
        {
            get { return fPSVTemplate; }
            set { SetPropertyValue<string>(nameof(PSVTemplate), ref fPSVTemplate, value); }
        }
    }

}
