//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class RM_Line_Items_Show : XPLiteObject
    {
        Guid fRM_Line_Items_Show_ID;
        [Key(true)]
        public Guid RM_Line_Items_Show_ID
        {
            get { return fRM_Line_Items_Show_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Line_Items_Show_ID), ref fRM_Line_Items_Show_ID, value); }
        }
        Guid fRM_Main_ID;
        public Guid RM_Main_ID
        {
            get { return fRM_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Main_ID), ref fRM_Main_ID, value); }
        }
        int fLine_Number;
        public int Line_Number
        {
            get { return fLine_Number; }
            set { SetPropertyValue<int>(nameof(Line_Number), ref fLine_Number, value); }
        }
        Guid fItem_Number;
        public Guid Item_Number
        {
            get { return fItem_Number; }
            set { SetPropertyValue<Guid>(nameof(Item_Number), ref fItem_Number, value); }
        }
        string fUPC;
        [Size(12)]
        public string UPC
        {
            get { return fUPC; }
            set { SetPropertyValue<string>(nameof(UPC), ref fUPC, value); }
        }
        Guid fUnit;
        public Guid Unit
        {
            get { return fUnit; }
            set { SetPropertyValue<Guid>(nameof(Unit), ref fUnit, value); }
        }
        int fSell_BL;
        public int Sell_BL
        {
            get { return fSell_BL; }
            set { SetPropertyValue<int>(nameof(Sell_BL), ref fSell_BL, value); }
        }
        Guid fAction;
        public Guid Action
        {
            get { return fAction; }
            set { SetPropertyValue<Guid>(nameof(Action), ref fAction, value); }
        }
        Guid fAction_Credit_Memo;
        public Guid Action_Credit_Memo
        {
            get { return fAction_Credit_Memo; }
            set { SetPropertyValue<Guid>(nameof(Action_Credit_Memo), ref fAction_Credit_Memo, value); }
        }
        int fQTY_Ordered;
        public int QTY_Ordered
        {
            get { return fQTY_Ordered; }
            set { SetPropertyValue<int>(nameof(QTY_Ordered), ref fQTY_Ordered, value); }
        }
        int fQTY_On_Hold;
        public int QTY_On_Hold
        {
            get { return fQTY_On_Hold; }
            set { SetPropertyValue<int>(nameof(QTY_On_Hold), ref fQTY_On_Hold, value); }
        }
        int fQTY_Allocated;
        public int QTY_Allocated
        {
            get { return fQTY_Allocated; }
            set { SetPropertyValue<int>(nameof(QTY_Allocated), ref fQTY_Allocated, value); }
        }
        int fQTY_Shipped;
        public int QTY_Shipped
        {
            get { return fQTY_Shipped; }
            set { SetPropertyValue<int>(nameof(QTY_Shipped), ref fQTY_Shipped, value); }
        }
        int fQTY_Credited;
        public int QTY_Credited
        {
            get { return fQTY_Credited; }
            set { SetPropertyValue<int>(nameof(QTY_Credited), ref fQTY_Credited, value); }
        }
        int fQTY_Returned;
        public int QTY_Returned
        {
            get { return fQTY_Returned; }
            set { SetPropertyValue<int>(nameof(QTY_Returned), ref fQTY_Returned, value); }
        }
        decimal fPrice;
        public decimal Price
        {
            get { return fPrice; }
            set { SetPropertyValue<decimal>(nameof(Price), ref fPrice, value); }
        }
        decimal fCost;
        public decimal Cost
        {
            get { return fCost; }
            set { SetPropertyValue<decimal>(nameof(Cost), ref fCost, value); }
        }
        int fCommission;
        public int Commission
        {
            get { return fCommission; }
            set { SetPropertyValue<int>(nameof(Commission), ref fCommission, value); }
        }
        int fPrice_Type;
        public int Price_Type
        {
            get { return fPrice_Type; }
            set { SetPropertyValue<int>(nameof(Price_Type), ref fPrice_Type, value); }
        }
        int fCommission_Type;
        public int Commission_Type
        {
            get { return fCommission_Type; }
            set { SetPropertyValue<int>(nameof(Commission_Type), ref fCommission_Type, value); }
        }
        Guid fCommission_Split;
        public Guid Commission_Split
        {
            get { return fCommission_Split; }
            set { SetPropertyValue<Guid>(nameof(Commission_Split), ref fCommission_Split, value); }
        }
        bool fDiscount_Line;
        public bool Discount_Line
        {
            get { return fDiscount_Line; }
            set { SetPropertyValue<bool>(nameof(Discount_Line), ref fDiscount_Line, value); }
        }
        int fDiscount_Percent;
        public int Discount_Percent
        {
            get { return fDiscount_Percent; }
            set { SetPropertyValue<int>(nameof(Discount_Percent), ref fDiscount_Percent, value); }
        }
        Guid fIP_Main_ID;
        public Guid IP_Main_ID
        {
            get { return fIP_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(IP_Main_ID), ref fIP_Main_ID, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
    }

}
