//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class RM_Main : XPLiteObject
    {
        Guid fRM_Main_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid RM_Main_ID
        {
            get { return fRM_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Main_ID), ref fRM_Main_ID, value); }
        }
        decimal fOrder_Number;
        public decimal Order_Number
        {
            get { return fOrder_Number; }
            set { SetPropertyValue<decimal>(nameof(Order_Number), ref fOrder_Number, value); }
        }
        string foldOrder_Number;
        [Indexed(Name = @"IX_RM_MAIN")]
        [Size(25)]
        public string oldOrder_Number
        {
            get { return foldOrder_Number; }
            set { SetPropertyValue<string>(nameof(oldOrder_Number), ref foldOrder_Number, value); }
        }
        string fNew_Order_Number;
        [Size(25)]
        public string New_Order_Number
        {
            get { return fNew_Order_Number; }
            set { SetPropertyValue<string>(nameof(New_Order_Number), ref fNew_Order_Number, value); }
        }
        string fGift_Show_Number;
        [Size(25)]
        public string Gift_Show_Number
        {
            get { return fGift_Show_Number; }
            set { SetPropertyValue<string>(nameof(Gift_Show_Number), ref fGift_Show_Number, value); }
        }
        pl_Source fOrder_Source;
        [Association(@"RM_MainReferencespl_Source")]
        public pl_Source Order_Source
        {
            get { return fOrder_Source; }
            set { SetPropertyValue<pl_Source>(nameof(Order_Source), ref fOrder_Source, value); }
        }
        pl_Order_Type fOrder_Type;
        [Association(@"RM_MainReferencespl_Order_Type")]
        public pl_Order_Type Order_Type
        {
            get { return fOrder_Type; }
            set { SetPropertyValue<pl_Order_Type>(nameof(Order_Type), ref fOrder_Type, value); }
        }
        string fWho_Placed_Order;
        [Size(50)]
        public string Who_Placed_Order
        {
            get { return fWho_Placed_Order; }
            set { SetPropertyValue<string>(nameof(Who_Placed_Order), ref fWho_Placed_Order, value); }
        }
        string fWho_Phone_Number;
        [Size(25)]
        public string Who_Phone_Number
        {
            get { return fWho_Phone_Number; }
            set { SetPropertyValue<string>(nameof(Who_Phone_Number), ref fWho_Phone_Number, value); }
        }
        string fWho_Phone_Extension;
        [Size(10)]
        public string Who_Phone_Extension
        {
            get { return fWho_Phone_Extension; }
            set { SetPropertyValue<string>(nameof(Who_Phone_Extension), ref fWho_Phone_Extension, value); }
        }
        pl_Title fTitle;
        [Association(@"RM_MainReferencespl_Title")]
        public pl_Title Title
        {
            get { return fTitle; }
            set { SetPropertyValue<pl_Title>(nameof(Title), ref fTitle, value); }
        }
        pl_Account_Priority fAccount_Priority;
        [Association(@"RM_MainReferencespl_Account_Priority")]
        public pl_Account_Priority Account_Priority
        {
            get { return fAccount_Priority; }
            set { SetPropertyValue<pl_Account_Priority>(nameof(Account_Priority), ref fAccount_Priority, value); }
        }
        pl_Account_Manager fAccount_Manager;
        [Association(@"RM_MainReferencespl_Account_Manager")]
        public pl_Account_Manager Account_Manager
        {
            get { return fAccount_Manager; }
            set { SetPropertyValue<pl_Account_Manager>(nameof(Account_Manager), ref fAccount_Manager, value); }
        }
        CM_Main fCM_Main_ID;
        [Association(@"RM_MainReferencesCM_Main")]
        public CM_Main CM_Main_ID
        {
            get { return fCM_Main_ID; }
            set { SetPropertyValue<CM_Main>(nameof(CM_Main_ID), ref fCM_Main_ID, value); }
        }
        string fBillTo_Account_Number;
        [Size(20)]
        public string BillTo_Account_Number
        {
            get { return fBillTo_Account_Number; }
            set { SetPropertyValue<string>(nameof(BillTo_Account_Number), ref fBillTo_Account_Number, value); }
        }
        string fBillTo_Name;
        [Size(50)]
        public string BillTo_Name
        {
            get { return fBillTo_Name; }
            set { SetPropertyValue<string>(nameof(BillTo_Name), ref fBillTo_Name, value); }
        }
        string fBillTo_Address;
        [Size(50)]
        public string BillTo_Address
        {
            get { return fBillTo_Address; }
            set { SetPropertyValue<string>(nameof(BillTo_Address), ref fBillTo_Address, value); }
        }
        string fBillTo_Overflow;
        [Size(50)]
        public string BillTo_Overflow
        {
            get { return fBillTo_Overflow; }
            set { SetPropertyValue<string>(nameof(BillTo_Overflow), ref fBillTo_Overflow, value); }
        }
        string fBillTo_City;
        [Size(50)]
        public string BillTo_City
        {
            get { return fBillTo_City; }
            set { SetPropertyValue<string>(nameof(BillTo_City), ref fBillTo_City, value); }
        }
        string fBillTo_State;
        [Size(2)]
        public string BillTo_State
        {
            get { return fBillTo_State; }
            set { SetPropertyValue<string>(nameof(BillTo_State), ref fBillTo_State, value); }
        }
        string fBillTo_Zip_Code;
        [Size(9)]
        public string BillTo_Zip_Code
        {
            get { return fBillTo_Zip_Code; }
            set { SetPropertyValue<string>(nameof(BillTo_Zip_Code), ref fBillTo_Zip_Code, value); }
        }
        int fBillTo_Zone;
        public int BillTo_Zone
        {
            get { return fBillTo_Zone; }
            set { SetPropertyValue<int>(nameof(BillTo_Zone), ref fBillTo_Zone, value); }
        }
        pl_Country fBillTo_Country;
        [Association(@"RM_MainReferencespl_Country")]
        public pl_Country BillTo_Country
        {
            get { return fBillTo_Country; }
            set { SetPropertyValue<pl_Country>(nameof(BillTo_Country), ref fBillTo_Country, value); }
        }
        pl_Address_Type fBillTo_Address_Type;
        [Association(@"RM_MainReferencespl_Address_Type")]
        public pl_Address_Type BillTo_Address_Type
        {
            get { return fBillTo_Address_Type; }
            set { SetPropertyValue<pl_Address_Type>(nameof(BillTo_Address_Type), ref fBillTo_Address_Type, value); }
        }
        int fBillTo_Ship_Type;
        public int BillTo_Ship_Type
        {
            get { return fBillTo_Ship_Type; }
            set { SetPropertyValue<int>(nameof(BillTo_Ship_Type), ref fBillTo_Ship_Type, value); }
        }
        decimal fnew_ShipTo_Number;
        public decimal new_ShipTo_Number
        {
            get { return fnew_ShipTo_Number; }
            set { SetPropertyValue<decimal>(nameof(new_ShipTo_Number), ref fnew_ShipTo_Number, value); }
        }
        CM_Main fShipTo_Account_Number;
        [Association(@"RM_MainReferencesCM_Main1")]
        public CM_Main ShipTo_Account_Number
        {
            get { return fShipTo_Account_Number; }
            set { SetPropertyValue<CM_Main>(nameof(ShipTo_Account_Number), ref fShipTo_Account_Number, value); }
        }
        string fShipTo_Name;
        [Size(50)]
        public string ShipTo_Name
        {
            get { return fShipTo_Name; }
            set { SetPropertyValue<string>(nameof(ShipTo_Name), ref fShipTo_Name, value); }
        }
        string fShipTo_Address;
        [Size(50)]
        public string ShipTo_Address
        {
            get { return fShipTo_Address; }
            set { SetPropertyValue<string>(nameof(ShipTo_Address), ref fShipTo_Address, value); }
        }
        string fShipTo_Overflow;
        [Size(50)]
        public string ShipTo_Overflow
        {
            get { return fShipTo_Overflow; }
            set { SetPropertyValue<string>(nameof(ShipTo_Overflow), ref fShipTo_Overflow, value); }
        }
        string fShipTo_City;
        [Size(50)]
        public string ShipTo_City
        {
            get { return fShipTo_City; }
            set { SetPropertyValue<string>(nameof(ShipTo_City), ref fShipTo_City, value); }
        }
        string fShipTo_State;
        [Size(2)]
        public string ShipTo_State
        {
            get { return fShipTo_State; }
            set { SetPropertyValue<string>(nameof(ShipTo_State), ref fShipTo_State, value); }
        }
        string fShipTo_Zip_Code;
        [Size(9)]
        public string ShipTo_Zip_Code
        {
            get { return fShipTo_Zip_Code; }
            set { SetPropertyValue<string>(nameof(ShipTo_Zip_Code), ref fShipTo_Zip_Code, value); }
        }
        int fShipTo_Zone;
        public int ShipTo_Zone
        {
            get { return fShipTo_Zone; }
            set { SetPropertyValue<int>(nameof(ShipTo_Zone), ref fShipTo_Zone, value); }
        }
        pl_Country fShipTo_Country;
        [Association(@"RM_MainReferencespl_Country1")]
        public pl_Country ShipTo_Country
        {
            get { return fShipTo_Country; }
            set { SetPropertyValue<pl_Country>(nameof(ShipTo_Country), ref fShipTo_Country, value); }
        }
        pl_Address_Type fShipTo_Address_Type;
        [Association(@"RM_MainReferencespl_Address_Type1")]
        public pl_Address_Type ShipTo_Address_Type
        {
            get { return fShipTo_Address_Type; }
            set { SetPropertyValue<pl_Address_Type>(nameof(ShipTo_Address_Type), ref fShipTo_Address_Type, value); }
        }
        int fShipTo_Ship_Type;
        public int ShipTo_Ship_Type
        {
            get { return fShipTo_Ship_Type; }
            set { SetPropertyValue<int>(nameof(ShipTo_Ship_Type), ref fShipTo_Ship_Type, value); }
        }
        string fAccount_Number_ShipTo;
        [Size(25)]
        public string Account_Number_ShipTo
        {
            get { return fAccount_Number_ShipTo; }
            set { SetPropertyValue<string>(nameof(Account_Number_ShipTo), ref fAccount_Number_ShipTo, value); }
        }
        bool fUse_Manual_Address;
        public bool Use_Manual_Address
        {
            get { return fUse_Manual_Address; }
            set { SetPropertyValue<bool>(nameof(Use_Manual_Address), ref fUse_Manual_Address, value); }
        }
        pl_Order_Status fOrder_Status;
        [Association(@"RM_MainReferencespl_Order_Status")]
        public pl_Order_Status Order_Status
        {
            get { return fOrder_Status; }
            set { SetPropertyValue<pl_Order_Status>(nameof(Order_Status), ref fOrder_Status, value); }
        }
        string fComment;
        [Size(200)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        pl_Reason_for_Hold fHold;
        [Association(@"RM_MainReferencespl_Reason_for_Hold")]
        public pl_Reason_for_Hold Hold
        {
            get { return fHold; }
            set { SetPropertyValue<pl_Reason_for_Hold>(nameof(Hold), ref fHold, value); }
        }
        DateTime fCreated_Date_Time;
        [Indexed(Name = @"IX_RM_MAIN_2")]
        public DateTime Created_Date_Time
        {
            get { return fCreated_Date_Time; }
            set { SetPropertyValue<DateTime>(nameof(Created_Date_Time), ref fCreated_Date_Time, value); }
        }
        pl_Reason_for_Hold fHold_Reason;
        [Association(@"RM_MainReferencespl_Reason_for_Hold1")]
        public pl_Reason_for_Hold Hold_Reason
        {
            get { return fHold_Reason; }
            set { SetPropertyValue<pl_Reason_for_Hold>(nameof(Hold_Reason), ref fHold_Reason, value); }
        }
        bool fPre_Pay_ReBill;
        public bool Pre_Pay_ReBill
        {
            get { return fPre_Pay_ReBill; }
            set { SetPropertyValue<bool>(nameof(Pre_Pay_ReBill), ref fPre_Pay_ReBill, value); }
        }
        bool fDelete_Flag;
        public bool Delete_Flag
        {
            get { return fDelete_Flag; }
            set { SetPropertyValue<bool>(nameof(Delete_Flag), ref fDelete_Flag, value); }
        }
        Guid fCancel_OrderStatus_Restore;
        public Guid Cancel_OrderStatus_Restore
        {
            get { return fCancel_OrderStatus_Restore; }
            set { SetPropertyValue<Guid>(nameof(Cancel_OrderStatus_Restore), ref fCancel_OrderStatus_Restore, value); }
        }
        string fShipTo_Account_Number_Suffex;
        [Size(25)]
        public string ShipTo_Account_Number_Suffex
        {
            get { return fShipTo_Account_Number_Suffex; }
            set { SetPropertyValue<string>(nameof(ShipTo_Account_Number_Suffex), ref fShipTo_Account_Number_Suffex, value); }
        }
        DateTime fIdle_Mark;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime Idle_Mark
        {
            get { return fIdle_Mark; }
            set { SetPropertyValue<DateTime>(nameof(Idle_Mark), ref fIdle_Mark, value); }
        }
        Guid fBillTo_Address_ShipType;
        public Guid BillTo_Address_ShipType
        {
            get { return fBillTo_Address_ShipType; }
            set { SetPropertyValue<Guid>(nameof(BillTo_Address_ShipType), ref fBillTo_Address_ShipType, value); }
        }
        Guid fShipTo_Address_ShipType;
        public Guid ShipTo_Address_ShipType
        {
            get { return fShipTo_Address_ShipType; }
            set { SetPropertyValue<Guid>(nameof(ShipTo_Address_ShipType), ref fShipTo_Address_ShipType, value); }
        }
        Guid fManual_Address_ShipType;
        public Guid Manual_Address_ShipType
        {
            get { return fManual_Address_ShipType; }
            set { SetPropertyValue<Guid>(nameof(Manual_Address_ShipType), ref fManual_Address_ShipType, value); }
        }
        string fatest;
        [Size(50)]
        public string atest
        {
            get { return fatest; }
            set { SetPropertyValue<string>(nameof(atest), ref fatest, value); }
        }
        string fNew_Order_Number_Short;
        [Size(25)]
        public string New_Order_Number_Short
        {
            get { return fNew_Order_Number_Short; }
            set { SetPropertyValue<string>(nameof(New_Order_Number_Short), ref fNew_Order_Number_Short, value); }
        }
        string fOld_Order_Number_Long;
        [Size(25)]
        public string Old_Order_Number_Long
        {
            get { return fOld_Order_Number_Long; }
            set { SetPropertyValue<string>(nameof(Old_Order_Number_Long), ref fOld_Order_Number_Long, value); }
        }
        Guid fOrder_ShipTo_ID;
        public Guid Order_ShipTo_ID
        {
            get { return fOrder_ShipTo_ID; }
            set { SetPropertyValue<Guid>(nameof(Order_ShipTo_ID), ref fOrder_ShipTo_ID, value); }
        }
        string fOrder_Number_fmt;
        [Size(25)]
        public string Order_Number_fmt
        {
            get { return fOrder_Number_fmt; }
            set { SetPropertyValue<string>(nameof(Order_Number_fmt), ref fOrder_Number_fmt, value); }
        }
        string fOrder_Number_Body;
        [Size(6)]
        public string Order_Number_Body
        {
            get { return fOrder_Number_Body; }
            set { SetPropertyValue<string>(nameof(Order_Number_Body), ref fOrder_Number_Body, value); }
        }
        bool fDelete_Flag_Check;
        public bool Delete_Flag_Check
        {
            get { return fDelete_Flag_Check; }
            set { SetPropertyValue<bool>(nameof(Delete_Flag_Check), ref fDelete_Flag_Check, value); }
        }
        bool fBack_Order_Flag;
        public bool Back_Order_Flag
        {
            get { return fBack_Order_Flag; }
            set { SetPropertyValue<bool>(nameof(Back_Order_Flag), ref fBack_Order_Flag, value); }
        }
        int fOrder_Location;
        public int Order_Location
        {
            get { return fOrder_Location; }
            set { SetPropertyValue<int>(nameof(Order_Location), ref fOrder_Location, value); }
        }
        string fBillTo_Address_5_Line;
        [Size(1000)]
        public string BillTo_Address_5_Line
        {
            get { return fBillTo_Address_5_Line; }
            set { SetPropertyValue<string>(nameof(BillTo_Address_5_Line), ref fBillTo_Address_5_Line, value); }
        }
        string fShipTo_Address_5_Line;
        [Size(1000)]
        public string ShipTo_Address_5_Line
        {
            get { return fShipTo_Address_5_Line; }
            set { SetPropertyValue<string>(nameof(ShipTo_Address_5_Line), ref fShipTo_Address_5_Line, value); }
        }
        [Association(@"IV_MainReferencesRM_Main")]
        public XPCollection<IV_Main> IV_Mains { get { return GetCollection<IV_Main>(nameof(IV_Mains)); } }
        [Association(@"OI_UnappliedReferencesRM_Main")]
        public XPCollection<OI_Unapplied> OI_Unapplieds { get { return GetCollection<OI_Unapplied>(nameof(OI_Unapplieds)); } }
        [Association(@"RM_Line_ItemsReferencesRM_Main")]
        public XPCollection<RM_Line_Items> RM_Line_Itemss { get { return GetCollection<RM_Line_Items>(nameof(RM_Line_Itemss)); } }
        [Association(@"RM_OptionsReferencesRM_Main")]
        public XPCollection<RM_Options> RM_Optionss { get { return GetCollection<RM_Options>(nameof(RM_Optionss)); } }
        [Association(@"RM_ProblemsReferencesRM_Main")]
        public XPCollection<RM_Problems> RM_Problemss { get { return GetCollection<RM_Problems>(nameof(RM_Problemss)); } }
        [Association(@"RM_ProcessReferencesRM_Main")]
        public XPCollection<RM_Process> RM_Processs { get { return GetCollection<RM_Process>(nameof(RM_Processs)); } }
        [Association(@"WU_ERRORSReferencesRM_Main")]
        public XPCollection<WU_ERRORS> WU_ERRORSs { get { return GetCollection<WU_ERRORS>(nameof(WU_ERRORSs)); } }
    }

}
