//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class RM_Options : XPLiteObject
    {
        Guid fRM_Options_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid RM_Options_ID
        {
            get { return fRM_Options_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Options_ID), ref fRM_Options_ID, value); }
        }
        RM_Main fRM_Main_ID;
        [Association(@"RM_OptionsReferencesRM_Main")]
        public RM_Main RM_Main_ID
        {
            get { return fRM_Main_ID; }
            set { SetPropertyValue<RM_Main>(nameof(RM_Main_ID), ref fRM_Main_ID, value); }
        }
        TD_Main fTerms;
        [Association(@"RM_OptionsReferencesTD_Main")]
        public TD_Main Terms
        {
            get { return fTerms; }
            set { SetPropertyValue<TD_Main>(nameof(Terms), ref fTerms, value); }
        }
        pl_Ship_Via fShip_Via;
        [Association(@"RM_OptionsReferencespl_Ship_Via")]
        public pl_Ship_Via Ship_Via
        {
            get { return fShip_Via; }
            set { SetPropertyValue<pl_Ship_Via>(nameof(Ship_Via), ref fShip_Via, value); }
        }
        string fPO_Number;
        [Size(20)]
        public string PO_Number
        {
            get { return fPO_Number; }
            set { SetPropertyValue<string>(nameof(PO_Number), ref fPO_Number, value); }
        }
        string fInvoice_Number;
        [Indexed(Name = @"IX_RM_Options_Invoice_Number")]
        [Size(20)]
        public string Invoice_Number
        {
            get { return fInvoice_Number; }
            set { SetPropertyValue<string>(nameof(Invoice_Number), ref fInvoice_Number, value); }
        }
        string fCredit_Memo_To_Invoice_Number;
        [Indexed(Name = @"IX_RM_Options_Credit_Memo_To_Invoice_Number")]
        [Size(20)]
        public string Credit_Memo_To_Invoice_Number
        {
            get { return fCredit_Memo_To_Invoice_Number; }
            set { SetPropertyValue<string>(nameof(Credit_Memo_To_Invoice_Number), ref fCredit_Memo_To_Invoice_Number, value); }
        }
        string fRebill_Invoice_Number;
        [Size(20)]
        public string Rebill_Invoice_Number
        {
            get { return fRebill_Invoice_Number; }
            set { SetPropertyValue<string>(nameof(Rebill_Invoice_Number), ref fRebill_Invoice_Number, value); }
        }
        decimal fOrder_Amount;
        public decimal Order_Amount
        {
            get { return fOrder_Amount; }
            set { SetPropertyValue<decimal>(nameof(Order_Amount), ref fOrder_Amount, value); }
        }
        decimal fOrder_Cost;
        public decimal Order_Cost
        {
            get { return fOrder_Cost; }
            set { SetPropertyValue<decimal>(nameof(Order_Cost), ref fOrder_Cost, value); }
        }
        decimal fOrder_Amount_Shipped;
        public decimal Order_Amount_Shipped
        {
            get { return fOrder_Amount_Shipped; }
            set { SetPropertyValue<decimal>(nameof(Order_Amount_Shipped), ref fOrder_Amount_Shipped, value); }
        }
        decimal fOrder_Shipped_Cost;
        public decimal Order_Shipped_Cost
        {
            get { return fOrder_Shipped_Cost; }
            set { SetPropertyValue<decimal>(nameof(Order_Shipped_Cost), ref fOrder_Shipped_Cost, value); }
        }
        decimal fFreight_Amount;
        public decimal Freight_Amount
        {
            get { return fFreight_Amount; }
            set { SetPropertyValue<decimal>(nameof(Freight_Amount), ref fFreight_Amount, value); }
        }
        decimal fInsurance_Amount;
        public decimal Insurance_Amount
        {
            get { return fInsurance_Amount; }
            set { SetPropertyValue<decimal>(nameof(Insurance_Amount), ref fInsurance_Amount, value); }
        }
        decimal fHandling_Charge;
        public decimal Handling_Charge
        {
            get { return fHandling_Charge; }
            set { SetPropertyValue<decimal>(nameof(Handling_Charge), ref fHandling_Charge, value); }
        }
        decimal fTotal_Order_Amount;
        public decimal Total_Order_Amount
        {
            get { return fTotal_Order_Amount; }
            set { SetPropertyValue<decimal>(nameof(Total_Order_Amount), ref fTotal_Order_Amount, value); }
        }
        decimal fTotal_Order_Amount_Shipped;
        public decimal Total_Order_Amount_Shipped
        {
            get { return fTotal_Order_Amount_Shipped; }
            set { SetPropertyValue<decimal>(nameof(Total_Order_Amount_Shipped), ref fTotal_Order_Amount_Shipped, value); }
        }
        DateTime fRequest_Date;
        public DateTime Request_Date
        {
            get { return fRequest_Date; }
            set { SetPropertyValue<DateTime>(nameof(Request_Date), ref fRequest_Date, value); }
        }
        DateTime fCancel_Date;
        public DateTime Cancel_Date
        {
            get { return fCancel_Date; }
            set { SetPropertyValue<DateTime>(nameof(Cancel_Date), ref fCancel_Date, value); }
        }
        SM_Main fSalesman_Number_1;
        [Association(@"RM_OptionsReferencesSM_Main")]
        public SM_Main Salesman_Number_1
        {
            get { return fSalesman_Number_1; }
            set { SetPropertyValue<SM_Main>(nameof(Salesman_Number_1), ref fSalesman_Number_1, value); }
        }
        SM_Main fSalesman_Number_2;
        [Association(@"RM_OptionsReferencesSM_Main1")]
        public SM_Main Salesman_Number_2
        {
            get { return fSalesman_Number_2; }
            set { SetPropertyValue<SM_Main>(nameof(Salesman_Number_2), ref fSalesman_Number_2, value); }
        }
        pl_Commission_Split fCommission_Split;
        [Association(@"RM_OptionsReferencespl_Commission_Split")]
        public pl_Commission_Split Commission_Split
        {
            get { return fCommission_Split; }
            set { SetPropertyValue<pl_Commission_Split>(nameof(Commission_Split), ref fCommission_Split, value); }
        }
        decimal fCommission_Amount;
        public decimal Commission_Amount
        {
            get { return fCommission_Amount; }
            set { SetPropertyValue<decimal>(nameof(Commission_Amount), ref fCommission_Amount, value); }
        }
        pl_Discount_Type fDiscount;
        [Association(@"RM_OptionsReferencespl_Discount_Type")]
        public pl_Discount_Type Discount
        {
            get { return fDiscount; }
            set { SetPropertyValue<pl_Discount_Type>(nameof(Discount), ref fDiscount, value); }
        }
        int fDiscount_Percent;
        public int Discount_Percent
        {
            get { return fDiscount_Percent; }
            set { SetPropertyValue<int>(nameof(Discount_Percent), ref fDiscount_Percent, value); }
        }
        decimal fDiscount_Amount;
        public decimal Discount_Amount
        {
            get { return fDiscount_Amount; }
            set { SetPropertyValue<decimal>(nameof(Discount_Amount), ref fDiscount_Amount, value); }
        }
        bool fCredit_Pending;
        public bool Credit_Pending
        {
            get { return fCredit_Pending; }
            set { SetPropertyValue<bool>(nameof(Credit_Pending), ref fCredit_Pending, value); }
        }
        bool fDo_Not_Ship;
        public bool Do_Not_Ship
        {
            get { return fDo_Not_Ship; }
            set { SetPropertyValue<bool>(nameof(Do_Not_Ship), ref fDo_Not_Ship, value); }
        }
        pl_Credit_Status fCredit_Status;
        [Association(@"RM_OptionsReferencespl_Credit_Status")]
        public pl_Credit_Status Credit_Status
        {
            get { return fCredit_Status; }
            set { SetPropertyValue<pl_Credit_Status>(nameof(Credit_Status), ref fCredit_Status, value); }
        }
        bool fAllow_Dating;
        public bool Allow_Dating
        {
            get { return fAllow_Dating; }
            set { SetPropertyValue<bool>(nameof(Allow_Dating), ref fAllow_Dating, value); }
        }
        bool fOrder_Acknowledgement;
        public bool Order_Acknowledgement
        {
            get { return fOrder_Acknowledgement; }
            set { SetPropertyValue<bool>(nameof(Order_Acknowledgement), ref fOrder_Acknowledgement, value); }
        }
        DateTime fDate_Acknowledgement_Printed;
        public DateTime Date_Acknowledgement_Printed
        {
            get { return fDate_Acknowledgement_Printed; }
            set { SetPropertyValue<DateTime>(nameof(Date_Acknowledgement_Printed), ref fDate_Acknowledgement_Printed, value); }
        }
        bool fNo_Partial_Ship;
        public bool No_Partial_Ship
        {
            get { return fNo_Partial_Ship; }
            set { SetPropertyValue<bool>(nameof(No_Partial_Ship), ref fNo_Partial_Ship, value); }
        }
        bool fAccept_Backorders;
        public bool Accept_Backorders
        {
            get { return fAccept_Backorders; }
            set { SetPropertyValue<bool>(nameof(Accept_Backorders), ref fAccept_Backorders, value); }
        }
        bool fAuto_OE_Minimums;
        public bool Auto_OE_Minimums
        {
            get { return fAuto_OE_Minimums; }
            set { SetPropertyValue<bool>(nameof(Auto_OE_Minimums), ref fAuto_OE_Minimums, value); }
        }
        int fUse_Price_Set;
        public int Use_Price_Set
        {
            get { return fUse_Price_Set; }
            set { SetPropertyValue<int>(nameof(Use_Price_Set), ref fUse_Price_Set, value); }
        }
        bool fCall_Before_Shipping;
        public bool Call_Before_Shipping
        {
            get { return fCall_Before_Shipping; }
            set { SetPropertyValue<bool>(nameof(Call_Before_Shipping), ref fCall_Before_Shipping, value); }
        }
        bool fCall_Before_Delivery;
        public bool Call_Before_Delivery
        {
            get { return fCall_Before_Delivery; }
            set { SetPropertyValue<bool>(nameof(Call_Before_Delivery), ref fCall_Before_Delivery, value); }
        }
        bool fCall_Before_Shipping_BOs;
        public bool Call_Before_Shipping_BOs
        {
            get { return fCall_Before_Shipping_BOs; }
            set { SetPropertyValue<bool>(nameof(Call_Before_Shipping_BOs), ref fCall_Before_Shipping_BOs, value); }
        }
        bool fPickup_Orders_Only;
        public bool Pickup_Orders_Only
        {
            get { return fPickup_Orders_Only; }
            set { SetPropertyValue<bool>(nameof(Pickup_Orders_Only), ref fPickup_Orders_Only, value); }
        }
        bool fPrePay_Rebill_Freight;
        public bool PrePay_Rebill_Freight
        {
            get { return fPrePay_Rebill_Freight; }
            set { SetPropertyValue<bool>(nameof(PrePay_Rebill_Freight), ref fPrePay_Rebill_Freight, value); }
        }
        bool fModified_Status;
        public bool Modified_Status
        {
            get { return fModified_Status; }
            set { SetPropertyValue<bool>(nameof(Modified_Status), ref fModified_Status, value); }
        }
        Guid fTD_Main_ID;
        public Guid TD_Main_ID
        {
            get { return fTD_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(TD_Main_ID), ref fTD_Main_ID, value); }
        }
        Guid fSM_Main_ID;
        public Guid SM_Main_ID
        {
            get { return fSM_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(SM_Main_ID), ref fSM_Main_ID, value); }
        }
        Guid fSM_Main_ID_1;
        public Guid SM_Main_ID_1
        {
            get { return fSM_Main_ID_1; }
            set { SetPropertyValue<Guid>(nameof(SM_Main_ID_1), ref fSM_Main_ID_1, value); }
        }
        pl_Ship_Via fRestore_Ship_Via;
        [Association(@"RM_OptionsReferencespl_Ship_Via1")]
        public pl_Ship_Via Restore_Ship_Via
        {
            get { return fRestore_Ship_Via; }
            set { SetPropertyValue<pl_Ship_Via>(nameof(Restore_Ship_Via), ref fRestore_Ship_Via, value); }
        }
        bool fHold_Flag;
        public bool Hold_Flag
        {
            get { return fHold_Flag; }
            set { SetPropertyValue<bool>(nameof(Hold_Flag), ref fHold_Flag, value); }
        }
        pl_Reason_for_Hold fHold_Placed_Reason_ID;
        [Association(@"RM_OptionsReferencespl_Reason_for_Hold")]
        public pl_Reason_for_Hold Hold_Placed_Reason_ID
        {
            get { return fHold_Placed_Reason_ID; }
            set { SetPropertyValue<pl_Reason_for_Hold>(nameof(Hold_Placed_Reason_ID), ref fHold_Placed_Reason_ID, value); }
        }
        UD_Main fHold_Placed_User_ID;
        [Association(@"RM_OptionsReferencesUD_Main")]
        public UD_Main Hold_Placed_User_ID
        {
            get { return fHold_Placed_User_ID; }
            set { SetPropertyValue<UD_Main>(nameof(Hold_Placed_User_ID), ref fHold_Placed_User_ID, value); }
        }
        DateTime fHold_Placed_DateTime;
        public DateTime Hold_Placed_DateTime
        {
            get { return fHold_Placed_DateTime; }
            set { SetPropertyValue<DateTime>(nameof(Hold_Placed_DateTime), ref fHold_Placed_DateTime, value); }
        }
        pl_Reason_for_Hold fHold_Removed_Reason_ID;
        [Association(@"RM_OptionsReferencespl_Reason_for_Hold1")]
        public pl_Reason_for_Hold Hold_Removed_Reason_ID
        {
            get { return fHold_Removed_Reason_ID; }
            set { SetPropertyValue<pl_Reason_for_Hold>(nameof(Hold_Removed_Reason_ID), ref fHold_Removed_Reason_ID, value); }
        }
        UD_Main fHold_Removed_User_ID;
        [Association(@"RM_OptionsReferencesUD_Main1")]
        public UD_Main Hold_Removed_User_ID
        {
            get { return fHold_Removed_User_ID; }
            set { SetPropertyValue<UD_Main>(nameof(Hold_Removed_User_ID), ref fHold_Removed_User_ID, value); }
        }
        DateTime fHold_Removed_DateTime;
        public DateTime Hold_Removed_DateTime
        {
            get { return fHold_Removed_DateTime; }
            set { SetPropertyValue<DateTime>(nameof(Hold_Removed_DateTime), ref fHold_Removed_DateTime, value); }
        }
        bool fHold_Flag_Check;
        public bool Hold_Flag_Check
        {
            get { return fHold_Flag_Check; }
            set { SetPropertyValue<bool>(nameof(Hold_Flag_Check), ref fHold_Flag_Check, value); }
        }
        int fHold_Placed_Valid;
        public int Hold_Placed_Valid
        {
            get { return fHold_Placed_Valid; }
            set { SetPropertyValue<int>(nameof(Hold_Placed_Valid), ref fHold_Placed_Valid, value); }
        }
        string fAlpha;
        [Size(10)]
        public string Alpha
        {
            get { return fAlpha; }
            set { SetPropertyValue<string>(nameof(Alpha), ref fAlpha, value); }
        }
        int fWhat_Order_Type;
        public int What_Order_Type
        {
            get { return fWhat_Order_Type; }
            set { SetPropertyValue<int>(nameof(What_Order_Type), ref fWhat_Order_Type, value); }
        }
        decimal fcTotal_Addons;
        public decimal cTotal_Addons
        {
            get { return fcTotal_Addons; }
            set { SetPropertyValue<decimal>(nameof(cTotal_Addons), ref fcTotal_Addons, value); }
        }
        decimal fcItems_Total;
        public decimal cItems_Total
        {
            get { return fcItems_Total; }
            set { SetPropertyValue<decimal>(nameof(cItems_Total), ref fcItems_Total, value); }
        }
        decimal fcItems_Total_Cost;
        public decimal cItems_Total_Cost
        {
            get { return fcItems_Total_Cost; }
            set { SetPropertyValue<decimal>(nameof(cItems_Total_Cost), ref fcItems_Total_Cost, value); }
        }
        decimal fcItems_Total_SF;
        public decimal cItems_Total_SF
        {
            get { return fcItems_Total_SF; }
            set { SetPropertyValue<decimal>(nameof(cItems_Total_SF), ref fcItems_Total_SF, value); }
        }
    }

}
