//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class RM_Options_Show : XPLiteObject
    {
        Guid fRM_Options_Show_ID;
        [Key(true)]
        public Guid RM_Options_Show_ID
        {
            get { return fRM_Options_Show_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Options_Show_ID), ref fRM_Options_Show_ID, value); }
        }
        Guid fRM_Main_ID;
        public Guid RM_Main_ID
        {
            get { return fRM_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Main_ID), ref fRM_Main_ID, value); }
        }
        Guid fTerms;
        public Guid Terms
        {
            get { return fTerms; }
            set { SetPropertyValue<Guid>(nameof(Terms), ref fTerms, value); }
        }
        Guid fShip_Via;
        public Guid Ship_Via
        {
            get { return fShip_Via; }
            set { SetPropertyValue<Guid>(nameof(Ship_Via), ref fShip_Via, value); }
        }
        string fPO_Number;
        [Size(20)]
        public string PO_Number
        {
            get { return fPO_Number; }
            set { SetPropertyValue<string>(nameof(PO_Number), ref fPO_Number, value); }
        }
        string fInvoice_Number;
        [Size(20)]
        public string Invoice_Number
        {
            get { return fInvoice_Number; }
            set { SetPropertyValue<string>(nameof(Invoice_Number), ref fInvoice_Number, value); }
        }
        string fCredit_Memo_To_Invoice_Number;
        [Size(20)]
        public string Credit_Memo_To_Invoice_Number
        {
            get { return fCredit_Memo_To_Invoice_Number; }
            set { SetPropertyValue<string>(nameof(Credit_Memo_To_Invoice_Number), ref fCredit_Memo_To_Invoice_Number, value); }
        }
        string fRebill_Invoice_Number;
        [Size(20)]
        public string Rebill_Invoice_Number
        {
            get { return fRebill_Invoice_Number; }
            set { SetPropertyValue<string>(nameof(Rebill_Invoice_Number), ref fRebill_Invoice_Number, value); }
        }
        decimal fOrder_Amount;
        public decimal Order_Amount
        {
            get { return fOrder_Amount; }
            set { SetPropertyValue<decimal>(nameof(Order_Amount), ref fOrder_Amount, value); }
        }
        decimal fOrder_Cost;
        public decimal Order_Cost
        {
            get { return fOrder_Cost; }
            set { SetPropertyValue<decimal>(nameof(Order_Cost), ref fOrder_Cost, value); }
        }
        decimal fOrder_Amount_Shipped;
        public decimal Order_Amount_Shipped
        {
            get { return fOrder_Amount_Shipped; }
            set { SetPropertyValue<decimal>(nameof(Order_Amount_Shipped), ref fOrder_Amount_Shipped, value); }
        }
        decimal fOrder_Shipped_Cost;
        public decimal Order_Shipped_Cost
        {
            get { return fOrder_Shipped_Cost; }
            set { SetPropertyValue<decimal>(nameof(Order_Shipped_Cost), ref fOrder_Shipped_Cost, value); }
        }
        decimal fFreight_Amount;
        public decimal Freight_Amount
        {
            get { return fFreight_Amount; }
            set { SetPropertyValue<decimal>(nameof(Freight_Amount), ref fFreight_Amount, value); }
        }
        decimal fInsurance_Amount;
        public decimal Insurance_Amount
        {
            get { return fInsurance_Amount; }
            set { SetPropertyValue<decimal>(nameof(Insurance_Amount), ref fInsurance_Amount, value); }
        }
        decimal fHandling_Charge;
        public decimal Handling_Charge
        {
            get { return fHandling_Charge; }
            set { SetPropertyValue<decimal>(nameof(Handling_Charge), ref fHandling_Charge, value); }
        }
        decimal fTotal_Order_Amount;
        public decimal Total_Order_Amount
        {
            get { return fTotal_Order_Amount; }
            set { SetPropertyValue<decimal>(nameof(Total_Order_Amount), ref fTotal_Order_Amount, value); }
        }
        decimal fTotal_Order_Amount_Shipped;
        public decimal Total_Order_Amount_Shipped
        {
            get { return fTotal_Order_Amount_Shipped; }
            set { SetPropertyValue<decimal>(nameof(Total_Order_Amount_Shipped), ref fTotal_Order_Amount_Shipped, value); }
        }
        DateTime fRequest_Date;
        public DateTime Request_Date
        {
            get { return fRequest_Date; }
            set { SetPropertyValue<DateTime>(nameof(Request_Date), ref fRequest_Date, value); }
        }
        DateTime fCancel_Date;
        public DateTime Cancel_Date
        {
            get { return fCancel_Date; }
            set { SetPropertyValue<DateTime>(nameof(Cancel_Date), ref fCancel_Date, value); }
        }
        Guid fSalesman_Number_1;
        public Guid Salesman_Number_1
        {
            get { return fSalesman_Number_1; }
            set { SetPropertyValue<Guid>(nameof(Salesman_Number_1), ref fSalesman_Number_1, value); }
        }
        Guid fSalesman_Number_2;
        public Guid Salesman_Number_2
        {
            get { return fSalesman_Number_2; }
            set { SetPropertyValue<Guid>(nameof(Salesman_Number_2), ref fSalesman_Number_2, value); }
        }
        Guid fCommission_Split;
        public Guid Commission_Split
        {
            get { return fCommission_Split; }
            set { SetPropertyValue<Guid>(nameof(Commission_Split), ref fCommission_Split, value); }
        }
        decimal fCommission_Amount;
        public decimal Commission_Amount
        {
            get { return fCommission_Amount; }
            set { SetPropertyValue<decimal>(nameof(Commission_Amount), ref fCommission_Amount, value); }
        }
        Guid fDiscount;
        public Guid Discount
        {
            get { return fDiscount; }
            set { SetPropertyValue<Guid>(nameof(Discount), ref fDiscount, value); }
        }
        int fDiscount_Percent;
        public int Discount_Percent
        {
            get { return fDiscount_Percent; }
            set { SetPropertyValue<int>(nameof(Discount_Percent), ref fDiscount_Percent, value); }
        }
        decimal fDiscount_Amount;
        public decimal Discount_Amount
        {
            get { return fDiscount_Amount; }
            set { SetPropertyValue<decimal>(nameof(Discount_Amount), ref fDiscount_Amount, value); }
        }
        bool fCredit_Pending;
        public bool Credit_Pending
        {
            get { return fCredit_Pending; }
            set { SetPropertyValue<bool>(nameof(Credit_Pending), ref fCredit_Pending, value); }
        }
        bool fDo_Not_Ship;
        public bool Do_Not_Ship
        {
            get { return fDo_Not_Ship; }
            set { SetPropertyValue<bool>(nameof(Do_Not_Ship), ref fDo_Not_Ship, value); }
        }
        Guid fCredit_Status;
        public Guid Credit_Status
        {
            get { return fCredit_Status; }
            set { SetPropertyValue<Guid>(nameof(Credit_Status), ref fCredit_Status, value); }
        }
        bool fAllow_Dating;
        public bool Allow_Dating
        {
            get { return fAllow_Dating; }
            set { SetPropertyValue<bool>(nameof(Allow_Dating), ref fAllow_Dating, value); }
        }
        bool fOrder_Acknowledgement;
        public bool Order_Acknowledgement
        {
            get { return fOrder_Acknowledgement; }
            set { SetPropertyValue<bool>(nameof(Order_Acknowledgement), ref fOrder_Acknowledgement, value); }
        }
        DateTime fDate_Acknowledgement_Printed;
        public DateTime Date_Acknowledgement_Printed
        {
            get { return fDate_Acknowledgement_Printed; }
            set { SetPropertyValue<DateTime>(nameof(Date_Acknowledgement_Printed), ref fDate_Acknowledgement_Printed, value); }
        }
        bool fNo_Partial_Ship;
        public bool No_Partial_Ship
        {
            get { return fNo_Partial_Ship; }
            set { SetPropertyValue<bool>(nameof(No_Partial_Ship), ref fNo_Partial_Ship, value); }
        }
        bool fAccept_Backorders;
        public bool Accept_Backorders
        {
            get { return fAccept_Backorders; }
            set { SetPropertyValue<bool>(nameof(Accept_Backorders), ref fAccept_Backorders, value); }
        }
        bool fAuto_OE_Minimums;
        public bool Auto_OE_Minimums
        {
            get { return fAuto_OE_Minimums; }
            set { SetPropertyValue<bool>(nameof(Auto_OE_Minimums), ref fAuto_OE_Minimums, value); }
        }
        int fUse_Price_Set;
        public int Use_Price_Set
        {
            get { return fUse_Price_Set; }
            set { SetPropertyValue<int>(nameof(Use_Price_Set), ref fUse_Price_Set, value); }
        }
        bool fCall_Before_Shipping;
        public bool Call_Before_Shipping
        {
            get { return fCall_Before_Shipping; }
            set { SetPropertyValue<bool>(nameof(Call_Before_Shipping), ref fCall_Before_Shipping, value); }
        }
        bool fCall_Before_Delivery;
        public bool Call_Before_Delivery
        {
            get { return fCall_Before_Delivery; }
            set { SetPropertyValue<bool>(nameof(Call_Before_Delivery), ref fCall_Before_Delivery, value); }
        }
        bool fCall_Before_Shipping_BOs;
        public bool Call_Before_Shipping_BOs
        {
            get { return fCall_Before_Shipping_BOs; }
            set { SetPropertyValue<bool>(nameof(Call_Before_Shipping_BOs), ref fCall_Before_Shipping_BOs, value); }
        }
        bool fPickup_Orders_Only;
        public bool Pickup_Orders_Only
        {
            get { return fPickup_Orders_Only; }
            set { SetPropertyValue<bool>(nameof(Pickup_Orders_Only), ref fPickup_Orders_Only, value); }
        }
        bool fPrePay_Rebill_Freight;
        public bool PrePay_Rebill_Freight
        {
            get { return fPrePay_Rebill_Freight; }
            set { SetPropertyValue<bool>(nameof(PrePay_Rebill_Freight), ref fPrePay_Rebill_Freight, value); }
        }
        bool fModified_Status;
        public bool Modified_Status
        {
            get { return fModified_Status; }
            set { SetPropertyValue<bool>(nameof(Modified_Status), ref fModified_Status, value); }
        }
        Guid fTD_Main_ID;
        public Guid TD_Main_ID
        {
            get { return fTD_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(TD_Main_ID), ref fTD_Main_ID, value); }
        }
        Guid fSM_Main_ID;
        public Guid SM_Main_ID
        {
            get { return fSM_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(SM_Main_ID), ref fSM_Main_ID, value); }
        }
        Guid fSM_Main_ID_1;
        public Guid SM_Main_ID_1
        {
            get { return fSM_Main_ID_1; }
            set { SetPropertyValue<Guid>(nameof(SM_Main_ID_1), ref fSM_Main_ID_1, value); }
        }
        string fAlpha;
        [Size(10)]
        public string Alpha
        {
            get { return fAlpha; }
            set { SetPropertyValue<string>(nameof(Alpha), ref fAlpha, value); }
        }
    }

}
