//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class RM_Process : XPLiteObject
    {
        Guid fRM_Process_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid RM_Process_ID
        {
            get { return fRM_Process_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Process_ID), ref fRM_Process_ID, value); }
        }
        RM_Main fRM_Main_ID;
        [Association(@"RM_ProcessReferencesRM_Main")]
        public RM_Main RM_Main_ID
        {
            get { return fRM_Main_ID; }
            set { SetPropertyValue<RM_Main>(nameof(RM_Main_ID), ref fRM_Main_ID, value); }
        }
        string fTracking_Number;
        [Size(18)]
        public string Tracking_Number
        {
            get { return fTracking_Number; }
            set { SetPropertyValue<string>(nameof(Tracking_Number), ref fTracking_Number, value); }
        }
        int fPackage_Count;
        public int Package_Count
        {
            get { return fPackage_Count; }
            set { SetPropertyValue<int>(nameof(Package_Count), ref fPackage_Count, value); }
        }
        bool fPrint_PickTicket_Now;
        public bool Print_PickTicket_Now
        {
            get { return fPrint_PickTicket_Now; }
            set { SetPropertyValue<bool>(nameof(Print_PickTicket_Now), ref fPrint_PickTicket_Now, value); }
        }
        bool fRePrint_PickingTicket;
        public bool RePrint_PickingTicket
        {
            get { return fRePrint_PickingTicket; }
            set { SetPropertyValue<bool>(nameof(RePrint_PickingTicket), ref fRePrint_PickingTicket, value); }
        }
        DateTime fDate_InPicking;
        public DateTime Date_InPicking
        {
            get { return fDate_InPicking; }
            set { SetPropertyValue<DateTime>(nameof(Date_InPicking), ref fDate_InPicking, value); }
        }
        DateTime fDate_Shipped;
        public DateTime Date_Shipped
        {
            get { return fDate_Shipped; }
            set { SetPropertyValue<DateTime>(nameof(Date_Shipped), ref fDate_Shipped, value); }
        }
        DateTime fDate_Invoiced;
        [Indexed(Name = @"IDX_DATEINVOICED")]
        public DateTime Date_Invoiced
        {
            get { return fDate_Invoiced; }
            set { SetPropertyValue<DateTime>(nameof(Date_Invoiced), ref fDate_Invoiced, value); }
        }
        DateTime fOriginal_Due_Date;
        public DateTime Original_Due_Date
        {
            get { return fOriginal_Due_Date; }
            set { SetPropertyValue<DateTime>(nameof(Original_Due_Date), ref fOriginal_Due_Date, value); }
        }
        DateTime fDate_RePrint_PickingTicket;
        public DateTime Date_RePrint_PickingTicket
        {
            get { return fDate_RePrint_PickingTicket; }
            set { SetPropertyValue<DateTime>(nameof(Date_RePrint_PickingTicket), ref fDate_RePrint_PickingTicket, value); }
        }
        DateTime fDate_RePrint_Invoice;
        public DateTime Date_RePrint_Invoice
        {
            get { return fDate_RePrint_Invoice; }
            set { SetPropertyValue<DateTime>(nameof(Date_RePrint_Invoice), ref fDate_RePrint_Invoice, value); }
        }
        Guid fUD_Main_ID_Picker;
        public Guid UD_Main_ID_Picker
        {
            get { return fUD_Main_ID_Picker; }
            set { SetPropertyValue<Guid>(nameof(UD_Main_ID_Picker), ref fUD_Main_ID_Picker, value); }
        }
        int fPick_Time_Hours_Minutes;
        public int Pick_Time_Hours_Minutes
        {
            get { return fPick_Time_Hours_Minutes; }
            set { SetPropertyValue<int>(nameof(Pick_Time_Hours_Minutes), ref fPick_Time_Hours_Minutes, value); }
        }
        Guid fUD_Main_ID_Packer;
        public Guid UD_Main_ID_Packer
        {
            get { return fUD_Main_ID_Packer; }
            set { SetPropertyValue<Guid>(nameof(UD_Main_ID_Packer), ref fUD_Main_ID_Packer, value); }
        }
        Guid fUD_Main_ID_Checker;
        public Guid UD_Main_ID_Checker
        {
            get { return fUD_Main_ID_Checker; }
            set { SetPropertyValue<Guid>(nameof(UD_Main_ID_Checker), ref fUD_Main_ID_Checker, value); }
        }
        Guid fUD_Main_ID_WriteUp;
        public Guid UD_Main_ID_WriteUp
        {
            get { return fUD_Main_ID_WriteUp; }
            set { SetPropertyValue<Guid>(nameof(UD_Main_ID_WriteUp), ref fUD_Main_ID_WriteUp, value); }
        }
        UD_Main fUD_Main_ID;
        [Association(@"RM_ProcessReferencesUD_Main")]
        public UD_Main UD_Main_ID
        {
            get { return fUD_Main_ID; }
            set { SetPropertyValue<UD_Main>(nameof(UD_Main_ID), ref fUD_Main_ID, value); }
        }
        DateTime fDate_Canceled;
        public DateTime Date_Canceled
        {
            get { return fDate_Canceled; }
            set { SetPropertyValue<DateTime>(nameof(Date_Canceled), ref fDate_Canceled, value); }
        }
        UD_Main fPicker;
        [Association(@"RM_ProcessReferencesUD_Main2")]
        public UD_Main Picker
        {
            get { return fPicker; }
            set { SetPropertyValue<UD_Main>(nameof(Picker), ref fPicker, value); }
        }
        UD_Main fPacker;
        [Association(@"RM_ProcessReferencesUD_Main3")]
        public UD_Main Packer
        {
            get { return fPacker; }
            set { SetPropertyValue<UD_Main>(nameof(Packer), ref fPacker, value); }
        }
        UD_Main fChecker;
        [Association(@"RM_ProcessReferencesUD_Main4")]
        public UD_Main Checker
        {
            get { return fChecker; }
            set { SetPropertyValue<UD_Main>(nameof(Checker), ref fChecker, value); }
        }
        UD_Main fWriteUp;
        [Association(@"RM_ProcessReferencesUD_Main5")]
        public UD_Main WriteUp
        {
            get { return fWriteUp; }
            set { SetPropertyValue<UD_Main>(nameof(WriteUp), ref fWriteUp, value); }
        }
        UD_Main fUser_ID;
        [Association(@"RM_ProcessReferencesUD_Main1")]
        public UD_Main User_ID
        {
            get { return fUser_ID; }
            set { SetPropertyValue<UD_Main>(nameof(User_ID), ref fUser_ID, value); }
        }
        bool fRePrint_Invoice;
        public bool RePrint_Invoice
        {
            get { return fRePrint_Invoice; }
            set { SetPropertyValue<bool>(nameof(RePrint_Invoice), ref fRePrint_Invoice, value); }
        }
        DateTime fFuture_Imprint_Report;
        public DateTime Future_Imprint_Report
        {
            get { return fFuture_Imprint_Report; }
            set { SetPropertyValue<DateTime>(nameof(Future_Imprint_Report), ref fFuture_Imprint_Report, value); }
        }
        DateTime fPad_Print_Work_Date;
        public DateTime Pad_Print_Work_Date
        {
            get { return fPad_Print_Work_Date; }
            set { SetPropertyValue<DateTime>(nameof(Pad_Print_Work_Date), ref fPad_Print_Work_Date, value); }
        }
        string fHotSyncName;
        [Size(50)]
        public string HotSyncName
        {
            get { return fHotSyncName; }
            set { SetPropertyValue<string>(nameof(HotSyncName), ref fHotSyncName, value); }
        }
        DateTime fPort_Date_Time;
        public DateTime Port_Date_Time
        {
            get { return fPort_Date_Time; }
            set { SetPropertyValue<DateTime>(nameof(Port_Date_Time), ref fPort_Date_Time, value); }
        }
        UD_Main fUD_Main_ID_Canceled;
        [Association(@"RM_ProcessReferencesUD_Main6")]
        public UD_Main UD_Main_ID_Canceled
        {
            get { return fUD_Main_ID_Canceled; }
            set { SetPropertyValue<UD_Main>(nameof(UD_Main_ID_Canceled), ref fUD_Main_ID_Canceled, value); }
        }
        int fgrid_Print_PickTicket_Now_Enabled;
        public int grid_Print_PickTicket_Now_Enabled
        {
            get { return fgrid_Print_PickTicket_Now_Enabled; }
            set { SetPropertyValue<int>(nameof(grid_Print_PickTicket_Now_Enabled), ref fgrid_Print_PickTicket_Now_Enabled, value); }
        }
        int fgrid_Date_RePrint_PickingTicket_Warning;
        public int grid_Date_RePrint_PickingTicket_Warning
        {
            get { return fgrid_Date_RePrint_PickingTicket_Warning; }
            set { SetPropertyValue<int>(nameof(grid_Date_RePrint_PickingTicket_Warning), ref fgrid_Date_RePrint_PickingTicket_Warning, value); }
        }
        int fgrid_Date_RePrint_Invoice_Warning;
        public int grid_Date_RePrint_Invoice_Warning
        {
            get { return fgrid_Date_RePrint_Invoice_Warning; }
            set { SetPropertyValue<int>(nameof(grid_Date_RePrint_Invoice_Warning), ref fgrid_Date_RePrint_Invoice_Warning, value); }
        }
        int fgrid_RePrint_Invoice_Enabled;
        public int grid_RePrint_Invoice_Enabled
        {
            get { return fgrid_RePrint_Invoice_Enabled; }
            set { SetPropertyValue<int>(nameof(grid_RePrint_Invoice_Enabled), ref fgrid_RePrint_Invoice_Enabled, value); }
        }
        int fgrid_RePrint_PickingTicket_Enabled;
        public int grid_RePrint_PickingTicket_Enabled
        {
            get { return fgrid_RePrint_PickingTicket_Enabled; }
            set { SetPropertyValue<int>(nameof(grid_RePrint_PickingTicket_Enabled), ref fgrid_RePrint_PickingTicket_Enabled, value); }
        }
        bool fCanceled_Visible;
        public bool Canceled_Visible
        {
            get { return fCanceled_Visible; }
            set { SetPropertyValue<bool>(nameof(Canceled_Visible), ref fCanceled_Visible, value); }
        }
    }

}
