//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class RM_Problems_Show : XPLiteObject
    {
        Guid fRM_Problems_Show_ID;
        [Key(true)]
        public Guid RM_Problems_Show_ID
        {
            get { return fRM_Problems_Show_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Problems_Show_ID), ref fRM_Problems_Show_ID, value); }
        }
        Guid fRM_Main_ID;
        public Guid RM_Main_ID
        {
            get { return fRM_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Main_ID), ref fRM_Main_ID, value); }
        }
        bool fProblem_With_Credit;
        public bool Problem_With_Credit
        {
            get { return fProblem_With_Credit; }
            set { SetPropertyValue<bool>(nameof(Problem_With_Credit), ref fProblem_With_Credit, value); }
        }
        bool fProblem_With_Header;
        public bool Problem_With_Header
        {
            get { return fProblem_With_Header; }
            set { SetPropertyValue<bool>(nameof(Problem_With_Header), ref fProblem_With_Header, value); }
        }
        bool fProblem_With_Line_Items;
        public bool Problem_With_Line_Items
        {
            get { return fProblem_With_Line_Items; }
            set { SetPropertyValue<bool>(nameof(Problem_With_Line_Items), ref fProblem_With_Line_Items, value); }
        }
        bool fProblem_With_ShippingFeedBack;
        public bool Problem_With_ShippingFeedBack
        {
            get { return fProblem_With_ShippingFeedBack; }
            set { SetPropertyValue<bool>(nameof(Problem_With_ShippingFeedBack), ref fProblem_With_ShippingFeedBack, value); }
        }
        bool fOverride_Credit_Memo_Problem;
        public bool Override_Credit_Memo_Problem
        {
            get { return fOverride_Credit_Memo_Problem; }
            set { SetPropertyValue<bool>(nameof(Override_Credit_Memo_Problem), ref fOverride_Credit_Memo_Problem, value); }
        }
    }

}
