//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class RM_Test_Data : XPLiteObject
    {
        Guid fRM_Test_ID;
        [ColumnDbDefaultValue("(newid())")]
        public Guid RM_Test_ID
        {
            get { return fRM_Test_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Test_ID), ref fRM_Test_ID, value); }
        }
        Guid fRM_Main_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid RM_Main_ID
        {
            get { return fRM_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(RM_Main_ID), ref fRM_Main_ID, value); }
        }
        decimal fInsurance_Amount;
        public decimal Insurance_Amount
        {
            get { return fInsurance_Amount; }
            set { SetPropertyValue<decimal>(nameof(Insurance_Amount), ref fInsurance_Amount, value); }
        }
    }

}
