//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class SC_Main : XPLiteObject
    {
        Guid fSC_Main_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid SC_Main_ID
        {
            get { return fSC_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(SC_Main_ID), ref fSC_Main_ID, value); }
        }
        decimal fCommission_From_Key;
        [ColumnDbDefaultValue("((0))")]
        public decimal Commission_From_Key
        {
            get { return fCommission_From_Key; }
            set { SetPropertyValue<decimal>(nameof(Commission_From_Key), ref fCommission_From_Key, value); }
        }
        decimal fCommission_To_Key;
        [ColumnDbDefaultValue("((0))")]
        public decimal Commission_To_Key
        {
            get { return fCommission_To_Key; }
            set { SetPropertyValue<decimal>(nameof(Commission_To_Key), ref fCommission_To_Key, value); }
        }
        decimal fCommission_Percent;
        [ColumnDbDefaultValue("((0))")]
        public decimal Commission_Percent
        {
            get { return fCommission_Percent; }
            set { SetPropertyValue<decimal>(nameof(Commission_Percent), ref fCommission_Percent, value); }
        }
    }

}
