//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class ST_Data : XPLiteObject
    {
        Guid fST_Data_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid ST_Data_ID
        {
            get { return fST_Data_ID; }
            set { SetPropertyValue<Guid>(nameof(ST_Data_ID), ref fST_Data_ID, value); }
        }
        string fZip_Code;
        [Size(5)]
        public string Zip_Code
        {
            get { return fZip_Code; }
            set { SetPropertyValue<string>(nameof(Zip_Code), ref fZip_Code, value); }
        }
        int fTerritory;
        public int Territory
        {
            get { return fTerritory; }
            set { SetPropertyValue<int>(nameof(Territory), ref fTerritory, value); }
        }
        Guid fZip_Code_Link;
        public Guid Zip_Code_Link
        {
            get { return fZip_Code_Link; }
            set { SetPropertyValue<Guid>(nameof(Zip_Code_Link), ref fZip_Code_Link, value); }
        }
    }

}
