//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class start : XPLiteObject
    {
        int fStart_ID;
        [Key(true)]
        public int Start_ID
        {
            get { return fStart_ID; }
            set { SetPropertyValue<int>(nameof(Start_ID), ref fStart_ID, value); }
        }
        string fName;
        [Size(1024)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(1024)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fStatus;
        [Size(1024)]
        [Persistent(@"Status  ")]
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        string fStartupType;
        [Size(1024)]
        [Persistent(@"Startup Type")]
        public string StartupType
        {
            get { return fStartupType; }
            set { SetPropertyValue<string>(nameof(StartupType), ref fStartupType, value); }
        }
        string fLogOnAs;
        [Size(1024)]
        [Persistent(@"Log On As")]
        public string LogOnAs
        {
            get { return fLogOnAs; }
            set { SetPropertyValue<string>(nameof(LogOnAs), ref fLogOnAs, value); }
        }
    }

}
