//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class System_Value_Table : XPLiteObject
    {
        string fID;
        [Key]
        [Size(3)]
        [ColumnDbDefaultValue("('')")]
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>(nameof(ID), ref fID, value); }
        }
        int fCurrent_Show;
        [ColumnDbDefaultValue("((0))")]
        public int Current_Show
        {
            get { return fCurrent_Show; }
            set { SetPropertyValue<int>(nameof(Current_Show), ref fCurrent_Show, value); }
        }
        short fPicking_PreDays;
        [ColumnDbDefaultValue("((0))")]
        public short Picking_PreDays
        {
            get { return fPicking_PreDays; }
            set { SetPropertyValue<short>(nameof(Picking_PreDays), ref fPicking_PreDays, value); }
        }
        int fCurrent_Date;
        [ColumnDbDefaultValue("((0))")]
        public int Current_Date
        {
            get { return fCurrent_Date; }
            set { SetPropertyValue<int>(nameof(Current_Date), ref fCurrent_Date, value); }
        }
        int fSystem_Date;
        [ColumnDbDefaultValue("((0))")]
        public int System_Date
        {
            get { return fSystem_Date; }
            set { SetPropertyValue<int>(nameof(System_Date), ref fSystem_Date, value); }
        }
        string fCommission_Type;
        [Size(1)]
        [ColumnDbDefaultValue("('')")]
        public string Commission_Type
        {
            get { return fCommission_Type; }
            set { SetPropertyValue<string>(nameof(Commission_Type), ref fCommission_Type, value); }
        }
        decimal fMinimum_Order_Amount;
        [ColumnDbDefaultValue("((0))")]
        public decimal Minimum_Order_Amount
        {
            get { return fMinimum_Order_Amount; }
            set { SetPropertyValue<decimal>(nameof(Minimum_Order_Amount), ref fMinimum_Order_Amount, value); }
        }
        decimal fShow_Minmum_Order_Amount;
        public decimal Show_Minmum_Order_Amount
        {
            get { return fShow_Minmum_Order_Amount; }
            set { SetPropertyValue<decimal>(nameof(Show_Minmum_Order_Amount), ref fShow_Minmum_Order_Amount, value); }
        }
        decimal fDefault_Finance_Charge_Rate;
        [ColumnDbDefaultValue("((0))")]
        public decimal Default_Finance_Charge_Rate
        {
            get { return fDefault_Finance_Charge_Rate; }
            set { SetPropertyValue<decimal>(nameof(Default_Finance_Charge_Rate), ref fDefault_Finance_Charge_Rate, value); }
        }
        short fDefault_No_Statement_Limit;
        [ColumnDbDefaultValue("((0))")]
        public short Default_No_Statement_Limit
        {
            get { return fDefault_No_Statement_Limit; }
            set { SetPropertyValue<short>(nameof(Default_No_Statement_Limit), ref fDefault_No_Statement_Limit, value); }
        }
        int fDefault_OE_Past_Due_Limit;
        [ColumnDbDefaultValue("((0))")]
        public int Default_OE_Past_Due_Limit
        {
            get { return fDefault_OE_Past_Due_Limit; }
            set { SetPropertyValue<int>(nameof(Default_OE_Past_Due_Limit), ref fDefault_OE_Past_Due_Limit, value); }
        }
        int fDefault_CM_Release_Limit;
        [ColumnDbDefaultValue("((0))")]
        public int Default_CM_Release_Limit
        {
            get { return fDefault_CM_Release_Limit; }
            set { SetPropertyValue<int>(nameof(Default_CM_Release_Limit), ref fDefault_CM_Release_Limit, value); }
        }
        int fDefault_Credit_Limit;
        [ColumnDbDefaultValue("((0))")]
        public int Default_Credit_Limit
        {
            get { return fDefault_Credit_Limit; }
            set { SetPropertyValue<int>(nameof(Default_Credit_Limit), ref fDefault_Credit_Limit, value); }
        }
        short fDefault_Credit_Responses;
        [ColumnDbDefaultValue("((0))")]
        public short Default_Credit_Responses
        {
            get { return fDefault_Credit_Responses; }
            set { SetPropertyValue<short>(nameof(Default_Credit_Responses), ref fDefault_Credit_Responses, value); }
        }
        decimal fDefault_Large_Order_Amount;
        [ColumnDbDefaultValue("((0))")]
        public decimal Default_Large_Order_Amount
        {
            get { return fDefault_Large_Order_Amount; }
            set { SetPropertyValue<decimal>(nameof(Default_Large_Order_Amount), ref fDefault_Large_Order_Amount, value); }
        }
        short fDefault_Credit_Request_To_Send;
        [ColumnDbDefaultValue("((0))")]
        public short Default_Credit_Request_To_Send
        {
            get { return fDefault_Credit_Request_To_Send; }
            set { SetPropertyValue<short>(nameof(Default_Credit_Request_To_Send), ref fDefault_Credit_Request_To_Send, value); }
        }
        short fDefault_Good_Credit_Request_To_Release;
        [ColumnDbDefaultValue("((0))")]
        public short Default_Good_Credit_Request_To_Release
        {
            get { return fDefault_Good_Credit_Request_To_Release; }
            set { SetPropertyValue<short>(nameof(Default_Good_Credit_Request_To_Release), ref fDefault_Good_Credit_Request_To_Release, value); }
        }
        short fDefault_Bad_Poor_Credit_Request;
        [ColumnDbDefaultValue("((0))")]
        public short Default_Bad_Poor_Credit_Request
        {
            get { return fDefault_Bad_Poor_Credit_Request; }
            set { SetPropertyValue<short>(nameof(Default_Bad_Poor_Credit_Request), ref fDefault_Bad_Poor_Credit_Request, value); }
        }
        short fDefault_Iffy_Credit_Request;
        [ColumnDbDefaultValue("((0))")]
        public short Default_Iffy_Credit_Request
        {
            get { return fDefault_Iffy_Credit_Request; }
            set { SetPropertyValue<short>(nameof(Default_Iffy_Credit_Request), ref fDefault_Iffy_Credit_Request, value); }
        }
        int fDefault_Station_ID;
        [ColumnDbDefaultValue("((1))")]
        public int Default_Station_ID
        {
            get { return fDefault_Station_ID; }
            set { SetPropertyValue<int>(nameof(Default_Station_ID), ref fDefault_Station_ID, value); }
        }
        int fDay_of_Week_Free_Calling_Plan;
        [ColumnDbDefaultValue("((0))")]
        public int Day_of_Week_Free_Calling_Plan
        {
            get { return fDay_of_Week_Free_Calling_Plan; }
            set { SetPropertyValue<int>(nameof(Day_of_Week_Free_Calling_Plan), ref fDay_of_Week_Free_Calling_Plan, value); }
        }
        decimal fNext_PO_Number;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_PO_Number
        {
            get { return fNext_PO_Number; }
            set { SetPropertyValue<decimal>(nameof(Next_PO_Number), ref fNext_PO_Number, value); }
        }
        decimal fNext_PO_Number_OverSeas;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_PO_Number_OverSeas
        {
            get { return fNext_PO_Number_OverSeas; }
            set { SetPropertyValue<decimal>(nameof(Next_PO_Number_OverSeas), ref fNext_PO_Number_OverSeas, value); }
        }
        decimal fNext_Picking_Ticket_Number;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_Picking_Ticket_Number
        {
            get { return fNext_Picking_Ticket_Number; }
            set { SetPropertyValue<decimal>(nameof(Next_Picking_Ticket_Number), ref fNext_Picking_Ticket_Number, value); }
        }
        decimal fNext_Credit_Request_Number;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_Credit_Request_Number
        {
            get { return fNext_Credit_Request_Number; }
            set { SetPropertyValue<decimal>(nameof(Next_Credit_Request_Number), ref fNext_Credit_Request_Number, value); }
        }
        decimal fNext_Credit_Memo_Number;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_Credit_Memo_Number
        {
            get { return fNext_Credit_Memo_Number; }
            set { SetPropertyValue<decimal>(nameof(Next_Credit_Memo_Number), ref fNext_Credit_Memo_Number, value); }
        }
        decimal fNext_Invoicing_Number;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_Invoicing_Number
        {
            get { return fNext_Invoicing_Number; }
            set { SetPropertyValue<decimal>(nameof(Next_Invoicing_Number), ref fNext_Invoicing_Number, value); }
        }
        decimal fNext_Letter_Number;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_Letter_Number
        {
            get { return fNext_Letter_Number; }
            set { SetPropertyValue<decimal>(nameof(Next_Letter_Number), ref fNext_Letter_Number, value); }
        }
        decimal fNext_Statement_Number;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_Statement_Number
        {
            get { return fNext_Statement_Number; }
            set { SetPropertyValue<decimal>(nameof(Next_Statement_Number), ref fNext_Statement_Number, value); }
        }
        decimal fNext_Order_Number;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_Order_Number
        {
            get { return fNext_Order_Number; }
            set { SetPropertyValue<decimal>(nameof(Next_Order_Number), ref fNext_Order_Number, value); }
        }
        int fNext_Gift_Show_Number;
        [ColumnDbDefaultValue("((0))")]
        public int Next_Gift_Show_Number
        {
            get { return fNext_Gift_Show_Number; }
            set { SetPropertyValue<int>(nameof(Next_Gift_Show_Number), ref fNext_Gift_Show_Number, value); }
        }
        decimal fNext_Auto_DB_CR_Number;
        [ColumnDbDefaultValue("((0))")]
        public decimal Next_Auto_DB_CR_Number
        {
            get { return fNext_Auto_DB_CR_Number; }
            set { SetPropertyValue<decimal>(nameof(Next_Auto_DB_CR_Number), ref fNext_Auto_DB_CR_Number, value); }
        }
        int fPick_Ticket_Date;
        [ColumnDbDefaultValue("((0))")]
        public int Pick_Ticket_Date
        {
            get { return fPick_Ticket_Date; }
            set { SetPropertyValue<int>(nameof(Pick_Ticket_Date), ref fPick_Ticket_Date, value); }
        }
        int fInvoice_Date;
        [ColumnDbDefaultValue("((0))")]
        public int Invoice_Date
        {
            get { return fInvoice_Date; }
            set { SetPropertyValue<int>(nameof(Invoice_Date), ref fInvoice_Date, value); }
        }
        int fCash_Receipts_Date;
        [ColumnDbDefaultValue("((0))")]
        public int Cash_Receipts_Date
        {
            get { return fCash_Receipts_Date; }
            set { SetPropertyValue<int>(nameof(Cash_Receipts_Date), ref fCash_Receipts_Date, value); }
        }
        int fStatements_Date;
        [ColumnDbDefaultValue("((0))")]
        public int Statements_Date
        {
            get { return fStatements_Date; }
            set { SetPropertyValue<int>(nameof(Statements_Date), ref fStatements_Date, value); }
        }
        string fShort_Report_Date;
        [Size(10)]
        [ColumnDbDefaultValue("('')")]
        public string Short_Report_Date
        {
            get { return fShort_Report_Date; }
            set { SetPropertyValue<string>(nameof(Short_Report_Date), ref fShort_Report_Date, value); }
        }
        string fLong_Report_Date;
        [Size(30)]
        [ColumnDbDefaultValue("('')")]
        public string Long_Report_Date
        {
            get { return fLong_Report_Date; }
            set { SetPropertyValue<string>(nameof(Long_Report_Date), ref fLong_Report_Date, value); }
        }
        int fMonth;
        [ColumnDbDefaultValue("((0))")]
        public int Month
        {
            get { return fMonth; }
            set { SetPropertyValue<int>(nameof(Month), ref fMonth, value); }
        }
        int fCurrent_Year_Short;
        [ColumnDbDefaultValue("((0))")]
        public int Current_Year_Short
        {
            get { return fCurrent_Year_Short; }
            set { SetPropertyValue<int>(nameof(Current_Year_Short), ref fCurrent_Year_Short, value); }
        }
        int fCurrent_Year_Long;
        [ColumnDbDefaultValue("((0))")]
        public int Current_Year_Long
        {
            get { return fCurrent_Year_Long; }
            set { SetPropertyValue<int>(nameof(Current_Year_Long), ref fCurrent_Year_Long, value); }
        }
        int fProcessing_Date;
        [ColumnDbDefaultValue("((0))")]
        public int Processing_Date
        {
            get { return fProcessing_Date; }
            set { SetPropertyValue<int>(nameof(Processing_Date), ref fProcessing_Date, value); }
        }
        int fCurrent_Month_For_EOM;
        [ColumnDbDefaultValue("((0))")]
        public int Current_Month_For_EOM
        {
            get { return fCurrent_Month_For_EOM; }
            set { SetPropertyValue<int>(nameof(Current_Month_For_EOM), ref fCurrent_Month_For_EOM, value); }
        }
        int fLast_Day_of_Month;
        [ColumnDbDefaultValue("((0))")]
        public int Last_Day_of_Month
        {
            get { return fLast_Day_of_Month; }
            set { SetPropertyValue<int>(nameof(Last_Day_of_Month), ref fLast_Day_of_Month, value); }
        }
        int fLead_Days_for_Picking_Tickets;
        [ColumnDbDefaultValue("((0))")]
        public int Lead_Days_for_Picking_Tickets
        {
            get { return fLead_Days_for_Picking_Tickets; }
            set { SetPropertyValue<int>(nameof(Lead_Days_for_Picking_Tickets), ref fLead_Days_for_Picking_Tickets, value); }
        }
        int fPast_Due_30;
        [ColumnDbDefaultValue("((0))")]
        public int Past_Due_30
        {
            get { return fPast_Due_30; }
            set { SetPropertyValue<int>(nameof(Past_Due_30), ref fPast_Due_30, value); }
        }
        int fPast_Due_60;
        [ColumnDbDefaultValue("((0))")]
        public int Past_Due_60
        {
            get { return fPast_Due_60; }
            set { SetPropertyValue<int>(nameof(Past_Due_60), ref fPast_Due_60, value); }
        }
        int fPast_Due_90;
        [ColumnDbDefaultValue("((0))")]
        public int Past_Due_90
        {
            get { return fPast_Due_90; }
            set { SetPropertyValue<int>(nameof(Past_Due_90), ref fPast_Due_90, value); }
        }
        int fPast_Due_120;
        [ColumnDbDefaultValue("((0))")]
        public int Past_Due_120
        {
            get { return fPast_Due_120; }
            set { SetPropertyValue<int>(nameof(Past_Due_120), ref fPast_Due_120, value); }
        }
        int fPast_Due_121_Plus;
        [ColumnDbDefaultValue("((0))")]
        public int Past_Due_121_Plus
        {
            get { return fPast_Due_121_Plus; }
            set { SetPropertyValue<int>(nameof(Past_Due_121_Plus), ref fPast_Due_121_Plus, value); }
        }
        bool fEOY_Active;
        [ColumnDbDefaultValue("((0))")]
        public bool EOY_Active
        {
            get { return fEOY_Active; }
            set { SetPropertyValue<bool>(nameof(EOY_Active), ref fEOY_Active, value); }
        }
        bool fEOD_Running;
        [ColumnDbDefaultValue("((0))")]
        public bool EOD_Running
        {
            get { return fEOD_Running; }
            set { SetPropertyValue<bool>(nameof(EOD_Running), ref fEOD_Running, value); }
        }
        bool fEOM_Running;
        [ColumnDbDefaultValue("((0))")]
        public bool EOM_Running
        {
            get { return fEOM_Running; }
            set { SetPropertyValue<bool>(nameof(EOM_Running), ref fEOM_Running, value); }
        }
        bool fEOY_Running;
        [ColumnDbDefaultValue("((0))")]
        public bool EOY_Running
        {
            get { return fEOY_Running; }
            set { SetPropertyValue<bool>(nameof(EOY_Running), ref fEOY_Running, value); }
        }
        bool fStatements_Running;
        [ColumnDbDefaultValue("((0))")]
        public bool Statements_Running
        {
            get { return fStatements_Running; }
            set { SetPropertyValue<bool>(nameof(Statements_Running), ref fStatements_Running, value); }
        }
        bool fCash_Receipts_Running;
        [ColumnDbDefaultValue("((0))")]
        public bool Cash_Receipts_Running
        {
            get { return fCash_Receipts_Running; }
            set { SetPropertyValue<bool>(nameof(Cash_Receipts_Running), ref fCash_Receipts_Running, value); }
        }
        bool fInvoices_Running;
        [ColumnDbDefaultValue("((0))")]
        public bool Invoices_Running
        {
            get { return fInvoices_Running; }
            set { SetPropertyValue<bool>(nameof(Invoices_Running), ref fInvoices_Running, value); }
        }
        bool fInventory_Receipts_Running;
        [ColumnDbDefaultValue("((0))")]
        public bool Inventory_Receipts_Running
        {
            get { return fInventory_Receipts_Running; }
            set { SetPropertyValue<bool>(nameof(Inventory_Receipts_Running), ref fInventory_Receipts_Running, value); }
        }
        bool fCreditMemos_Running;
        [ColumnDbDefaultValue("((0))")]
        public bool CreditMemos_Running
        {
            get { return fCreditMemos_Running; }
            set { SetPropertyValue<bool>(nameof(CreditMemos_Running), ref fCreditMemos_Running, value); }
        }
        bool fPickingTickets_Running;
        [ColumnDbDefaultValue("((0))")]
        public bool PickingTickets_Running
        {
            get { return fPickingTickets_Running; }
            set { SetPropertyValue<bool>(nameof(PickingTickets_Running), ref fPickingTickets_Running, value); }
        }
        bool fStatements_Summary_Run_Today;
        [ColumnDbDefaultValue("((0))")]
        public bool Statements_Summary_Run_Today
        {
            get { return fStatements_Summary_Run_Today; }
            set { SetPropertyValue<bool>(nameof(Statements_Summary_Run_Today), ref fStatements_Summary_Run_Today, value); }
        }
        decimal fBrokerage_Cost;
        [ColumnDbDefaultValue("((0))")]
        public decimal Brokerage_Cost
        {
            get { return fBrokerage_Cost; }
            set { SetPropertyValue<decimal>(nameof(Brokerage_Cost), ref fBrokerage_Cost, value); }
        }
        decimal fUser_Cost;
        [ColumnDbDefaultValue("((0))")]
        public decimal User_Cost
        {
            get { return fUser_Cost; }
            set { SetPropertyValue<decimal>(nameof(User_Cost), ref fUser_Cost, value); }
        }
        decimal fIns_Cost;
        [ColumnDbDefaultValue("((0))")]
        public decimal Ins_Cost
        {
            get { return fIns_Cost; }
            set { SetPropertyValue<decimal>(nameof(Ins_Cost), ref fIns_Cost, value); }
        }
        decimal fLowest_Price_Factor;
        [ColumnDbDefaultValue("((0))")]
        public decimal Lowest_Price_Factor
        {
            get { return fLowest_Price_Factor; }
            set { SetPropertyValue<decimal>(nameof(Lowest_Price_Factor), ref fLowest_Price_Factor, value); }
        }
        bool fIgnoreDeleteTriggers;
        [ColumnDbDefaultValue("((0))")]
        public bool IgnoreDeleteTriggers
        {
            get { return fIgnoreDeleteTriggers; }
            set { SetPropertyValue<bool>(nameof(IgnoreDeleteTriggers), ref fIgnoreDeleteTriggers, value); }
        }
        bool fIgnoreOrderTriggers;
        [ColumnDbDefaultValue("((0))")]
        public bool IgnoreOrderTriggers
        {
            get { return fIgnoreOrderTriggers; }
            set { SetPropertyValue<bool>(nameof(IgnoreOrderTriggers), ref fIgnoreOrderTriggers, value); }
        }
        bool fIgnoreCustomerTriggers;
        [ColumnDbDefaultValue("((0))")]
        public bool IgnoreCustomerTriggers
        {
            get { return fIgnoreCustomerTriggers; }
            set { SetPropertyValue<bool>(nameof(IgnoreCustomerTriggers), ref fIgnoreCustomerTriggers, value); }
        }
        bool fIgnoreItemTriggers;
        [ColumnDbDefaultValue("((0))")]
        public bool IgnoreItemTriggers
        {
            get { return fIgnoreItemTriggers; }
            set { SetPropertyValue<bool>(nameof(IgnoreItemTriggers), ref fIgnoreItemTriggers, value); }
        }
        int fActive_Show_ID;
        [ColumnDbDefaultValue("((0))")]
        public int Active_Show_ID
        {
            get { return fActive_Show_ID; }
            set { SetPropertyValue<int>(nameof(Active_Show_ID), ref fActive_Show_ID, value); }
        }
        string fLocation_Mask;
        [Size(25)]
        [ColumnDbDefaultValue("('0000-11-11-0000')")]
        public string Location_Mask
        {
            get { return fLocation_Mask; }
            set { SetPropertyValue<string>(nameof(Location_Mask), ref fLocation_Mask, value); }
        }
        string fLocation_Valid_1;
        [Size(150)]
        [ColumnDbDefaultValue("('')")]
        public string Location_Valid_1
        {
            get { return fLocation_Valid_1; }
            set { SetPropertyValue<string>(nameof(Location_Valid_1), ref fLocation_Valid_1, value); }
        }
        string fLocation_Valid_2;
        [Size(150)]
        [ColumnDbDefaultValue("('')")]
        public string Location_Valid_2
        {
            get { return fLocation_Valid_2; }
            set { SetPropertyValue<string>(nameof(Location_Valid_2), ref fLocation_Valid_2, value); }
        }
        string fLocation_Valid_3;
        [Size(150)]
        [ColumnDbDefaultValue("('')")]
        public string Location_Valid_3
        {
            get { return fLocation_Valid_3; }
            set { SetPropertyValue<string>(nameof(Location_Valid_3), ref fLocation_Valid_3, value); }
        }
        string fLocation_Valid_4;
        [Size(150)]
        [ColumnDbDefaultValue("('')")]
        public string Location_Valid_4
        {
            get { return fLocation_Valid_4; }
            set { SetPropertyValue<string>(nameof(Location_Valid_4), ref fLocation_Valid_4, value); }
        }
        DateTime fCreated_Date_Time;
        [ColumnDbDefaultValue("((0))")]
        public DateTime Created_Date_Time
        {
            get { return fCreated_Date_Time; }
            set { SetPropertyValue<DateTime>(nameof(Created_Date_Time), ref fCreated_Date_Time, value); }
        }
        int fCreated_User;
        [ColumnDbDefaultValue("((0))")]
        public int Created_User
        {
            get { return fCreated_User; }
            set { SetPropertyValue<int>(nameof(Created_User), ref fCreated_User, value); }
        }
        int fCreated_Station;
        [ColumnDbDefaultValue("((0))")]
        public int Created_Station
        {
            get { return fCreated_Station; }
            set { SetPropertyValue<int>(nameof(Created_Station), ref fCreated_Station, value); }
        }
        DateTime fLast_Updated_Date_Time;
        [ColumnDbDefaultValue("((0))")]
        public DateTime Last_Updated_Date_Time
        {
            get { return fLast_Updated_Date_Time; }
            set { SetPropertyValue<DateTime>(nameof(Last_Updated_Date_Time), ref fLast_Updated_Date_Time, value); }
        }
        int fLast_Updated_User;
        [ColumnDbDefaultValue("((0))")]
        public int Last_Updated_User
        {
            get { return fLast_Updated_User; }
            set { SetPropertyValue<int>(nameof(Last_Updated_User), ref fLast_Updated_User, value); }
        }
        int fLast_Updated_Station;
        [ColumnDbDefaultValue("((0))")]
        public int Last_Updated_Station
        {
            get { return fLast_Updated_Station; }
            set { SetPropertyValue<int>(nameof(Last_Updated_Station), ref fLast_Updated_Station, value); }
        }
        int fRecord_Status;
        [ColumnDbDefaultValue("((0))")]
        public int Record_Status
        {
            get { return fRecord_Status; }
            set { SetPropertyValue<int>(nameof(Record_Status), ref fRecord_Status, value); }
        }
        bool fModified_Status;
        [ColumnDbDefaultValue("((0))")]
        public bool Modified_Status
        {
            get { return fModified_Status; }
            set { SetPropertyValue<bool>(nameof(Modified_Status), ref fModified_Status, value); }
        }
        Guid frowguid;
        [ColumnDbDefaultValue("(newid())")]
        public Guid rowguid
        {
            get { return frowguid; }
            set { SetPropertyValue<Guid>(nameof(rowguid), ref frowguid, value); }
        }
        string fHostID;
        [Size(5)]
        public string HostID
        {
            get { return fHostID; }
            set { SetPropertyValue<string>(nameof(HostID), ref fHostID, value); }
        }
        string fShowServer;
        [Size(50)]
        [ColumnDbDefaultValue("('')")]
        public string ShowServer
        {
            get { return fShowServer; }
            set { SetPropertyValue<string>(nameof(ShowServer), ref fShowServer, value); }
        }
        DateTime fHarrys_Order_Date;
        public DateTime Harrys_Order_Date
        {
            get { return fHarrys_Order_Date; }
            set { SetPropertyValue<DateTime>(nameof(Harrys_Order_Date), ref fHarrys_Order_Date, value); }
        }
    }

}
