//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tbl_Days_In_n_Month : XPLiteObject
    {
        Guid ftbl_Days_In_n_Month_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid tbl_Days_In_n_Month_ID
        {
            get { return ftbl_Days_In_n_Month_ID; }
            set { SetPropertyValue<Guid>(nameof(tbl_Days_In_n_Month_ID), ref ftbl_Days_In_n_Month_ID, value); }
        }
        int fDay_Number;
        public int Day_Number
        {
            get { return fDay_Number; }
            set { SetPropertyValue<int>(nameof(Day_Number), ref fDay_Number, value); }
        }
    }

}
