//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tbl_Day_from_Number : XPLiteObject
    {
        Guid ftbl_Day_from_Number_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid tbl_Day_from_Number_ID
        {
            get { return ftbl_Day_from_Number_ID; }
            set { SetPropertyValue<Guid>(nameof(tbl_Day_from_Number_ID), ref ftbl_Day_from_Number_ID, value); }
        }
        int fDay_Index;
        public int Day_Index
        {
            get { return fDay_Index; }
            set { SetPropertyValue<int>(nameof(Day_Index), ref fDay_Index, value); }
        }
        string fDay_Name;
        [Size(30)]
        public string Day_Name
        {
            get { return fDay_Name; }
            set { SetPropertyValue<string>(nameof(Day_Name), ref fDay_Name, value); }
        }
    }

}
