//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class Tbl_Service_Names : XPLiteObject
    {
        Guid fID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid ID
        {
            get { return fID; }
            set { SetPropertyValue<Guid>(nameof(ID), ref fID, value); }
        }
        string fService_Symbol;
        [Size(60)]
        public string Service_Symbol
        {
            get { return fService_Symbol; }
            set { SetPropertyValue<string>(nameof(Service_Symbol), ref fService_Symbol, value); }
        }
        string fService_FriendlyName;
        [Size(50)]
        public string Service_FriendlyName
        {
            get { return fService_FriendlyName; }
            set { SetPropertyValue<string>(nameof(Service_FriendlyName), ref fService_FriendlyName, value); }
        }
    }

}
