//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblAttestationDocumentsConfig : XPLiteObject
    {
        int fAutoID;
        [Key(true)]
        public int AutoID
        {
            get { return fAutoID; }
            set { SetPropertyValue<int>(nameof(AutoID), ref fAutoID, value); }
        }
        string fPDFName;
        [Size(250)]
        public string PDFName
        {
            get { return fPDFName; }
            set { SetPropertyValue<string>(nameof(PDFName), ref fPDFName, value); }
        }
        string fPDFURI;
        [Size(250)]
        public string PDFURI
        {
            get { return fPDFURI; }
            set { SetPropertyValue<string>(nameof(PDFURI), ref fPDFURI, value); }
        }
        string fPDFDescription;
        [Size(250)]
        public string PDFDescription
        {
            get { return fPDFDescription; }
            set { SetPropertyValue<string>(nameof(PDFDescription), ref fPDFDescription, value); }
        }
        int fAccessItemID;
        public int AccessItemID
        {
            get { return fAccessItemID; }
            set { SetPropertyValue<int>(nameof(AccessItemID), ref fAccessItemID, value); }
        }
    }

}
