//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblFileAttachments : XPLiteObject
    {
        int fFileAttachmentID;
        [Key(true)]
        public int FileAttachmentID
        {
            get { return fFileAttachmentID; }
            set { SetPropertyValue<int>(nameof(FileAttachmentID), ref fFileAttachmentID, value); }
        }
        Guid fAttachmentGuid;
        [Indexed(Name = @"MSMERGE_INDEX_325784418", Unique = true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid AttachmentGuid
        {
            get { return fAttachmentGuid; }
            set { SetPropertyValue<Guid>(nameof(AttachmentGuid), ref fAttachmentGuid, value); }
        }
        string fExtension;
        public string Extension
        {
            get { return fExtension; }
            set { SetPropertyValue<string>(nameof(Extension), ref fExtension, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        string fDescription;
        [Size(250)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        byte[] fImage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Image
        {
            get { return fImage; }
            set { SetPropertyValue<byte[]>(nameof(Image), ref fImage, value); }
        }
        int fFlags;
        public int Flags
        {
            get { return fFlags; }
            set { SetPropertyValue<int>(nameof(Flags), ref fFlags, value); }
        }
        bool fDirectory;
        public bool Directory
        {
            get { return fDirectory; }
            set { SetPropertyValue<bool>(nameof(Directory), ref fDirectory, value); }
        }
        Guid fParentGuid;
        public Guid ParentGuid
        {
            get { return fParentGuid; }
            set { SetPropertyValue<Guid>(nameof(ParentGuid), ref fParentGuid, value); }
        }
        string fActualFileName;
        [Size(1000)]
        public string ActualFileName
        {
            get { return fActualFileName; }
            set { SetPropertyValue<string>(nameof(ActualFileName), ref fActualFileName, value); }
        }
        byte[] fFileData;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] FileData
        {
            get { return fFileData; }
            set { SetPropertyValue<byte[]>(nameof(FileData), ref fFileData, value); }
        }
    }

}
