//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblFileAttachmentLinkDefinition : XPLiteObject
    {
        int fLinkDefinitionID;
        [Key(true)]
        public int LinkDefinitionID
        {
            get { return fLinkDefinitionID; }
            set { SetPropertyValue<int>(nameof(LinkDefinitionID), ref fLinkDefinitionID, value); }
        }
        string fLinkDefinitionName;
        public string LinkDefinitionName
        {
            get { return fLinkDefinitionName; }
            set { SetPropertyValue<string>(nameof(LinkDefinitionName), ref fLinkDefinitionName, value); }
        }
        string fLinkTableName;
        public string LinkTableName
        {
            get { return fLinkTableName; }
            set { SetPropertyValue<string>(nameof(LinkTableName), ref fLinkTableName, value); }
        }
        string fLinkTablePK;
        public string LinkTablePK
        {
            get { return fLinkTablePK; }
            set { SetPropertyValue<string>(nameof(LinkTablePK), ref fLinkTablePK, value); }
        }
        string fLinkTableFK;
        public string LinkTableFK
        {
            get { return fLinkTableFK; }
            set { SetPropertyValue<string>(nameof(LinkTableFK), ref fLinkTableFK, value); }
        }
        string fLinkDescriptionQuery;
        [Size(500)]
        public string LinkDescriptionQuery
        {
            get { return fLinkDescriptionQuery; }
            set { SetPropertyValue<string>(nameof(LinkDescriptionQuery), ref fLinkDescriptionQuery, value); }
        }
        string fLinkReferenceTable;
        public string LinkReferenceTable
        {
            get { return fLinkReferenceTable; }
            set { SetPropertyValue<string>(nameof(LinkReferenceTable), ref fLinkReferenceTable, value); }
        }
        string fLinkReferencePK;
        public string LinkReferencePK
        {
            get { return fLinkReferencePK; }
            set { SetPropertyValue<string>(nameof(LinkReferencePK), ref fLinkReferencePK, value); }
        }
        string fLinkReferenceQuery;
        [Size(500)]
        public string LinkReferenceQuery
        {
            get { return fLinkReferenceQuery; }
            set { SetPropertyValue<string>(nameof(LinkReferenceQuery), ref fLinkReferenceQuery, value); }
        }
        string fLinkField;
        public string LinkField
        {
            get { return fLinkField; }
            set { SetPropertyValue<string>(nameof(LinkField), ref fLinkField, value); }
        }
        string fNavigationTree;
        [Size(250)]
        public string NavigationTree
        {
            get { return fNavigationTree; }
            set { SetPropertyValue<string>(nameof(NavigationTree), ref fNavigationTree, value); }
        }
        string fNavigationOwner;
        [Size(50)]
        public string NavigationOwner
        {
            get { return fNavigationOwner; }
            set { SetPropertyValue<string>(nameof(NavigationOwner), ref fNavigationOwner, value); }
        }
        string fNavigationScreen;
        [Size(50)]
        public string NavigationScreen
        {
            get { return fNavigationScreen; }
            set { SetPropertyValue<string>(nameof(NavigationScreen), ref fNavigationScreen, value); }
        }
        string fAuthor;
        [Size(50)]
        public string Author
        {
            get { return fAuthor; }
            set { SetPropertyValue<string>(nameof(Author), ref fAuthor, value); }
        }
        bool fUseCustomQuery;
        public bool UseCustomQuery
        {
            get { return fUseCustomQuery; }
            set { SetPropertyValue<bool>(nameof(UseCustomQuery), ref fUseCustomQuery, value); }
        }
        string fCustomQuery;
        [Size(4000)]
        public string CustomQuery
        {
            get { return fCustomQuery; }
            set { SetPropertyValue<string>(nameof(CustomQuery), ref fCustomQuery, value); }
        }
        string fLinkItemKey;
        public string LinkItemKey
        {
            get { return fLinkItemKey; }
            set { SetPropertyValue<string>(nameof(LinkItemKey), ref fLinkItemKey, value); }
        }
        string fLinkSubItemKey;
        public string LinkSubItemKey
        {
            get { return fLinkSubItemKey; }
            set { SetPropertyValue<string>(nameof(LinkSubItemKey), ref fLinkSubItemKey, value); }
        }
        string fScreenName;
        [Size(250)]
        public string ScreenName
        {
            get { return fScreenName; }
            set { SetPropertyValue<string>(nameof(ScreenName), ref fScreenName, value); }
        }
        [Association(@"tblFileAttachmentLinksReferencestblFileAttachmentLinkDefinition")]
        public XPCollection<tblFileAttachmentLinks> tblFileAttachmentLinksCollection { get { return GetCollection<tblFileAttachmentLinks>(nameof(tblFileAttachmentLinksCollection)); } }
    }

}
