//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblFileAttachmentLinks : XPLiteObject
    {
        int fLinkID;
        [Key(true)]
        public int LinkID
        {
            get { return fLinkID; }
            set { SetPropertyValue<int>(nameof(LinkID), ref fLinkID, value); }
        }
        tblFileAttachmentLinkDefinition fLinkDefinitionID;
        [Association(@"tblFileAttachmentLinksReferencestblFileAttachmentLinkDefinition")]
        public tblFileAttachmentLinkDefinition LinkDefinitionID
        {
            get { return fLinkDefinitionID; }
            set { SetPropertyValue<tblFileAttachmentLinkDefinition>(nameof(LinkDefinitionID), ref fLinkDefinitionID, value); }
        }
        string fItemID;
        [Size(250)]
        public string ItemID
        {
            get { return fItemID; }
            set { SetPropertyValue<string>(nameof(ItemID), ref fItemID, value); }
        }
        string fItemName;
        public string ItemName
        {
            get { return fItemName; }
            set { SetPropertyValue<string>(nameof(ItemName), ref fItemName, value); }
        }
        string fReferenceID;
        [Size(250)]
        public string ReferenceID
        {
            get { return fReferenceID; }
            set { SetPropertyValue<string>(nameof(ReferenceID), ref fReferenceID, value); }
        }
        string fReferenceName;
        public string ReferenceName
        {
            get { return fReferenceName; }
            set { SetPropertyValue<string>(nameof(ReferenceName), ref fReferenceName, value); }
        }
        string fSubItemID;
        [Size(250)]
        public string SubItemID
        {
            get { return fSubItemID; }
            set { SetPropertyValue<string>(nameof(SubItemID), ref fSubItemID, value); }
        }
        string fLinkData;
        [Size(1000)]
        public string LinkData
        {
            get { return fLinkData; }
            set { SetPropertyValue<string>(nameof(LinkData), ref fLinkData, value); }
        }
        int fLinkStatus;
        public int LinkStatus
        {
            get { return fLinkStatus; }
            set { SetPropertyValue<int>(nameof(LinkStatus), ref fLinkStatus, value); }
        }
    }

}
