//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblGroupItems : XPLiteObject
    {
        Guid ftblGroupItemID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid tblGroupItemID
        {
            get { return ftblGroupItemID; }
            set { SetPropertyValue<Guid>(nameof(tblGroupItemID), ref ftblGroupItemID, value); }
        }
        Guid ftblGroupID;
        public Guid tblGroupID
        {
            get { return ftblGroupID; }
            set { SetPropertyValue<Guid>(nameof(tblGroupID), ref ftblGroupID, value); }
        }
        string fTreeName;
        [Size(250)]
        public string TreeName
        {
            get { return fTreeName; }
            set { SetPropertyValue<string>(nameof(TreeName), ref fTreeName, value); }
        }
        string fTreeSecurityID;
        [Size(250)]
        public string TreeSecurityID
        {
            get { return fTreeSecurityID; }
            set { SetPropertyValue<string>(nameof(TreeSecurityID), ref fTreeSecurityID, value); }
        }
        int fLinkID;
        public int LinkID
        {
            get { return fLinkID; }
            set { SetPropertyValue<int>(nameof(LinkID), ref fLinkID, value); }
        }
    }

}
