//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblImageLocal : XPLiteObject
    {
        int fImageLocalID;
        [Key(true)]
        public int ImageLocalID
        {
            get { return fImageLocalID; }
            set { SetPropertyValue<int>(nameof(ImageLocalID), ref fImageLocalID, value); }
        }
        string fDescription;
        [Size(250)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fLocalID;
        public int LocalID
        {
            get { return fLocalID; }
            set { SetPropertyValue<int>(nameof(LocalID), ref fLocalID, value); }
        }
        string fHostName;
        [Size(50)]
        public string HostName
        {
            get { return fHostName; }
            set { SetPropertyValue<string>(nameof(HostName), ref fHostName, value); }
        }
    }

}
