//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblSystemText : XPLiteObject
    {
        Guid fSystemTextGUID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid SystemTextGUID
        {
            get { return fSystemTextGUID; }
            set { SetPropertyValue<Guid>(nameof(SystemTextGUID), ref fSystemTextGUID, value); }
        }
        string fSystemTextName;
        [Size(50)]
        public string SystemTextName
        {
            get { return fSystemTextName; }
            set { SetPropertyValue<string>(nameof(SystemTextName), ref fSystemTextName, value); }
        }
        int fSystemTextID;
        public int SystemTextID
        {
            get { return fSystemTextID; }
            set { SetPropertyValue<int>(nameof(SystemTextID), ref fSystemTextID, value); }
        }
        string fSystemText;
        [Size(1024)]
        public string SystemText
        {
            get { return fSystemText; }
            set { SetPropertyValue<string>(nameof(SystemText), ref fSystemText, value); }
        }
    }

}
