//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblStates : XPLiteObject
    {
        int fStateID;
        [Key(true)]
        public int StateID
        {
            get { return fStateID; }
            set { SetPropertyValue<int>(nameof(StateID), ref fStateID, value); }
        }
        string fShortName;
        [Size(2)]
        public string ShortName
        {
            get { return fShortName; }
            set { SetPropertyValue<string>(nameof(ShortName), ref fShortName, value); }
        }
        string fLongName;
        [Size(15)]
        public string LongName
        {
            get { return fLongName; }
            set { SetPropertyValue<string>(nameof(LongName), ref fLongName, value); }
        }
    }

}
