//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblSearch : XPLiteObject
    {
        Guid fSearchGuid;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid SearchGuid
        {
            get { return fSearchGuid; }
            set { SetPropertyValue<Guid>(nameof(SearchGuid), ref fSearchGuid, value); }
        }
        string fSearchDescription;
        [Size(250)]
        public string SearchDescription
        {
            get { return fSearchDescription; }
            set { SetPropertyValue<string>(nameof(SearchDescription), ref fSearchDescription, value); }
        }
        string fSearchSelectQuery;
        [Size(SizeAttribute.Unlimited)]
        public string SearchSelectQuery
        {
            get { return fSearchSelectQuery; }
            set { SetPropertyValue<string>(nameof(SearchSelectQuery), ref fSearchSelectQuery, value); }
        }
        string fSearchJoinQuery;
        [Size(SizeAttribute.Unlimited)]
        public string SearchJoinQuery
        {
            get { return fSearchJoinQuery; }
            set { SetPropertyValue<string>(nameof(SearchJoinQuery), ref fSearchJoinQuery, value); }
        }
        string fSearchWhereQuery;
        [Size(SizeAttribute.Unlimited)]
        public string SearchWhereQuery
        {
            get { return fSearchWhereQuery; }
            set { SetPropertyValue<string>(nameof(SearchWhereQuery), ref fSearchWhereQuery, value); }
        }
        string fSearchOrderbyQuery;
        [Size(SizeAttribute.Unlimited)]
        public string SearchOrderbyQuery
        {
            get { return fSearchOrderbyQuery; }
            set { SetPropertyValue<string>(nameof(SearchOrderbyQuery), ref fSearchOrderbyQuery, value); }
        }
        string fSearchHelp;
        [Size(SizeAttribute.Unlimited)]
        public string SearchHelp
        {
            get { return fSearchHelp; }
            set { SetPropertyValue<string>(nameof(SearchHelp), ref fSearchHelp, value); }
        }
        bool fVisibleinSearch;
        [ColumnDbDefaultValue("((0))")]
        public bool VisibleinSearch
        {
            get { return fVisibleinSearch; }
            set { SetPropertyValue<bool>(nameof(VisibleinSearch), ref fVisibleinSearch, value); }
        }
        bool fVisibleinReports;
        [ColumnDbDefaultValue("((0))")]
        public bool VisibleinReports
        {
            get { return fVisibleinReports; }
            set { SetPropertyValue<bool>(nameof(VisibleinReports), ref fVisibleinReports, value); }
        }
        bool fVisibleinPopulate;
        public bool VisibleinPopulate
        {
            get { return fVisibleinPopulate; }
            set { SetPropertyValue<bool>(nameof(VisibleinPopulate), ref fVisibleinPopulate, value); }
        }
        bool fVisibleinGlobalUpdate;
        [ColumnDbDefaultValue("((0))")]
        public bool VisibleinGlobalUpdate
        {
            get { return fVisibleinGlobalUpdate; }
            set { SetPropertyValue<bool>(nameof(VisibleinGlobalUpdate), ref fVisibleinGlobalUpdate, value); }
        }
        bool fVisibleinTracking;
        [ColumnDbDefaultValue("((0))")]
        public bool VisibleinTracking
        {
            get { return fVisibleinTracking; }
            set { SetPropertyValue<bool>(nameof(VisibleinTracking), ref fVisibleinTracking, value); }
        }
        bool fVisibleinTree;
        [ColumnDbDefaultValue("((0))")]
        public bool VisibleinTree
        {
            get { return fVisibleinTree; }
            set { SetPropertyValue<bool>(nameof(VisibleinTree), ref fVisibleinTree, value); }
        }
        bool fVisibleinFilterBar;
        [ColumnDbDefaultValue("((0))")]
        public bool VisibleinFilterBar
        {
            get { return fVisibleinFilterBar; }
            set { SetPropertyValue<bool>(nameof(VisibleinFilterBar), ref fVisibleinFilterBar, value); }
        }
        bool fVisibleinSearchBar;
        [ColumnDbDefaultValue("((0))")]
        public bool VisibleinSearchBar
        {
            get { return fVisibleinSearchBar; }
            set { SetPropertyValue<bool>(nameof(VisibleinSearchBar), ref fVisibleinSearchBar, value); }
        }
        bool fVisibleinAltSearch;
        [ColumnDbDefaultValue("((0))")]
        public bool VisibleinAltSearch
        {
            get { return fVisibleinAltSearch; }
            set { SetPropertyValue<bool>(nameof(VisibleinAltSearch), ref fVisibleinAltSearch, value); }
        }
        string fNavigateTree;
        [Size(250)]
        public string NavigateTree
        {
            get { return fNavigateTree; }
            set { SetPropertyValue<string>(nameof(NavigateTree), ref fNavigateTree, value); }
        }
        string fNavigateLevel;
        public string NavigateLevel
        {
            get { return fNavigateLevel; }
            set { SetPropertyValue<string>(nameof(NavigateLevel), ref fNavigateLevel, value); }
        }
        string fNavigateScreen;
        public string NavigateScreen
        {
            get { return fNavigateScreen; }
            set { SetPropertyValue<string>(nameof(NavigateScreen), ref fNavigateScreen, value); }
        }
        string fGroup;
        public string Group
        {
            get { return fGroup; }
            set { SetPropertyValue<string>(nameof(Group), ref fGroup, value); }
        }
        string fAuthor;
        [Size(50)]
        public string Author
        {
            get { return fAuthor; }
            set { SetPropertyValue<string>(nameof(Author), ref fAuthor, value); }
        }
        string fPrimaryView;
        public string PrimaryView
        {
            get { return fPrimaryView; }
            set { SetPropertyValue<string>(nameof(PrimaryView), ref fPrimaryView, value); }
        }
        string fTechnology;
        [Size(250)]
        public string Technology
        {
            get { return fTechnology; }
            set { SetPropertyValue<string>(nameof(Technology), ref fTechnology, value); }
        }
    }

}
