//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblSystemLimits : XPLiteObject
    {
        Guid fSystemLimitsGUID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid SystemLimitsGUID
        {
            get { return fSystemLimitsGUID; }
            set { SetPropertyValue<Guid>(nameof(SystemLimitsGUID), ref fSystemLimitsGUID, value); }
        }
        string fSystemLimitsName;
        [Size(50)]
        public string SystemLimitsName
        {
            get { return fSystemLimitsName; }
            set { SetPropertyValue<string>(nameof(SystemLimitsName), ref fSystemLimitsName, value); }
        }
        int fSystemLimitsID;
        public int SystemLimitsID
        {
            get { return fSystemLimitsID; }
            set { SetPropertyValue<int>(nameof(SystemLimitsID), ref fSystemLimitsID, value); }
        }
        decimal fSystemLimits;
        public decimal SystemLimits
        {
            get { return fSystemLimits; }
            set { SetPropertyValue<decimal>(nameof(SystemLimits), ref fSystemLimits, value); }
        }
        string fSystemLimitsFormat;
        [Size(25)]
        public string SystemLimitsFormat
        {
            get { return fSystemLimitsFormat; }
            set { SetPropertyValue<string>(nameof(SystemLimitsFormat), ref fSystemLimitsFormat, value); }
        }
        int fSystemLimitsPrecision;
        public int SystemLimitsPrecision
        {
            get { return fSystemLimitsPrecision; }
            set { SetPropertyValue<int>(nameof(SystemLimitsPrecision), ref fSystemLimitsPrecision, value); }
        }
    }

}
