//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblTraceSQL : XPLiteObject
    {
        Guid ftrace_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid trace_ID
        {
            get { return ftrace_ID; }
            set { SetPropertyValue<Guid>(nameof(trace_ID), ref ftrace_ID, value); }
        }
        string ftrace_SQL_NAME;
        [Size(50)]
        public string trace_SQL_NAME
        {
            get { return ftrace_SQL_NAME; }
            set { SetPropertyValue<string>(nameof(trace_SQL_NAME), ref ftrace_SQL_NAME, value); }
        }
        string ftrace_STEP_INFO;
        public string trace_STEP_INFO
        {
            get { return ftrace_STEP_INFO; }
            set { SetPropertyValue<string>(nameof(trace_STEP_INFO), ref ftrace_STEP_INFO, value); }
        }
        Guid ftrace_GUID;
        public Guid trace_GUID
        {
            get { return ftrace_GUID; }
            set { SetPropertyValue<Guid>(nameof(trace_GUID), ref ftrace_GUID, value); }
        }
        int ftrace_INT;
        public int trace_INT
        {
            get { return ftrace_INT; }
            set { SetPropertyValue<int>(nameof(trace_INT), ref ftrace_INT, value); }
        }
        decimal ftrace_Decimal;
        public decimal trace_Decimal
        {
            get { return ftrace_Decimal; }
            set { SetPropertyValue<decimal>(nameof(trace_Decimal), ref ftrace_Decimal, value); }
        }
        string ftrace_Comment;
        [Size(250)]
        public string trace_Comment
        {
            get { return ftrace_Comment; }
            set { SetPropertyValue<string>(nameof(trace_Comment), ref ftrace_Comment, value); }
        }
    }

}
