//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tblUSRType : XPLiteObject
    {
        int fUSRTypeID;
        [Key(true)]
        public int USRTypeID
        {
            get { return fUSRTypeID; }
            set { SetPropertyValue<int>(nameof(USRTypeID), ref fUSRTypeID, value); }
        }
        string fUSRType;
        [Size(250)]
        public string USRType
        {
            get { return fUSRType; }
            set { SetPropertyValue<string>(nameof(USRType), ref fUSRType, value); }
        }
        string fUSRDataType;
        [Size(50)]
        public string USRDataType
        {
            get { return fUSRDataType; }
            set { SetPropertyValue<string>(nameof(USRDataType), ref fUSRDataType, value); }
        }
        int fUSRDataTypeLength;
        public int USRDataTypeLength
        {
            get { return fUSRDataTypeLength; }
            set { SetPropertyValue<int>(nameof(USRDataTypeLength), ref fUSRDataTypeLength, value); }
        }
        string fUSRControlType;
        [Size(50)]
        public string USRControlType
        {
            get { return fUSRControlType; }
            set { SetPropertyValue<string>(nameof(USRControlType), ref fUSRControlType, value); }
        }
    }

}
