//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class tempFlyerData : XPLiteObject
    {
        Guid fFlyer_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid Flyer_ID
        {
            get { return fFlyer_ID; }
            set { SetPropertyValue<Guid>(nameof(Flyer_ID), ref fFlyer_ID, value); }
        }
        decimal fRow_IDX;
        public decimal Row_IDX
        {
            get { return fRow_IDX; }
            set { SetPropertyValue<decimal>(nameof(Row_IDX), ref fRow_IDX, value); }
        }
        int fMonth_Start;
        public int Month_Start
        {
            get { return fMonth_Start; }
            set { SetPropertyValue<int>(nameof(Month_Start), ref fMonth_Start, value); }
        }
        int fMonth_End;
        public int Month_End
        {
            get { return fMonth_End; }
            set { SetPropertyValue<int>(nameof(Month_End), ref fMonth_End, value); }
        }
        Guid fIM_Main_ID;
        public Guid IM_Main_ID
        {
            get { return fIM_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(IM_Main_ID), ref fIM_Main_ID, value); }
        }
        string fItem_Number_Main;
        [Size(25)]
        public string Item_Number_Main
        {
            get { return fItem_Number_Main; }
            set { SetPropertyValue<string>(nameof(Item_Number_Main), ref fItem_Number_Main, value); }
        }
        int fSet_Minimum_Order;
        public int Set_Minimum_Order
        {
            get { return fSet_Minimum_Order; }
            set { SetPropertyValue<int>(nameof(Set_Minimum_Order), ref fSet_Minimum_Order, value); }
        }
        int fSet_Multiple_Order;
        public int Set_Multiple_Order
        {
            get { return fSet_Multiple_Order; }
            set { SetPropertyValue<int>(nameof(Set_Multiple_Order), ref fSet_Multiple_Order, value); }
        }
        int fSet_QTY_1;
        public int Set_QTY_1
        {
            get { return fSet_QTY_1; }
            set { SetPropertyValue<int>(nameof(Set_QTY_1), ref fSet_QTY_1, value); }
        }
        decimal fSet_Price_1;
        public decimal Set_Price_1
        {
            get { return fSet_Price_1; }
            set { SetPropertyValue<decimal>(nameof(Set_Price_1), ref fSet_Price_1, value); }
        }
        int fSet_Commission_1;
        public int Set_Commission_1
        {
            get { return fSet_Commission_1; }
            set { SetPropertyValue<int>(nameof(Set_Commission_1), ref fSet_Commission_1, value); }
        }
        int fSet_QTY_2;
        public int Set_QTY_2
        {
            get { return fSet_QTY_2; }
            set { SetPropertyValue<int>(nameof(Set_QTY_2), ref fSet_QTY_2, value); }
        }
        decimal fSet_Price_2;
        public decimal Set_Price_2
        {
            get { return fSet_Price_2; }
            set { SetPropertyValue<decimal>(nameof(Set_Price_2), ref fSet_Price_2, value); }
        }
        int fSet_Commission_2;
        public int Set_Commission_2
        {
            get { return fSet_Commission_2; }
            set { SetPropertyValue<int>(nameof(Set_Commission_2), ref fSet_Commission_2, value); }
        }
        Guid fIM_Price_Sets_ID;
        [ColumnDbDefaultValue("(newid())")]
        public Guid IM_Price_Sets_ID
        {
            get { return fIM_Price_Sets_ID; }
            set { SetPropertyValue<Guid>(nameof(IM_Price_Sets_ID), ref fIM_Price_Sets_ID, value); }
        }
        int fBL;
        public int BL
        {
            get { return fBL; }
            set { SetPropertyValue<int>(nameof(BL), ref fBL, value); }
        }
        decimal fCost;
        public decimal Cost
        {
            get { return fCost; }
            set { SetPropertyValue<decimal>(nameof(Cost), ref fCost, value); }
        }
        bool fProcessed;
        [ColumnDbDefaultValue("((0))")]
        public bool Processed
        {
            get { return fProcessed; }
            set { SetPropertyValue<bool>(nameof(Processed), ref fProcessed, value); }
        }
        bool fValid;
        [ColumnDbDefaultValue("((1))")]
        public bool Valid
        {
            get { return fValid; }
            set { SetPropertyValue<bool>(nameof(Valid), ref fValid, value); }
        }
        Guid fBatch_ID;
        public Guid Batch_ID
        {
            get { return fBatch_ID; }
            set { SetPropertyValue<Guid>(nameof(Batch_ID), ref fBatch_ID, value); }
        }
        string fMatch_ID;
        [Size(203)]
        public string Match_ID
        {
            get { return fMatch_ID; }
            set { SetPropertyValue<string>(nameof(Match_ID), ref fMatch_ID, value); }
        }
    }

}
