//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class TrackDefaultEvents : XPLiteObject
    {
        int fDefaultID;
        [Key(true)]
        public int DefaultID
        {
            get { return fDefaultID; }
            set { SetPropertyValue<int>(nameof(DefaultID), ref fDefaultID, value); }
        }
        string fDefaultName;
        [Size(250)]
        public string DefaultName
        {
            get { return fDefaultName; }
            set { SetPropertyValue<string>(nameof(DefaultName), ref fDefaultName, value); }
        }
        string fDefaultDescription;
        [Size(250)]
        public string DefaultDescription
        {
            get { return fDefaultDescription; }
            set { SetPropertyValue<string>(nameof(DefaultDescription), ref fDefaultDescription, value); }
        }
        string fReportingPoint;
        [Size(250)]
        public string ReportingPoint
        {
            get { return fReportingPoint; }
            set { SetPropertyValue<string>(nameof(ReportingPoint), ref fReportingPoint, value); }
        }
        TrackingType fTrackingTypeID;
        [Association(@"TrackDefaultEventsReferencesTrackingType")]
        public TrackingType TrackingTypeID
        {
            get { return fTrackingTypeID; }
            set { SetPropertyValue<TrackingType>(nameof(TrackingTypeID), ref fTrackingTypeID, value); }
        }
        bool fAutoAdd;
        public bool AutoAdd
        {
            get { return fAutoAdd; }
            set { SetPropertyValue<bool>(nameof(AutoAdd), ref fAutoAdd, value); }
        }
        int fOrder;
        public int Order
        {
            get { return fOrder; }
            set { SetPropertyValue<int>(nameof(Order), ref fOrder, value); }
        }
        int fDaysToComplete;
        public int DaysToComplete
        {
            get { return fDaysToComplete; }
            set { SetPropertyValue<int>(nameof(DaysToComplete), ref fDaysToComplete, value); }
        }
        string fDefaultUser;
        [Size(250)]
        public string DefaultUser
        {
            get { return fDefaultUser; }
            set { SetPropertyValue<string>(nameof(DefaultUser), ref fDefaultUser, value); }
        }
    }

}
