//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class TrackEvents : XPLiteObject
    {
        int fEventID;
        [Key(true)]
        public int EventID
        {
            get { return fEventID; }
            set { SetPropertyValue<int>(nameof(EventID), ref fEventID, value); }
        }
        TrackingJobs fJobID;
        [Association(@"TrackEventsReferencesTrackingJobs")]
        public TrackingJobs JobID
        {
            get { return fJobID; }
            set { SetPropertyValue<TrackingJobs>(nameof(JobID), ref fJobID, value); }
        }
        string fEventName;
        [Size(250)]
        public string EventName
        {
            get { return fEventName; }
            set { SetPropertyValue<string>(nameof(EventName), ref fEventName, value); }
        }
        string fDescription;
        [Size(250)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fReportingPoint;
        [Size(250)]
        public string ReportingPoint
        {
            get { return fReportingPoint; }
            set { SetPropertyValue<string>(nameof(ReportingPoint), ref fReportingPoint, value); }
        }
        DateTime fDateStarted;
        public DateTime DateStarted
        {
            get { return fDateStarted; }
            set { SetPropertyValue<DateTime>(nameof(DateStarted), ref fDateStarted, value); }
        }
        DateTime fDateCompleted;
        public DateTime DateCompleted
        {
            get { return fDateCompleted; }
            set { SetPropertyValue<DateTime>(nameof(DateCompleted), ref fDateCompleted, value); }
        }
        DateTime fDateDue;
        public DateTime DateDue
        {
            get { return fDateDue; }
            set { SetPropertyValue<DateTime>(nameof(DateDue), ref fDateDue, value); }
        }
        TrackingStatus fStatusID;
        [Association(@"TrackEventsReferencesTrackingStatus")]
        public TrackingStatus StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<TrackingStatus>(nameof(StatusID), ref fStatusID, value); }
        }
        int fOrder;
        public int Order
        {
            get { return fOrder; }
            set { SetPropertyValue<int>(nameof(Order), ref fOrder, value); }
        }
        int fNotified;
        public int Notified
        {
            get { return fNotified; }
            set { SetPropertyValue<int>(nameof(Notified), ref fNotified, value); }
        }
        string fAssignedUser;
        [Size(250)]
        public string AssignedUser
        {
            get { return fAssignedUser; }
            set { SetPropertyValue<string>(nameof(AssignedUser), ref fAssignedUser, value); }
        }
        string fmemo;
        [Size(SizeAttribute.Unlimited)]
        public string memo
        {
            get { return fmemo; }
            set { SetPropertyValue<string>(nameof(memo), ref fmemo, value); }
        }
        int fDefaultDaystoComplete;
        public int DefaultDaystoComplete
        {
            get { return fDefaultDaystoComplete; }
            set { SetPropertyValue<int>(nameof(DefaultDaystoComplete), ref fDefaultDaystoComplete, value); }
        }
        int fDaysToComplete;
        public int DaysToComplete
        {
            get { return fDaysToComplete; }
            set { SetPropertyValue<int>(nameof(DaysToComplete), ref fDaysToComplete, value); }
        }
    }

}
