//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class TrackingStatus : XPLiteObject
    {
        int fStatusID;
        [Key(true)]
        public int StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<int>(nameof(StatusID), ref fStatusID, value); }
        }
        string fStatusName;
        [Size(250)]
        public string StatusName
        {
            get { return fStatusName; }
            set { SetPropertyValue<string>(nameof(StatusName), ref fStatusName, value); }
        }
        byte[] fImage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Image
        {
            get { return fImage; }
            set { SetPropertyValue<byte[]>(nameof(Image), ref fImage, value); }
        }
        [Association(@"TrackEventsReferencesTrackingStatus")]
        public XPCollection<TrackEvents> TrackEventsCollection { get { return GetCollection<TrackEvents>(nameof(TrackEventsCollection)); } }
        [Association(@"TrackingJobsReferencesTrackingStatus")]
        public XPCollection<TrackingJobs> TrackingJobsCollection { get { return GetCollection<TrackingJobs>(nameof(TrackingJobsCollection)); } }
    }

}
