//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class TrackingType : XPLiteObject
    {
        int fTrackingTypeID;
        [Key(true)]
        public int TrackingTypeID
        {
            get { return fTrackingTypeID; }
            set { SetPropertyValue<int>(nameof(TrackingTypeID), ref fTrackingTypeID, value); }
        }
        string fTrackingTypeName;
        [Size(250)]
        public string TrackingTypeName
        {
            get { return fTrackingTypeName; }
            set { SetPropertyValue<string>(nameof(TrackingTypeName), ref fTrackingTypeName, value); }
        }
        [Association(@"TrackDefaultEventsReferencesTrackingType")]
        public XPCollection<TrackDefaultEvents> TrackDefaultEventsCollection { get { return GetCollection<TrackDefaultEvents>(nameof(TrackDefaultEventsCollection)); } }
        [Association(@"TrackingJobsReferencesTrackingType")]
        public XPCollection<TrackingJobs> TrackingJobsCollection { get { return GetCollection<TrackingJobs>(nameof(TrackingJobsCollection)); } }
    }

}
