//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class TrackingJobs : XPLiteObject
    {
        int fJobID;
        [Key(true)]
        public int JobID
        {
            get { return fJobID; }
            set { SetPropertyValue<int>(nameof(JobID), ref fJobID, value); }
        }
        string fJobName;
        [Size(250)]
        public string JobName
        {
            get { return fJobName; }
            set { SetPropertyValue<string>(nameof(JobName), ref fJobName, value); }
        }
        int fFormID;
        public int FormID
        {
            get { return fFormID; }
            set { SetPropertyValue<int>(nameof(FormID), ref fFormID, value); }
        }
        int fPhysicianID;
        public int PhysicianID
        {
            get { return fPhysicianID; }
            set { SetPropertyValue<int>(nameof(PhysicianID), ref fPhysicianID, value); }
        }
        TrackingStatus fStatusID;
        [Association(@"TrackingJobsReferencesTrackingStatus")]
        public TrackingStatus StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<TrackingStatus>(nameof(StatusID), ref fStatusID, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        DateTime fDateClosed;
        public DateTime DateClosed
        {
            get { return fDateClosed; }
            set { SetPropertyValue<DateTime>(nameof(DateClosed), ref fDateClosed, value); }
        }
        TrackingType fTrackingTypeID;
        [Association(@"TrackingJobsReferencesTrackingType")]
        public TrackingType TrackingTypeID
        {
            get { return fTrackingTypeID; }
            set { SetPropertyValue<TrackingType>(nameof(TrackingTypeID), ref fTrackingTypeID, value); }
        }
        int fSecurityID;
        public int SecurityID
        {
            get { return fSecurityID; }
            set { SetPropertyValue<int>(nameof(SecurityID), ref fSecurityID, value); }
        }
        int fOfficeID;
        public int OfficeID
        {
            get { return fOfficeID; }
            set { SetPropertyValue<int>(nameof(OfficeID), ref fOfficeID, value); }
        }
        DateTime fEffectiveDate;
        public DateTime EffectiveDate
        {
            get { return fEffectiveDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveDate), ref fEffectiveDate, value); }
        }
        int fNotified;
        public int Notified
        {
            get { return fNotified; }
            set { SetPropertyValue<int>(nameof(Notified), ref fNotified, value); }
        }
        string fFormName;
        [Size(250)]
        public string FormName
        {
            get { return fFormName; }
            set { SetPropertyValue<string>(nameof(FormName), ref fFormName, value); }
        }
        string fmemo;
        [Size(SizeAttribute.Unlimited)]
        public string memo
        {
            get { return fmemo; }
            set { SetPropertyValue<string>(nameof(memo), ref fmemo, value); }
        }
        Guid fEntityGuid;
        public Guid EntityGuid
        {
            get { return fEntityGuid; }
            set { SetPropertyValue<Guid>(nameof(EntityGuid), ref fEntityGuid, value); }
        }
        string fDocument;
        [Size(1000)]
        public string Document
        {
            get { return fDocument; }
            set { SetPropertyValue<string>(nameof(Document), ref fDocument, value); }
        }
        string fJobReportingPoint;
        [Size(250)]
        public string JobReportingPoint
        {
            get { return fJobReportingPoint; }
            set { SetPropertyValue<string>(nameof(JobReportingPoint), ref fJobReportingPoint, value); }
        }
        string fJobAssignedUser;
        [Size(250)]
        public string JobAssignedUser
        {
            get { return fJobAssignedUser; }
            set { SetPropertyValue<string>(nameof(JobAssignedUser), ref fJobAssignedUser, value); }
        }
        [Association(@"TrackEventsReferencesTrackingJobs")]
        public XPCollection<TrackEvents> TrackEventsCollection { get { return GetCollection<TrackEvents>(nameof(TrackEventsCollection)); } }
    }

}
