//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class TS_Main : XPLiteObject
    {
        Guid fTS_Main_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid TS_Main_ID
        {
            get { return fTS_Main_ID; }
            set { SetPropertyValue<Guid>(nameof(TS_Main_ID), ref fTS_Main_ID, value); }
        }
        string fShow_Name;
        [Size(50)]
        public string Show_Name
        {
            get { return fShow_Name; }
            set { SetPropertyValue<string>(nameof(Show_Name), ref fShow_Name, value); }
        }
        string fShow_Name_Short;
        [Size(15)]
        public string Show_Name_Short
        {
            get { return fShow_Name_Short; }
            set { SetPropertyValue<string>(nameof(Show_Name_Short), ref fShow_Name_Short, value); }
        }
        int fShow_Name_ID;
        public int Show_Name_ID
        {
            get { return fShow_Name_ID; }
            set { SetPropertyValue<int>(nameof(Show_Name_ID), ref fShow_Name_ID, value); }
        }
        decimal fOrdered;
        public decimal Ordered
        {
            get { return fOrdered; }
            set { SetPropertyValue<decimal>(nameof(Ordered), ref fOrdered, value); }
        }
        int fShow_Parent_ID;
        public int Show_Parent_ID
        {
            get { return fShow_Parent_ID; }
            set { SetPropertyValue<int>(nameof(Show_Parent_ID), ref fShow_Parent_ID, value); }
        }
        int fOrder_Number;
        public int Order_Number
        {
            get { return fOrder_Number; }
            set { SetPropertyValue<int>(nameof(Order_Number), ref fOrder_Number, value); }
        }
        int fNext_Gift_Show_Number;
        public int Next_Gift_Show_Number
        {
            get { return fNext_Gift_Show_Number; }
            set { SetPropertyValue<int>(nameof(Next_Gift_Show_Number), ref fNext_Gift_Show_Number, value); }
        }
        DateTime fShow_Date_Start_Previous;
        public DateTime Show_Date_Start_Previous
        {
            get { return fShow_Date_Start_Previous; }
            set { SetPropertyValue<DateTime>(nameof(Show_Date_Start_Previous), ref fShow_Date_Start_Previous, value); }
        }
        DateTime fShow_Date_Stop_Previous;
        public DateTime Show_Date_Stop_Previous
        {
            get { return fShow_Date_Stop_Previous; }
            set { SetPropertyValue<DateTime>(nameof(Show_Date_Stop_Previous), ref fShow_Date_Stop_Previous, value); }
        }
        DateTime fShow_Date_Start_Current;
        public DateTime Show_Date_Start_Current
        {
            get { return fShow_Date_Start_Current; }
            set { SetPropertyValue<DateTime>(nameof(Show_Date_Start_Current), ref fShow_Date_Start_Current, value); }
        }
        DateTime fShow_Date_Stop_Current;
        public DateTime Show_Date_Stop_Current
        {
            get { return fShow_Date_Stop_Current; }
            set { SetPropertyValue<DateTime>(nameof(Show_Date_Stop_Current), ref fShow_Date_Stop_Current, value); }
        }
        DateTime fShow_Date_Start_Next;
        public DateTime Show_Date_Start_Next
        {
            get { return fShow_Date_Start_Next; }
            set { SetPropertyValue<DateTime>(nameof(Show_Date_Start_Next), ref fShow_Date_Start_Next, value); }
        }
        DateTime fShow_Date_Stop_Next;
        public DateTime Show_Date_Stop_Next
        {
            get { return fShow_Date_Stop_Next; }
            set { SetPropertyValue<DateTime>(nameof(Show_Date_Stop_Next), ref fShow_Date_Stop_Next, value); }
        }
        string fShow_Previous_Booth_Numbers;
        [Size(40)]
        public string Show_Previous_Booth_Numbers
        {
            get { return fShow_Previous_Booth_Numbers; }
            set { SetPropertyValue<string>(nameof(Show_Previous_Booth_Numbers), ref fShow_Previous_Booth_Numbers, value); }
        }
        string fShow_Current_Booth_Numbers;
        [Size(40)]
        public string Show_Current_Booth_Numbers
        {
            get { return fShow_Current_Booth_Numbers; }
            set { SetPropertyValue<string>(nameof(Show_Current_Booth_Numbers), ref fShow_Current_Booth_Numbers, value); }
        }
        string fShow_Next_Booth_Numbers;
        [Size(40)]
        public string Show_Next_Booth_Numbers
        {
            get { return fShow_Next_Booth_Numbers; }
            set { SetPropertyValue<string>(nameof(Show_Next_Booth_Numbers), ref fShow_Next_Booth_Numbers, value); }
        }
        int fShow_Orders_Previous_Year;
        public int Show_Orders_Previous_Year
        {
            get { return fShow_Orders_Previous_Year; }
            set { SetPropertyValue<int>(nameof(Show_Orders_Previous_Year), ref fShow_Orders_Previous_Year, value); }
        }
        int fShow_Orders_Current_Year;
        public int Show_Orders_Current_Year
        {
            get { return fShow_Orders_Current_Year; }
            set { SetPropertyValue<int>(nameof(Show_Orders_Current_Year), ref fShow_Orders_Current_Year, value); }
        }
        int fShow_Orders_Next_Year;
        public int Show_Orders_Next_Year
        {
            get { return fShow_Orders_Next_Year; }
            set { SetPropertyValue<int>(nameof(Show_Orders_Next_Year), ref fShow_Orders_Next_Year, value); }
        }
        decimal fShow_Order_Amount_Previous_Year;
        public decimal Show_Order_Amount_Previous_Year
        {
            get { return fShow_Order_Amount_Previous_Year; }
            set { SetPropertyValue<decimal>(nameof(Show_Order_Amount_Previous_Year), ref fShow_Order_Amount_Previous_Year, value); }
        }
        decimal fShow_Order_Amount_Current_Year;
        public decimal Show_Order_Amount_Current_Year
        {
            get { return fShow_Order_Amount_Current_Year; }
            set { SetPropertyValue<decimal>(nameof(Show_Order_Amount_Current_Year), ref fShow_Order_Amount_Current_Year, value); }
        }
        decimal fShow_Order_Amount_Next_Year;
        public decimal Show_Order_Amount_Next_Year
        {
            get { return fShow_Order_Amount_Next_Year; }
            set { SetPropertyValue<decimal>(nameof(Show_Order_Amount_Next_Year), ref fShow_Order_Amount_Next_Year, value); }
        }
        string fShow_Location_Address_Previous_Year;
        [Size(SizeAttribute.Unlimited)]
        public string Show_Location_Address_Previous_Year
        {
            get { return fShow_Location_Address_Previous_Year; }
            set { SetPropertyValue<string>(nameof(Show_Location_Address_Previous_Year), ref fShow_Location_Address_Previous_Year, value); }
        }
        string fShow_Location_Address_Current_Year;
        [Size(SizeAttribute.Unlimited)]
        public string Show_Location_Address_Current_Year
        {
            get { return fShow_Location_Address_Current_Year; }
            set { SetPropertyValue<string>(nameof(Show_Location_Address_Current_Year), ref fShow_Location_Address_Current_Year, value); }
        }
        string fShow_Location_Address_Next_Year;
        [Size(SizeAttribute.Unlimited)]
        public string Show_Location_Address_Next_Year
        {
            get { return fShow_Location_Address_Next_Year; }
            set { SetPropertyValue<string>(nameof(Show_Location_Address_Next_Year), ref fShow_Location_Address_Next_Year, value); }
        }
        string fShow_Ship_Address_Previous_Year;
        [Size(SizeAttribute.Unlimited)]
        public string Show_Ship_Address_Previous_Year
        {
            get { return fShow_Ship_Address_Previous_Year; }
            set { SetPropertyValue<string>(nameof(Show_Ship_Address_Previous_Year), ref fShow_Ship_Address_Previous_Year, value); }
        }
        string fShow_Ship_Address_Current_Year;
        [Size(SizeAttribute.Unlimited)]
        public string Show_Ship_Address_Current_Year
        {
            get { return fShow_Ship_Address_Current_Year; }
            set { SetPropertyValue<string>(nameof(Show_Ship_Address_Current_Year), ref fShow_Ship_Address_Current_Year, value); }
        }
        string fShow_Ship_Address_Next_Year;
        [Size(SizeAttribute.Unlimited)]
        public string Show_Ship_Address_Next_Year
        {
            get { return fShow_Ship_Address_Next_Year; }
            set { SetPropertyValue<string>(nameof(Show_Ship_Address_Next_Year), ref fShow_Ship_Address_Next_Year, value); }
        }
        bool fDelete_Flag;
        public bool Delete_Flag
        {
            get { return fDelete_Flag; }
            set { SetPropertyValue<bool>(nameof(Delete_Flag), ref fDelete_Flag, value); }
        }
        bool fShow_Group_Flag;
        public bool Show_Group_Flag
        {
            get { return fShow_Group_Flag; }
            set { SetPropertyValue<bool>(nameof(Show_Group_Flag), ref fShow_Group_Flag, value); }
        }
        bool fINActive_Flag;
        public bool INActive_Flag
        {
            get { return fINActive_Flag; }
            set { SetPropertyValue<bool>(nameof(INActive_Flag), ref fINActive_Flag, value); }
        }
        string fShow_State;
        [Size(2)]
        public string Show_State
        {
            get { return fShow_State; }
            set { SetPropertyValue<string>(nameof(Show_State), ref fShow_State, value); }
        }
        string fAlpha;
        [Size(1)]
        public string Alpha
        {
            get { return fAlpha; }
            set { SetPropertyValue<string>(nameof(Alpha), ref fAlpha, value); }
        }
        bool fDelete_Flag_Check;
        public bool Delete_Flag_Check
        {
            get { return fDelete_Flag_Check; }
            set { SetPropertyValue<bool>(nameof(Delete_Flag_Check), ref fDelete_Flag_Check, value); }
        }
        bool fINActive_Flag_Check;
        public bool INActive_Flag_Check
        {
            get { return fINActive_Flag_Check; }
            set { SetPropertyValue<bool>(nameof(INActive_Flag_Check), ref fINActive_Flag_Check, value); }
        }
    }

}
