//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class UD_Options : XPLiteObject
    {
        Guid fUD_Options_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid UD_Options_ID
        {
            get { return fUD_Options_ID; }
            set { SetPropertyValue<Guid>(nameof(UD_Options_ID), ref fUD_Options_ID, value); }
        }
        UD_Main fUD_Main_ID;
        [Association(@"UD_OptionsReferencesUD_Main")]
        public UD_Main UD_Main_ID
        {
            get { return fUD_Main_ID; }
            set { SetPropertyValue<UD_Main>(nameof(UD_Main_ID), ref fUD_Main_ID, value); }
        }
        bool fAccount_Manager;
        public bool Account_Manager
        {
            get { return fAccount_Manager; }
            set { SetPropertyValue<bool>(nameof(Account_Manager), ref fAccount_Manager, value); }
        }
        string fUser_Name_Link;
        [Size(50)]
        public string User_Name_Link
        {
            get { return fUser_Name_Link; }
            set { SetPropertyValue<string>(nameof(User_Name_Link), ref fUser_Name_Link, value); }
        }
        pl_Department_Name fDepartment;
        [Association(@"UD_OptionsReferencespl_Department_Name")]
        public pl_Department_Name Department
        {
            get { return fDepartment; }
            set { SetPropertyValue<pl_Department_Name>(nameof(Department), ref fDepartment, value); }
        }
        pl_User_Title fTitle;
        [Association(@"UD_OptionsReferencespl_User_Title")]
        public pl_User_Title Title
        {
            get { return fTitle; }
            set { SetPropertyValue<pl_User_Title>(nameof(Title), ref fTitle, value); }
        }
        string fScanner_Access;
        [Size(255)]
        public string Scanner_Access
        {
            get { return fScanner_Access; }
            set { SetPropertyValue<string>(nameof(Scanner_Access), ref fScanner_Access, value); }
        }
        bool fWrites_Order;
        public bool Writes_Order
        {
            get { return fWrites_Order; }
            set { SetPropertyValue<bool>(nameof(Writes_Order), ref fWrites_Order, value); }
        }
        bool fAtShow;
        public bool AtShow
        {
            get { return fAtShow; }
            set { SetPropertyValue<bool>(nameof(AtShow), ref fAtShow, value); }
        }
        string fUserPassword;
        [Size(50)]
        public string UserPassword
        {
            get { return fUserPassword; }
            set { SetPropertyValue<string>(nameof(UserPassword), ref fUserPassword, value); }
        }
        int fAccessLevel;
        public int AccessLevel
        {
            get { return fAccessLevel; }
            set { SetPropertyValue<int>(nameof(AccessLevel), ref fAccessLevel, value); }
        }
        bool fManagement_Flag;
        public bool Management_Flag
        {
            get { return fManagement_Flag; }
            set { SetPropertyValue<bool>(nameof(Management_Flag), ref fManagement_Flag, value); }
        }
        bool fOverridePrice_Flag;
        public bool OverridePrice_Flag
        {
            get { return fOverridePrice_Flag; }
            set { SetPropertyValue<bool>(nameof(OverridePrice_Flag), ref fOverridePrice_Flag, value); }
        }
        bool fOverrideCreditMemo_Flag;
        public bool OverrideCreditMemo_Flag
        {
            get { return fOverrideCreditMemo_Flag; }
            set { SetPropertyValue<bool>(nameof(OverrideCreditMemo_Flag), ref fOverrideCreditMemo_Flag, value); }
        }
        bool fOverrideOrderTotal_Flag;
        public bool OverrideOrderTotal_Flag
        {
            get { return fOverrideOrderTotal_Flag; }
            set { SetPropertyValue<bool>(nameof(OverrideOrderTotal_Flag), ref fOverrideOrderTotal_Flag, value); }
        }
        bool fOverrideMinQTY_Flag;
        public bool OverrideMinQTY_Flag
        {
            get { return fOverrideMinQTY_Flag; }
            set { SetPropertyValue<bool>(nameof(OverrideMinQTY_Flag), ref fOverrideMinQTY_Flag, value); }
        }
        bool fOverride_AR_Flag;
        public bool Override_AR_Flag
        {
            get { return fOverride_AR_Flag; }
            set { SetPropertyValue<bool>(nameof(Override_AR_Flag), ref fOverride_AR_Flag, value); }
        }
        bool fOffice_Flag;
        public bool Office_Flag
        {
            get { return fOffice_Flag; }
            set { SetPropertyValue<bool>(nameof(Office_Flag), ref fOffice_Flag, value); }
        }
        bool fWarehouse_Flag;
        public bool Warehouse_Flag
        {
            get { return fWarehouse_Flag; }
            set { SetPropertyValue<bool>(nameof(Warehouse_Flag), ref fWarehouse_Flag, value); }
        }
        bool fSalesman_Flag;
        public bool Salesman_Flag
        {
            get { return fSalesman_Flag; }
            set { SetPropertyValue<bool>(nameof(Salesman_Flag), ref fSalesman_Flag, value); }
        }
        bool fRemoteAccess_Flag;
        public bool RemoteAccess_Flag
        {
            get { return fRemoteAccess_Flag; }
            set { SetPropertyValue<bool>(nameof(RemoteAccess_Flag), ref fRemoteAccess_Flag, value); }
        }
        bool fDataEntry_Flag;
        public bool DataEntry_Flag
        {
            get { return fDataEntry_Flag; }
            set { SetPropertyValue<bool>(nameof(DataEntry_Flag), ref fDataEntry_Flag, value); }
        }
        bool fScanOrders_Flag;
        public bool ScanOrders_Flag
        {
            get { return fScanOrders_Flag; }
            set { SetPropertyValue<bool>(nameof(ScanOrders_Flag), ref fScanOrders_Flag, value); }
        }
        bool fAtShow_Flag;
        public bool AtShow_Flag
        {
            get { return fAtShow_Flag; }
            set { SetPropertyValue<bool>(nameof(AtShow_Flag), ref fAtShow_Flag, value); }
        }
        bool fBuyer_Flag;
        public bool Buyer_Flag
        {
            get { return fBuyer_Flag; }
            set { SetPropertyValue<bool>(nameof(Buyer_Flag), ref fBuyer_Flag, value); }
        }
        bool fPicker_Flag;
        public bool Picker_Flag
        {
            get { return fPicker_Flag; }
            set { SetPropertyValue<bool>(nameof(Picker_Flag), ref fPicker_Flag, value); }
        }
        bool fPacker_Flag;
        public bool Packer_Flag
        {
            get { return fPacker_Flag; }
            set { SetPropertyValue<bool>(nameof(Packer_Flag), ref fPacker_Flag, value); }
        }
        bool fChecker_Flag;
        public bool Checker_Flag
        {
            get { return fChecker_Flag; }
            set { SetPropertyValue<bool>(nameof(Checker_Flag), ref fChecker_Flag, value); }
        }
        bool fShipper_Flag;
        public bool Shipper_Flag
        {
            get { return fShipper_Flag; }
            set { SetPropertyValue<bool>(nameof(Shipper_Flag), ref fShipper_Flag, value); }
        }
        bool fWriteUp_Flag;
        public bool WriteUp_Flag
        {
            get { return fWriteUp_Flag; }
            set { SetPropertyValue<bool>(nameof(WriteUp_Flag), ref fWriteUp_Flag, value); }
        }
        bool fStocker_Flag;
        public bool Stocker_Flag
        {
            get { return fStocker_Flag; }
            set { SetPropertyValue<bool>(nameof(Stocker_Flag), ref fStocker_Flag, value); }
        }
        bool fInventory_Flag;
        public bool Inventory_Flag
        {
            get { return fInventory_Flag; }
            set { SetPropertyValue<bool>(nameof(Inventory_Flag), ref fInventory_Flag, value); }
        }
        bool fHold_Customer_OE;
        public bool Hold_Customer_OE
        {
            get { return fHold_Customer_OE; }
            set { SetPropertyValue<bool>(nameof(Hold_Customer_OE), ref fHold_Customer_OE, value); }
        }
    }

}
