//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class wkAccessSecurity : XPLiteObject
    {
        Guid fwkAccessSecurity_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid wkAccessSecurity_ID
        {
            get { return fwkAccessSecurity_ID; }
            set { SetPropertyValue<Guid>(nameof(wkAccessSecurity_ID), ref fwkAccessSecurity_ID, value); }
        }
        int fAccessItemID;
        public int AccessItemID
        {
            get { return fAccessItemID; }
            set { SetPropertyValue<int>(nameof(AccessItemID), ref fAccessItemID, value); }
        }
        string fAccessItemName;
        [Size(250)]
        public string AccessItemName
        {
            get { return fAccessItemName; }
            set { SetPropertyValue<string>(nameof(AccessItemName), ref fAccessItemName, value); }
        }
        string fAccessItemDescription;
        [Size(500)]
        public string AccessItemDescription
        {
            get { return fAccessItemDescription; }
            set { SetPropertyValue<string>(nameof(AccessItemDescription), ref fAccessItemDescription, value); }
        }
        int fType;
        public int Type
        {
            get { return fType; }
            set { SetPropertyValue<int>(nameof(Type), ref fType, value); }
        }
        string fScreenName;
        [Size(250)]
        public string ScreenName
        {
            get { return fScreenName; }
            set { SetPropertyValue<string>(nameof(ScreenName), ref fScreenName, value); }
        }
        string fQuery;
        [Size(500)]
        public string Query
        {
            get { return fQuery; }
            set { SetPropertyValue<string>(nameof(Query), ref fQuery, value); }
        }
        string fCategory;
        [Size(50)]
        public string Category
        {
            get { return fCategory; }
            set { SetPropertyValue<string>(nameof(Category), ref fCategory, value); }
        }
    }

}
