//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class wkBCI_Security_GroupsX : XPLiteObject
    {
        Guid fBCI_Group_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid BCI_Group_ID
        {
            get { return fBCI_Group_ID; }
            set { SetPropertyValue<Guid>(nameof(BCI_Group_ID), ref fBCI_Group_ID, value); }
        }
        int fSymed_Group_ID;
        public int Symed_Group_ID
        {
            get { return fSymed_Group_ID; }
            set { SetPropertyValue<int>(nameof(Symed_Group_ID), ref fSymed_Group_ID, value); }
        }
        string fBCI_Group_Name;
        [Size(250)]
        public string BCI_Group_Name
        {
            get { return fBCI_Group_Name; }
            set { SetPropertyValue<string>(nameof(BCI_Group_Name), ref fBCI_Group_Name, value); }
        }
        int fGroup_Order;
        public int Group_Order
        {
            get { return fGroup_Order; }
            set { SetPropertyValue<int>(nameof(Group_Order), ref fGroup_Order, value); }
        }
        int fSymed_Access_ID;
        public int Symed_Access_ID
        {
            get { return fSymed_Access_ID; }
            set { SetPropertyValue<int>(nameof(Symed_Access_ID), ref fSymed_Access_ID, value); }
        }
    }

}
