//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class wkTreeLevelnLink : XPLiteObject
    {
        Guid fwkTreeLevelnLink_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid wkTreeLevelnLink_ID
        {
            get { return fwkTreeLevelnLink_ID; }
            set { SetPropertyValue<Guid>(nameof(wkTreeLevelnLink_ID), ref fwkTreeLevelnLink_ID, value); }
        }
        int fAutoID_Security;
        public int AutoID_Security
        {
            get { return fAutoID_Security; }
            set { SetPropertyValue<int>(nameof(AutoID_Security), ref fAutoID_Security, value); }
        }
        string fTreeName;
        [Size(250)]
        public string TreeName
        {
            get { return fTreeName; }
            set { SetPropertyValue<string>(nameof(TreeName), ref fTreeName, value); }
        }
        string fLevelName;
        [Size(50)]
        public string LevelName
        {
            get { return fLevelName; }
            set { SetPropertyValue<string>(nameof(LevelName), ref fLevelName, value); }
        }
        string fScreenName;
        [Size(250)]
        public string ScreenName
        {
            get { return fScreenName; }
            set { SetPropertyValue<string>(nameof(ScreenName), ref fScreenName, value); }
        }
        int fOrder;
        public int Order
        {
            get { return fOrder; }
            set { SetPropertyValue<int>(nameof(Order), ref fOrder, value); }
        }
    }

}
