//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace OldDatabaseRestore.Module.BusinessObjects.BCI_Database_V2A2013
{

    public partial class WU_ERRORS : XPLiteObject
    {
        Guid fWU_ERRORS_ID;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid WU_ERRORS_ID
        {
            get { return fWU_ERRORS_ID; }
            set { SetPropertyValue<Guid>(nameof(WU_ERRORS_ID), ref fWU_ERRORS_ID, value); }
        }
        RM_Main fRM_Main_ID;
        [Association(@"WU_ERRORSReferencesRM_Main")]
        public RM_Main RM_Main_ID
        {
            get { return fRM_Main_ID; }
            set { SetPropertyValue<RM_Main>(nameof(RM_Main_ID), ref fRM_Main_ID, value); }
        }
        int fNew_Line_Number;
        public int New_Line_Number
        {
            get { return fNew_Line_Number; }
            set { SetPropertyValue<int>(nameof(New_Line_Number), ref fNew_Line_Number, value); }
        }
        int fQTY;
        public int QTY
        {
            get { return fQTY; }
            set { SetPropertyValue<int>(nameof(QTY), ref fQTY, value); }
        }
        pl_Unit fUnit;
        [Association(@"WU_ERRORSReferencespl_Unit")]
        public pl_Unit Unit
        {
            get { return fUnit; }
            set { SetPropertyValue<pl_Unit>(nameof(Unit), ref fUnit, value); }
        }
        int fSell_BL;
        public int Sell_BL
        {
            get { return fSell_BL; }
            set { SetPropertyValue<int>(nameof(Sell_BL), ref fSell_BL, value); }
        }
    }

}
